import { readdirSync, readFileSync, statSync } from "node:fs";

type StaticSafetyCheck = {
  file: string;
  forbidden: RegExp[];
  required?: string[];
};

const checks: StaticSafetyCheck[] = [
  {
    file: "src/lib/dateKeys.ts",
    forbidden: [],
    required: [
      'const HU_TIME_ZONE = "Europe/Budapest"',
      "export function huTodayKey",
      "export function addDaysToDateKey",
    ],
  },
  {
    file: "src/lib/storage.ts",
    forbidden: [/new Date\(\)\.toISOString\(\)\.slice\(0, 10\)/],
    required: ['import { huTodayKey } from "./dateKeys";', "return huTodayKey();"],
  },
  {
    file: "src/routes/szerencseszamok.tsx",
    forbidden: [/new Date\(\)\.toISOString\(\)\.slice\(0, 10\)/],
    required: ['import { huTodayKey } from "@/lib/dateKeys";', "return huTodayKey();"],
  },
  {
    file: "src/data/magazin.hu.ts",
    forbidden: [/now\.toISOString\(\)\.slice\(0, 10\)/],
    required: ['import { huTodayKey } from "@/lib/dateKeys";', "const today = huTodayKey(now);"],
  },
  {
    file: "src/lib/paidReadings.ts",
    forbidden: [/new Date\(\)\.toISOString\(\)\.slice\(0, 10\)/],
    required: [
      'import { huTodayKey } from "./dateKeys";',
      "dateKey: text(input.dateKey) || huTodayKey()",
    ],
  },
  {
    file: "src/lib/roxy.functions.ts",
    forbidden: [/new Date\(\)\.toISOString\(\)\.slice\(0, 10\)/],
    required: [
      'import { huTodayKey } from "./dateKeys";',
      "const date = data.date ?? huTodayKey();",
      "const dateKey = data.dateKey ?? huTodayKey();",
    ],
  },
  {
    file: "src/lib/roxy.server.ts",
    forbidden: [
      /errorMessage: "ROXY_API_KEY/i,
      /errorMessage: err instanceof Error/i,
      /errorMessage: `Roxy/i,
      /errorMessage: "Roxy nem JSON/i,
      /HTTP \$\{res\.status\}/i,
      /Call a Roxy endpoint/i,
      /Roxy is unavailable/i,
      /ROXY_API_KEY from process\.env/i,
    ],
    required: [
      'providerCode: "missing_api_key"',
      'providerCode: "network_error"',
      'providerCode: "invalid_json"',
      'errorMessage: "A szimbolikus forrásanyag most nem érhető el."',
      "server-side symbolic source key",
      "source material is absent",
    ],
  },
  {
    file: "src/routes/sitemap[.]xml.tsx",
    forbidden: [/new Date\(\)\.toISOString\(\)\.slice\(0, 10\)/],
    required: ['import { huTodayKey } from "@/lib/dateKeys";', "const today = huTodayKey();"],
  },
  {
    file: "src/components/PaidReadingBody.tsx",
    forbidden: [
      /new Date\(\)\.toISOString\(\)\.slice\(0, 10\)/,
      /szimbolikus, önismereti digitális tartalom/i,
    ],
    required: [
      'import { huTodayKey } from "@/lib/dateKeys";',
      "`jovod-olvasat-${huTodayKey()}.txt`",
      "régi jelképrendszerekből készült önismereti olvasat",
    ],
  },
  {
    file: "src/data/chineseZodiac.hu.ts",
    forbidden: [
      /\bidegrendszer\b/i,
      /\bemésztés\b/i,
      /\bhormon/i,
      /\bpajzsmirigy\b/i,
      /\bízület/i,
      /\banyagcsere\b/i,
      /\bmáj\b/i,
      /\bmasszázs kötelező\b/i,
      /\bgyógyít/i,
      /\bVonzza a bőséget\b/i,
      /\bJó pénzügyi érzéke\b/i,
      /\bbefektetésre érzékenyen\b/i,
      /\bügyvédi\b/i,
      /\borvosi\b/i,
      /\bkatonai\b/i,
      /\bhalálos pontosan\b/i,
      /\bA sárkány a kínai állatöv legmágikusabb jegye\b/i,
      /\bAhol megjelenik, ott történik valami\b/i,
      /\bvagy a csúcson, vagy sehol\b/i,
      /\blátnoki energia és nagy tét\b/i,
      /\bUnalmas munka megöli\b/i,
      /\bÖnállóan és kis csapatban a legjobb\b/i,
      /\bnagy hierarchiában kifullad\b/i,
      /\bÖnállóan a legjobb\b/i,
      /\bfinom lelkű, művészi érzékű, mélyen empatikus jegy\b/i,
      /\bBelső világa gazdag\b/i,
      /\bott szüli a legjobb ötleteit\b/i,
      /\bkreatív problémamegoldás jegye\b/i,
      /\bGyors észjárású, humoros, kíváncsi\b/i,
      /\bMindenből játékot csinál\b/i,
      /\bmeglepően pontosan és fókuszáltan dolgozik\b/i,
      /\berkölcsi iránytűje\b/i,
      /\bmélyen empatikus\b/i,
      /\bbármit megtesz\b/i,
      /\bNem hisz könnyen, de ha igen, akkor mélyen\b/i,
      /\bKarizmatikus, eltökélt\b/i,
      /\bVezetésre született\b/i,
      /\bHeves és intenzív\b/i,
      /\bhegyet megmozgatni\b/i,
      /\bféltékenység és birtoklási vágy\b/i,
      /\bostoba szabályokat\b/i,
      /\bÍróasztal mögé zárva elsorvad\b/i,
      /\bRomantikus, érzékeny, mély érzelmű\b/i,
      /\bEgy biztonságos kapcsolat kivirágoztatja\b/i,
      /\bKemény versenyhelyzet kimeríti\b/i,
      /\bHűséges, gondoskodó partner\b/i,
      /\begy hazugság elég\b/i,
      /\bkifagy\b/i,
      /\bHosszú távra szövetkezik\b/i,
      /\btürelem mestere\b/i,
      /\ba teljesítménye beszél helyette\b/i,
      /\bmélyen lojális\b/i,
      /\bhűséges, megbízható oszlop\b/i,
      /\blegtöbbet teszi félre\b/i,
      /\bfolyamatos teherbírás\b/i,
      /\bA nyúl a kifinomultság és a béke jegye\b/i,
      /\bművészi lélek\b/i,
      /\bKonfliktusokat kerül\b/i,
      /\bRomantikus, gyengéd\b/i,
      /\bAkkor virágzik\b/i,
      /\bCsendes szakértőként a legerősebb\b/i,
    ],
    required: [
      "ritmus",
      "támogató munka",
      "nem minden feszültséget saját feladatként",
      "józan ellenőrzést",
      "Rendszerező, elemző, adminisztratív",
      "Nem rangot vagy különleges sorsot jelent",
      "figyelem, mérték és következetesség",
      "Nem kész karrierút",
      "felelősen kezelt lendület és a józan ritmus",
      "Nem kész pályaképet ad",
      "Nem azt állítja, hogy csak önállóan működhet jól",
      "az érzékeny figyelem, alkotó forma és békére törekvés jelképe",
      "Nem kész személyiségcímke",
      "a játékos találékonyság és gyors kapcsolás jelképe",
      "Nem állandó tréfálkozást vagy kiemelkedő észjárást ír elő",
      "a hűség, igazságérzet és védelmező figyelem jelképe",
      "Nem erkölcsi rangot vagy feltétlen önfeláldozást jelent",
      "a megújulás, bátorság és önálló lendület jelképe",
      "Nem vezetői sorsot vagy állandó harci kedvet ír elő",
      "Nem heves kapcsolatot vagy féltékenységet ígér",
      "Nem azt jelenti, hogy a nyugodtabb munka ne működhetne",
      "Nem ír elő különösen érzékeny természetet vagy ideális partnert",
      "Nem állítja, hogy versenyhelyzetben ne lehetne helytállni",
      "Nem hűséget vagy sérthetetlen bizalmat ígér",
      "a türelem, kitartás és csendes építkezés jelképe",
      "Nem kész személyiségítéletet ad",
      "Nem kész szerepet ír elő",
      "Nem ígér kiemelkedő takarékosságot",
      "a terhek ne maradjanak csendben, magányosan hordozott minták",
      "a béke, tapintat és kifinomult figyelem jelképe",
      "Nem kész érzékeny személyiséget ír le",
      "Nem romantikát vagy konfliktusmentességet ígér",
      "Nem csendes szakértői rangot jelöl",
    ],
  },
  {
    file: "src/routes/kinai-horoszkop.index.tsx",
    forbidden: [
      /\bminden jegye egy energiát képvisel\b/i,
      /\bjellemzőit\b/i,
      /\bkarrieres alkatát\b/i,
      /\bkompatibilis jegyeket\b/i,
    ],
    required: [
      "régi jelképi mintákat őriznek",
      "józan önismereti nézőpontként",
      "kapcsolati, munkabeli és kompatibilitási témákról",
    ],
  },
  {
    file: "src/data/numerologyTypes.hu.ts",
    forbidden: [
      /\bgyógyít/i,
      /\bgyógyító/i,
      /\bmestersz mára\b/i,
      /\bAnyagi hatalom\b/i,
      /\bpénzügyeidet\b/i,
      /\bházasság, gyerek, költözés\b/i,
      /\bMost jönnek az eredmények\b/i,
      /\bsorsod kódját hordozza\b/i,
      /\blelked alapvágya\b/i,
      /\bteszi teljessé az életed\b/i,
      /\bszenvedsz a legjobban\b/i,
      /\bmilyen képességek megnyilvánítására születtél\b/i,
      /\btehetségedet és az életcélodat\b/i,
      /\bA feladatod megtanulni\b/i,
      /\bFeladatod összekötni\b/i,
      /\bAlkotásra születtél\b/i,
      /\bDiplomata vagy\b/i,
      /\bmire vágyik legmélyebben a lelked\b/i,
      /\bvalójában boldoggá tesz\b/i,
      /\bahonnan a valódi öröm fakad\b/i,
      /\bsikeresnek látszol\b/i,
      /\bdöntéshozói szerepben látnak téged ösztönösen\b/i,
      /\bMagabiztosnak, kezdeményezőnek látszol\b/i,
      /\bvezetői benyomást keltesz\b/i,
      /\bA függés bármilyen formája lassan kiüríti\b/i,
      /\bnagyon megviseli a belső világodat\b/i,
      /\bcsendes szomorúság telepszik rád\b/i,
      /\bmélyen kibillentenek\b/i,
      /\banyagi szabadság hív/i,
      /\btisztelet és teljesítmény után vágyik\b/i,
      /\btehetetlenség érzése nagyon nehezen viselhető\b/i,
      /\bspirituális látás\b/i,
      /\bBelső igazságokat akarsz közvetíteni\b/i,
      /\bnagy víziók megvalósítása a földön\b/i,
      /\bLelked olyat akar építeni\b/i,
      /\bA lelked tanítóként\b/i,
      /\btanítóként vagy mélyen támogató jelenlétként akar jelen lenni\b/i,
    ],
    required: [
      "belső vágyirányokra és csendesebb motivációkra adhat nézőpontot",
      "belső igények egyik jelképes mutatójaként kezeli",
      "nem ad kész választ arra sem, mitől leszel boldog",
      "önálló irány és a saját kezdeményezés iránti belső igényt jelképezi",
      "kapcsolódás, béke és kölcsönösség iránti érzékenységet jelképezi",
      "önkifejezés, játékosság és öröm iránti belső igényt jelképezi",
      "biztonság, tisztaság és kiszámítható ritmus iránti igényt jelképezi",
      "önálló, kezdeményező külső benyomást jelképezhet",
      "nem vezetői rangot vagy kész szerepet jelent",
      "erős, határozott külső benyomást jelezhet",
      "nem státusz- vagy sikerígéret",
      "szeretet, gondoskodás és otthonosság iránti érzékenységet jelképezi",
      "önfeladással",
      "erő, felelősség és kézzelfogható hatás iránti belső igényt jelképezi",
      "Nem pénzügyi vagy státuszígéret",
      "kompetens jelenlét és a rendezett döntés",
      "a név hagyományos számmintáját olvassa",
      "nem kész életprogram",
      "Nem spirituális látást vagy különleges küldetést igazol",
      "érzékeny figyelem józan formába rendezése",
      "nagyobb elképzelések földelt, lépésenkénti építésének jelképe",
      "mélyen támogató jelenlétként",
      "Nem azt mondja, hogy tanítóként kell élned",
      "megtartó erőt",
      "mások támogatására",
      "Nem pénzügyi ígéret",
      "mesterszámra",
    ],
  },
  {
    file: "src/lib/numerology.ts",
    forbidden: [
      /\btényleg meg tud állni\b/i,
      /\bHalogatott beszélgetésekből lesznek a nagy szakítások\b/i,
      /\bA Lelkek Kutatója\b/i,
      /\bspirituális lelkület\b/i,
      /\bKüldetésed az igazság keresése\b/i,
      /\bKutatás, terápia, írás, tanácsadás\b/i,
      /\bahol mélyre kell látni\b/i,
      /\bA felszín mögé látni\b/i,
      /\bA Hatalom Kezelője\b/i,
      /\bAnyagi és szervezeti energiák gazdája\b/i,
      /\bA pénz, a hatalom és a felelősség tanít téged\b/i,
      /\bVezetés, vállalkozás, pénzügy, ingatlan\b/i,
      /\bahol nagyban gondolkodhatsz\b/i,
      /\bKépes vagy olyat építeni, ami túléli\b/i,
      /\bAlapító, intézményépítő, nagy projektek vezetője\b/i,
      /\bOlyat létrehozni, ami túléli a nevedet\b/i,
    ],
    required: [
      "kapcsolatmintát jelezhet",
      "tartósság a figyelmes hétköznapi jelenléten múlik",
      "halogatott beszélgetések idővel feszültséget gyűjthetnek",
      "Az Elmélyülő Kutató",
      "Nem spirituális küldetés",
      "hogyan értheted tisztábban a tapasztalataidat",
      "van idő kérdezni, rendszerezni, írni vagy összefüggéseket keresni",
      "belső figyelem és a hétköznapi valóság között",
      "Az Erő Rendezője",
      "Nem pénzügyi vagy hatalmi ígéret",
      "hogyan bánsz azzal, amit felépítesz",
      "felelősséget, rendszert és józan döntéseket",
      "Nem életművet ígér",
      "hogyan kaphat formát a vízió józan ritmusban",
      "rendszereket, kereteket és hosszabb távú terveket",
      "Formát adni annak, ami fontos",
    ],
  },
  {
    file: "src/data/magazin.hu.ts",
    forbidden: [
      /\bHa tényleg magadat akarod látni\b/i,
      /\bszórakozásnak jó\b/i,
      /\bkezd személyessé válni a kép\b/i,
      /\bönálló rezgést hordoznak\b/i,
      /\bmilyen tanulási pályára érkeztél\b/i,
      /\baz életutadat írja le\b/i,
      /\baz eredmény és anyagi rend\b/i,
      /\bmegmutatja az időjárást\b/i,
    ],
    required: [
      "saját adataidból induló önismereti nézőpontot",
      "személyesebb réteget kapni a kép",
      "könnyű napi rituálénak jó",
      "külön jelképi minőségként kezeli",
      "nem kész életleírás",
      "tanulási irányokra érdemes figyelned",
      "eredmény és felelős rendezés",
      "jelzi a jellemzőbb témákat",
    ],
  },
  {
    file: "src/data/numerologyTypes.hu.ts",
    forbidden: [
      /\bmilyen energia kíséri ezt az évedet\b/i,
      /\bmás feladatot és más lehetőséget hoz\b/i,
      /\bmegérted, miért történik veled most pont az, ami történik\b/i,
      /\bkövetkező 9 évet meghatározza\b/i,
      /\bDiplomácia éve\b/i,
      /\bCsend, tanulás, spiritualitás\b/i,
    ],
    required: [
      "milyen témák kerülhetnek könnyebben előtérbe",
      "visszatérő minták kérnek most több figyelmet",
      "fontos viszonyítási ponttá válhat",
      "türelmes egyeztetés adhatnak jobb irányt",
      "Csend, tanulás, befelé figyelés",
    ],
  },
  {
    file: "src/routes/numerologia.index.tsx",
    forbidden: [
      /\bteljes képet rólad\b/i,
      /\bA teljes számmisztika kép\b/i,
      /\bsorsfeladatod\b/i,
      /\bmegmutatja, miért most jönnek azok a témák\b/i,
    ],
    required: [
      "hagyományos értelmezésekkel",
      "régi jelképrendszere",
      "önismereti nézőpontot",
      "más réteget világíthat meg az élethelyzetedből",
      "A számmisztikai kép fő rétegei",
      "visszatérő témáidra adhat nézőpontot",
      "nézőpontot adhat arra",
      "elő bizonyos visszatérő témák",
    ],
  },
  {
    file: "src/routes/szammisztika.tsx",
    forbidden: [
      /\bMit mond rólad a születési dátumod\b/i,
      /\bAPI\b/i,
      /\blefordít/i,
    ],
    required: [
      "számmisztika régi jelképrendszere",
      "születési dátum mintáiból indul",
      "önismereti nézőpont",
    ],
  },
  {
    file: "src/routes/horoszkop.tsx",
    forbidden: [
      /\bFriss csillagjegy-rovat magyarul\b/i,
      /\bFriss, szerkesztett horoszkóp-rovat\b/i,
      /\bAPI\b/i,
      /\blefordít/i,
    ],
    required: [
      "asztrológiai hagyomány jelképeiből",
      "asztrológiai hagyomány régi jelképrendszeréből",
      "jegyed hagyományos motívumait",
    ],
  },
  {
    file: "src/data/lifePathMeanings.hu.ts",
    forbidden: [
      /\bgyógyít/i,
      /\bgyógyító/i,
      /\bterapeuta\w*/i,
      /\bápoló\b/i,
      /\bpénzügyi tanácsad/i,
      /\bpénzügyi szakértelem\b/i,
      /\bsiker megtestesítője\b/i,
      /\belőre megérezni dolgokat\b/i,
      /\bfelsőbb síkok\b/i,
      /\bideális diplomaták\b/i,
      /\bgrandiózus elképzelések valósággá formálás/i,
      /\bgrandiózus vízióidat\b/i,
      /\brendkívüli női energi/i,
      /\blegerősebb intuitív képességekkel rendelkezik\b/i,
      /\bmindig a béke és az egyensúly megteremtésére törekszik\b/i,
      /\bHatalmas befolyással bír\b/i,
      /\beredmények tagadhatatlanok\b/i,
      /\bmég mielőtt azok kifejeződnének\b/i,
      /\bKiválóan alkalmasak arra\b/i,
      /\brendkívül érzékeny energiákról van szó\b/i,
      /\ba legkisebb sértés is kibillenti\b/i,
      /\bkivételes intuíció és rendkívüli érzékenység\b/i,
      /\bmások előtt rejtve maradnak\b/i,
      /\bszellemi síkok\b/i,
      /\bmások gondolatait és érzéseit olvasnák\b/i,
      /\bfinom energiákat\b/i,
      /\brendkívül önállóak\b/i,
      /\bnem várnak a lehetőségekre\b/i,
      /\bmegteremtik azokat\b/i,
      /\brendkívül gyakorlatiasak\b/i,
      /\bnem tévesztik meg őket az illúziók\b/i,
      /\brendkívül nyitottá teszi\b/i,
      /\blegkülönfélébb helyzetekben is megtalálja a helyét\b/i,
      /\blegjobb tapasztalatokat\b/i,
      /\bAz úttörő vezető\b/i,
      /\bvezetői képességek\b/i,
      /\bvezetői hajlamaikat\b/i,
      /\bvezetői potenciált\b/i,
      /\bmagabiztosságot testesíti meg\b/i,
      /\balakítsuk a körülményeinket\b/i,
      /\bteremtés és a kezdetek energiáját hordozza\b/i,
      /\btúl dominánssá válni\b/i,
      /\bfigyelmetlenséggel párosulva sértést okozhat\b/i,
      /\bkorlátozott látásmód\b/i,
      /\bBelső bizonytalanságuk\b/i,
      /\bmélyen élhet bennük\b/i,
      /\bVezetői, önálló és úttörő szerepekben\b/i,
      /\bVállalkozóként, ügyvezetőként, feltalálóként vagy előadóként\b/i,
      /\bstabilitás, a rendszerezettség és a megbízhatóság energiáját hordozza\b/i,
      /\bAzoknak szól, akik\b/i,
      /\btartós értékeket képviselik az életben\b/i,
      /\bsorsszám rezgése\b/i,
      /\b4-es energiát hordozó személyek\b/i,
      /\bmérhető eredményeket szeretnének látni\b/i,
      /\bdogmatikussá válhatnak\b/i,
      /\bmereven ragaszkodnak\b/i,
      /\bunalmas.*fantáziátlan/i,
      /\bRugalmatlanságuk miatt\b/i,
      /\bHűségesek, megbízhatóak és odaadóak\b/i,
      /\bhosszú távú elköteleződésre törekednek\b/i,
      /\bSzívközpontú lényként fontos dolgod van\b/i,
      /\bKépessé tesz mások támogatására\b/i,
      /\bRendkívül támogató vagy\b/i,
      /\bPartnereid iránt hűséges, gondoskodó és rendkívül romantikus vagy\b/i,
      /\bmeleg és szeretetteljes otthont teremtve\b/i,
      /\brendíthetetlen hűség\b/i,
      /\bKiválóan teljesíthetsz olyan területeken\b/i,
      /\bVonzódhatsz a tanácsadói, segítői, oktatói vagy közösségi szerepekhez\b/i,
      /\bélmények iránti vágy megtestesítője\b/i,
      /\bÉletében a felfedezés és az új tapasztalatok gyűjtése áll a középpontban\b/i,
      /\bbeteljesedést az izgalmas élmények sokaságában találja meg\b/i,
      /\bhagyja, hogy a 'szél sodorja'\b/i,
      /\bmély és szenvedélyes kapcsolatot alakíthat ki\b/i,
      /\bmegbízhatatlanná teheti\b/i,
      /\bteljesebb és kiegyensúlyozottabb életet élhessen\b/i,
      /\bA leginkább olyan munkakörökben teljesedik ki\b/i,
      /\bKiválóan alkalmas az önálló vállalkozásra\b/i,
      /\butazással kapcsolatos foglalkozásokra\b/i,
      /\bstartup környezetekben\b/i,
      /\bAz életöröm és kreativitás útja\b/i,
      /\boptimista életszemlélet erejét hordozza\b/i,
      /\bEgy örökifjú lélek\b/i,
      /\bteljesedik ki\b/i,
      /\bfiatalos, pozitív és tele van életerővel\b/i,
      /\bAz életet egy táncnak tekinti\b/i,
      /\bFő mozgatórugója a vidámság\b/i,
      /\bművészeti kifejezések mestere\b/i,
      /\bKiemelkedő kommunikációs képességekkel rendelkezik\b/i,
      /\bTermészetes bájjal és karizmával\b/i,
      /\bnaivitás jellemezheti\b/i,
      /\bfelületes, ám kellemes interakciókat preferálja\b/i,
      /\bjátékos, kifejező és spontán\b/i,
      /\bkönnyed és vidám légkör fenntartása\b/i,
      /\börök optimizmusa igazi ajándék\b/i,
      /\bKreatív területeken bontakozik ki leginkább\b/i,
      /\bÍróként, előadóművészként, zenészként vagy marketingesként\b/i,
      /\bsikeres lehet\b/i,
      /\boktatóként vagy rendezvényszervezőként is kiteljesedhet\b/i,
      /\bmerev vállalati környezet kiégetné\b/i,
      /\bmélységek, a bölcsesség és az elmélyült gondolkodás felé tereli egyéniségét\b/i,
      /\brejtett igazságok és a létezés mélyebb értelmének felfedezéséről\b/i,
      /\bLényét a folytonos kutatás\b/i,
      /\berős intuitív képességei vezetik a tudás felé\b/i,
      /\bKiemelkedő spirituális érzékenység jellemzi\b/i,
      /\bláthatatlan világ törvényszerűségei\b/i,
      /\belszigeteltséget okozhat\b/i,
      /\bgyanakvóvá válhat\b/i,
      /\brendkívül hűséges és elkötelezett társsá válik\b/i,
      /\bvalódi, mély intellektuális és spirituális kapcsolódásra vágyik\b/i,
      /\bkülönleges mesterszám\b/i,
      /\bmély intuíciót és spirituális érzékenységet hordoz\b/i,
      /\bbelső tudás, finom érzékelés\b/i,
      /\bbelső figyelem mesterszáma\b/i,
      /\bvalaki erősebben reagál\b/i,
      /\bRendkívül intuitív lehetsz\b/i,
      /\bFokozott érzékenységed\b/i,
      /\bszorongáshoz, önbizalomhiányhoz vagy elzárkózáshoz vezethet\b/i,
      /\bdöntésképtelenséget okozhat\b/i,
      /\bmély érzelmi és spirituális kapcsolódásra vágysz\b/i,
      /\begyedi érzékenységedet\b/i,
      /\blegfőbb iránytűd\b/i,
      /\bKiválóan teljesít olyan területeken\b/i,
      /\bpszichológus vagy adatelemző munkakörben\b/i,
      /\btalálhatja meg a hivatását\b/i,
      /\bintellektuálisan kihívást jelentő\b/i,
      /\bKiválóan teljesítesz olyan területeken\b/i,
      /\bspirituális tanácsadóként\b/i,
      /\bLátnoki természeted\b/i,
      /\blélekszintű értelmet ad\b/i,
      /\bprofitközpontú környezet ürességet okozhat\b/i,
      /\bspirituális forrásból merítve ad válaszokat\b/i,
      /\blegnagyobb jót keresi\b/i,
      /\bfelébreszteni saját magasabb énjükre\b/i,
      /\bAz Önzetlen Segítő\b/i,
      /\bspirituális út egy fontos állomását jelöli\b/i,
      /\bbölcsességedet mások megsegítésére fordíthatod\b/i,
      /\bmások terhét neked kellene elvinned\b/i,
      /\btudod, mi kell ahhoz\b/i,
      /\bRemek építész, mérnök\b/i,
      /\bVezetői szerepekben is kiemelkedő vagy\b/i,
      /\bAz Építőmester útja\b/i,
      /\bMester Építő\b/i,
      /\bnagy potenciált jelöl\b/i,
      /\ba vízió nem marad álom\b/i,
      /\bnagyobb teherbírás\b/i,
      /\bnagyobb tudatossági feladat\b/i,
      /\bErős képességed lehet\b/i,
      /\bminden akadályt legyőz\b/i,
      /\btúlzott maximalizmusod megbénít\b/i,
      /\bkiégéshez vezethet\b/i,
      /\bkimerülve a túlhajszoltságban\b/i,
      /\bmindent jobban elvégzel magad\b/i,
      /\bintenzív, céltudatos és ambiciózus mintát\b/i,
      /\bmonumentális léptékű\b/i,
      /\bgyakran válnak kiemelkedő vezetőkké és sikeremberekké\b/i,
      /\bszinte élnek azért, hogy elérjék céljaikat\b/i,
      /\belvezeti a jóléthez\b/i,
      /\bA 4-es sorsszámúak kiválóak azokban a szakmákban\b/i,
      /\bJól érzik magukat mérnökként\b/i,
      /\bkiemelkedővé teszi őket\b/i,
      /\bKiváló spirituális vezető\b/i,
      /\ba lélek mélységeit szólítja meg\b/i,
      /\bfeltétel nélküli szeretet\b/i,
      /\bönzetlen szolgálat\b/i,
      /\bspirituális küldetés\b/i,
      /\bspirituális érlelődésre hív\b/i,
      /\begyetemes szeretet\b/i,
      /\bkomplex spirituális igazságokat\b/i,
      /\bláthatóvá téve a láthatatlant\b/i,
      /\bspirituálisan érzékeny\b/i,
      /\bszenvedélyét a fejlődés és a szolgálat iránt\b/i,
      /\blegnagyobb tanítás\b/i,
    ],
    required: [
      "Nem kész személyiségcímke",
      "Az önálló kezdeményező",
      "Nem vezetői rangot vagy kész szerepet ír le",
      "kezdeményezés és a felelős önállóság",
      "a kezdeményezés, újrakezdés és önálló iránykeresés témáit emeli előtérbe",
      "Nem azt állítja, hogy mindent egyedül kell alakítanod",
      "Nem dominanciát vagy rejtett bizonytalanságot ír elő",
      "visszajelzéshez és önreflexióhoz",
      "önálló kezdeményezést, a saját irány keresését",
      "Nem kész karriertanács",
      "önálló feladatvállalás, az új ötletek elindítása és a döntési tér",
      "saját irány keresését",
      "stabil alapokat keres",
      "ne szétszórjon, hanem tágítsa a látókört",
      "változás, szabadság és tapasztalati tanulás jelképeként olvassa",
      "Nem kész életstílust ír elő",
      "Nem szenvedélyt vagy tartós kötődést ígér",
      "Nem kész karrierutat jelöl",
      "változatosság, tanulás, kommunikáció és mozgástér",
      "a változás ne menekülés, hanem tudatos mozgás legyen",
      "felelősen kezelt mozgástérként jelenhet meg",
      "gondoskodás, felelősség és kapcsolati harmónia jelképeként olvassa",
      "Nem kész szerepet ír elő",
      "gondoskodás akkor marad tiszta, ha önmagad felé is működik",
      "a gondoskodás nem önfeladás",
      "Nem hűséget vagy romantikát ígér",
      "Nem kész pályaképet ad",
      "ahol a felelősség, a rendezettség, a szépség vagy a kapcsolati figyelem kap szerepet",
      "A kreatív önkifejezés",
      "az önkifejezés, a kommunikáció és a kreatív mozgástér jelképeként olvassa",
      "Nem örök derűt vagy kész személyiségcímkét ír le",
      "az alkotás, beszéd, játékosság és kapcsolódás témáit emeli előtérbe",
      "Nem kiemelkedő képességet vagy természetes karizmát ígér",
      "Nem könnyed vagy konfliktusmentes kapcsolatot ígér",
      "Nem kész szakmai útmutató",
      "önkifejezés, a kommunikáció és a kreatív mozgástér",
      "ötleteket lehet formába rendezni",
      "változatosság mellett marad elég fókusz és józan ritmus",
      "a stabilitás, rendszerezettség és tartós építkezés jelképeként olvassa",
      "megbízható ritmus, a határok és az alapok gondos felépítése",
      "a földelés, kitartó munka és gyakorlati rend témáit emeli előtérbe",
      "Nem azt állítja, hogy valaki csak mérhető eredményekben gondolkodik",
      "Nem rugalmatlanságot ír elő",
      "Nem hűséget vagy hosszú távú elköteleződést ígér",
      "stabil alapok, rendszerek és tartós építés témái",
      "megbízható ritmussá válik",
      "Nem kész pályaválasztási tanács",
      "csendes elmélyülés, a kérdezés és a belső figyelem jelképeként olvassa",
      "Nem rejtett igazságot vagy különleges tudást ígér",
      "kutatás, elemzés és befelé figyelés témáit emeli előtérbe",
      "nem felsőbb tudás",
      "túlzott elvonulást, túlelemzést vagy bizalmatlanabb belső ritmust jelezhet",
      "ne elszigetelődésbe forduljon",
      "Nem hűséget vagy különleges spirituális kapcsolódást ígér",
      "kutatás, elemzés és csendes elmélyülés",
      "ez nem igazol konkrét hivatást",
      "Nem különleges képességet vagy gondolatolvasást jelent",
      "az ihlet, érzékeny figyelem és földelt jelenlét jelképeként olvassa",
      "Nem különleges képességet vagy spirituális rangot ír le",
      "az intuíció, érzékenység és belső figyelem témáit emeli előtérbe",
      "a finom benyomásokat érdemes józan keretben vizsgálni",
      "intuíció nem bizonyosságként jelenik meg",
      "Nem spirituális kapcsolódást vagy különleges összeillést ígér",
      "nem azonnali igazságként, hanem finom jelzésként kezelni",
      "ihletet földelt, józan formába rendezni",
      "egészséges határokkal",
      "A tágabb rálátás",
      "a lezárás, elengedés és tágabb emberi rálátás jelképeként olvassa",
      "Nem spirituális állomást vagy segítő szerepet ír elő",
      "az együttérzés csak világos határokkal marad tartós és tiszta",
      "Nem kész spirituális válaszokat ad",
      "lezárás, elengedés és tágabb rálátás",
      "Nem felsőbb tudást vagy megmentő szerepet jelent",
      "tiszteletteljes jelenlétet lehet formálni",
      "Nem spirituális hivatást vagy különleges rangot jelöl",
      "értelmes, figyelmes és emberi léptékű munka",
      "világos határokkal és földelt felelősséggel",
      "Nem kész szakmai címke",
      "A felelős építés",
      "a nagyobb tervek, gyakorlati forma és felelős építkezés jelképeként olvassa",
      "Nem rangot vagy különleges sorsot ír le",
      "Nem nagyobb teherbírást vagy különleges feladatot bizonyít",
      "Nem azt jelenti, hogy mindent egyedül kell kézben tartani",
      "Nem ambiciózus vagy intenzív kapcsolatot ír elő",
      "a nagyobb tervek is csak emberi léptékben tarthatók meg",
      "rendszerek, struktúrák és hosszabb távú tervek építése",
      "Ez nem vezetői rangot ígér",
      "közösségi figyelem és emberi felelősség témáit emeli előtérbe",
      "józan jelenlétből indul",
      "Nem sikert vagy rangot ígér",
      "céltudatos építkezés, a stratégiai gondolkodás és a felelősségvállalás",
      "nem garantált jólétet jelent",
      "Nem spirituális rangot vagy hivatást igazol",
      "gondoskodó jelenlét és az értelmes forma",
      "egészséges határokkal és józan felelősséggel",
      "tartós rend és felelősség eszközeként",
      "gondoskodó figyelem és felelősen adott támogatás jelképeként olvassa",
      "Nem önzetlen szolgálatot vagy spirituális küldetést ír elő",
      "Nem egyetemes szeretetet vagy különleges rangot igazol",
      "a gondoskodás nem megmentő szerep",
      "Nem mély elköteleződést vagy spirituális összeillést ígér",
      "ne váljon csendes önfeladássá",
      "Nem rangot vagy különleges sorsot ír le",
    ],
  },
  {
    file: "src/data/cards.ts",
    forbidden: [
      /\bbiztosan\b/i,
      /\bgyógyít/i,
      /\bgyógyítható\b/i,
      /\bbefektetés\b/i,
      /\bvalósággá válik\b/i,
      /\blegnagyobb erőd\b/i,
      /\blegjobb iránytű\b/i,
      /\bte értesz a legjobban\b/i,
    ],
    required: [
      "bukkanhat fel",
      "finoman feldolgozható",
      "stabil támasz lehet",
      "megtartó erőforrás lehet",
      "tisztább irányt adhat",
      "természetesebbnek érzed a saját hangodat",
    ],
  },
  {
    file: "src/lib/angel.hu.ts",
    forbidden: [
      /\bkészülj\b/i,
      /\bvisszatérülés közeledik\b/i,
      /\bami jár, az megérkezik\b/i,
      /\begészen új kezdődik\b/i,
      /\bjó úton vagy\b/i,
      /\bpontosan ott vagy\b/i,
      /\blenned kell\b/i,
      /\bteremtő erejű\b/i,
      /\bmanifesztáció\b/i,
      /\bnem vagy egyedül\b/i,
      /\bbiztos alapokra épül\b/i,
      /\bfolytasd, amit elkezdtél\b/i,
      /\bgyors megvalósulás\b/i,
      /\bformálódik valósággá\b/i,
      /\bpontosan jó sorrendben\b/i,
      /\bspirituális mélyülés\b/i,
      /\bszerencsés egybeeséseket erősíti\b/i,
      /\bkülönleges spirituális állapotot ígér\b/i,
      /\bisteni teljességet\b/i,
      /\bnagy újrakezdés előtt\b/i,
      /\benergiáját erősíti fel\b/i,
      /\ba hangodra most szükség van\b/i,
      /\bmásoknak is utat mutat\b/i,
      /\benergiáját sokszorozza\b/i,
      /\bfelemelkedett mesterek jelenlétéhez\b/i,
      /\benergiáját hordozza\b/i,
      /\bköltözés vagy új életszakasz\b/i,
      /\baz tartós lesz\b/i,
      /\bnagy ívű, közösen épített tervek energiáját hordozza\b/i,
      /\ba bőség és az áramlás száma\b/i,
      /\bbefektetett figyelmed és munkád eredménye\b/i,
    ],
    required: [
      "arra hívhatja fel a figyelmed",
      "Nem anyagi ígéretként, inkább önismereti jelként",
      "önismereti jelként arra terelheti a figyelmed",
      "tisztábban szólhat hozzád",
      "a belső elmélyülés és a csendesebb iránykeresés jele lehet",
      "Nem különleges spirituális állapotot jelez",
      "a csend most tisztább figyelmet adhat",
      "a nyitott lehetőséget és a körszerű lezárás-újrakezdés mintáját jelképezi",
      "Nem nagy fordulatot ígér",
      "az új kezdet és a szándék rendezésének témáját emeli ki",
      "Nem azt jelzi, hogy másoknak utat kell mutatnod",
      "tanítói jelképrendszerekhez kötik",
      "nem külső üzenetként, hanem önismereti figyelmeztető jelként",
      "Nem költözést vagy új életszakaszt jósol",
      "Nem tartós eredményt ígér",
      "az eredmény, méltányosság és kiegyenlítődés témáihoz kapcsolódik",
    ],
  },
  {
    file: "src/data/ichingHexagrams.hu.ts",
    forbidden: [
      /\bValami jó közeledik\b/i,
      /\bValami jó dolog visszatér\b/i,
      /\bhatni fog rád\b/i,
      /\bA megérzéseid most pontosak\b/i,
      /\bEngedd magadhoz, akit a szíved hív\b/i,
      /\bBocsáss meg\b/i,
      /\bmegérkezik\b/i,
      /\bki kell mondani vagy meg kell tenni\b/i,
      /\bcélja a gyógyulás\b/i,
      /\bTiszta, kezdeményező energia\b/i,
      /\bEgy energia kitör\b/i,
      /\begyütt rezegnek veled\b/i,
      /\bNagy energia gyűlt össze\b/i,
      /\bKét energia egymásra hat\b/i,
      /\bSok energiád van\b/i,
      /\bCsatornázd az erőt\b/i,
      /\bnagy ívre van energia\b/i,
    ],
    required: [
      "Egy kedvezőbb mozgás közeledhet",
      "A megbékélés akkor értékes, ha belülről érik",
      "Valamit talán tisztábban kell kimondani vagy vállalni",
      "Az átharapás célja a tisztázás",
      "nem a múlt ismétlése",
      "vesd össze a helyzet tényeivel is",
      "kezdeményező erőt jelöl",
      "közös ritmust és felelős szándékot",
      "Nagy erő gyűlt össze",
      "Két minőség egymásra válaszol",
      "Erős lendület állhat rendelkezésedre",
      "Fordítsd az erőt értékes célba",
    ],
  },
  {
    file: "src/routes/jiking.index.tsx",
    forbidden: [
      /\bélet újra meg újra besorolja az embert\b/i,
      /\bránt magához tekinteted\b/i,
      /\ba válaszhoz közel áll\b/i,
      /\bŐsi kínai bölcsesség mai döntésekhez\b/i,
    ],
    required: [
      "Régi kínai jelképrendszer mai önreflexióhoz",
      "régi kínai jelképrendszer 64 hexagrammal",
      "józan önismereti nézőpontként",
      "segít tisztábban ránézni a helyzetre",
      "figyelmeztető szempontját",
    ],
  },
  {
    file: "src/lib/crystal.hu.ts",
    forbidden: [
      /\bgyógyít/i,
      /\bgyógyító/i,
      /\bFinomítja\b/i,
      /\bMegerősíti\b/i,
      /\bfókuszt ad\b/i,
      /\bönbizalmat hoz\b/i,
      /\bjelenlétet hoz\b/i,
      /\bminőséget hoz\b/i,
      /\bho(t|z) elő\b/i,
      /\berősíti\b/i,
    ],
    required: [
      "milyen minőséget jelképez",
      "Önismereti jelként",
      "Hagyományosan",
      "jelképezi",
      "társítják",
    ],
  },
  {
    file: "src/routes/kristaly.tsx",
    forbidden: [/\bminőséget hoz elő\b/i, /\bgyógyít/i, /\bgyógyító/i],
    required: [
      "milyen minőséget hordoz",
      'Section eyebrow="Milyen minőséget hordoz?"',
      "A kristályok hagyományosan szimbólumok",
      "önismereti jelként használjuk",
    ],
  },
  {
    file: "src/components/ReadingLoadingState.tsx",
    forbidden: [
      /\bLekérdezzük\b/i,
      /\bAPI\b/i,
      /\bháttéradat\b/i,
      /\bszolgáltató\b/i,
      /\blefordít/i,
    ],
    required: [
      "Figyelembe vesszük a Nap, a Hold és a bolygók aktuális állását",
      "Az asztrológiai képlet időminőségéből",
      "a Major és Minor Arcana hagyományával",
      "hagyományos álomfejtésben",
      "hagyományos jelentésével",
    ],
  },
  {
    file: "src/lib/dream.hu.ts",
    forbidden: [/\bSzinte sosem szó szerinti\b/i, /\bA vég is kapu\b/i],
    required: [
      "Nem jóslat és nem szó szerinti előrejelzés",
      "lezárást, átmenetet",
      "Nem végzet, hanem átmenet képe",
    ],
  },
  {
    file: "src/routes/alomfejtes.tsx",
    forbidden: [
      /Az álom nem előrejelzés\. Egy belső kép, amit érdemes meghallgatni, de nem szó\s+ szerint venni\./i,
    ],
    required: [
      "function dreamSafetyNote",
      "result.title",
      "halálesetet jósol",
      "Az álom nem szó szerinti jövőjel",
      "hagyományos álomfejtés",
      "milyen érzés, lezárás vagy vágy kér most figyelmet",
      "gyászhoz, krízishez vagy tartós szorongáshoz",
      "kérj emberi vagy szakmai támogatást",
    ],
  },
  {
    file: "src/routes/alomfejtes-jelentes.tsx",
    forbidden: [/\ba halál pedig sokszor\b/i],
    required: [
      "halálképek pedig nem jóslatként",
      "Mit jelent, ha halállal álmodom?",
      "Nem kezeljük előrejelzésként",
      "tartós szorongáshoz kapcsolódik",
    ],
  },
  {
    file: "src/routes/arak.tsx",
    forbidden: [
      /Nem\. A Jövőd\.hu szimbolikus/i,
      /szimbolikus, önismereti digitális tartalmat ad/i,
      /Azonnali digitális olvasat/i,
      /Részletes digitális olvasat/i,
      /\bRoxy\b/i,
      /\bAPI\b/i,
      /\bprovider\b/i,
      /\blefordít/i,
      /\bfordítjuk\b/i,
      /\bgyorsan kiderül\b/i,
      /\blegjobb választás\b/i,
    ],
    required: [
      "Azonnali önismereti olvasat",
      "Részletes önismereti olvasat",
      "első benyomást ad arról",
      "jobb illeszkedés lehet",
      "nagy hagyományú, történeti jelképrendszerekből",
      "népi megfigyelésekből indul",
      "önismereti olvasatként kezeljük",
      "tisztábban ránézni egy helyzetre",
      "nem helyettesítenek orvosi, jogi, pénzügyi vagy krízishelyzeti segítséget",
    ],
  },
  {
    file: "src/routes/vedikus-asztrologia.tsx",
    forbidden: [/\bteljes elemzés\b/i, /\bTeljes életkép\b/i],
    required: [
      "részletes elemzés a születési képletedből",
      "Védikus asztrológia – részletes elemzés",
      "Átfogó képlet-nézőpont",
      "visszatérő minta",
      "nem büntetés",
    ],
  },
  {
    file: "src/lib/products.ts",
    forbidden: [/Védikus asztrológia — teljes elemzés/i],
    required: ["Védikus asztrológia — részletes elemzés"],
  },
  {
    file: "src/lib/products/vedicFull.server.ts",
    forbidden: [/Védikus asztrológia – teljes elemzés/i],
    required: ["Védikus asztrológia – részletes elemzésed"],
  },
  {
    file: "src/components/SmartReadingFollowup.tsx",
    forbidden: [
      /A teljes elemzés a születési dátum/i,
      /Mi történik köztetek valójában/i,
      /napi lap valójában kapcsolati kérdést/i,
    ],
    required: [
      "A részletes elemzés a születési dátum",
      "Milyen mintát mutat köztetek?",
      "tempót, kölcsönösséget, kommunikációt",
      "tempót, kölcsönösséget és visszatérő mintát",
    ],
  },
  {
    file: "src/lib/legal.ts",
    forbidden: [/technikai szolgáltatóként készít/i, /\bAPI\b/i, /lefordít/i, /fordítjuk/i],
    required: [
      "SYMBOLIC_TRADITION_DISCLAIMER",
      "nagy hagyományú, történeti jelképrendszerekből és népi megfigyelésekből indul",
      "józan, mai önismereti nyelven olvassa",
    ],
  },
  {
    file: "src/components/Layout.tsx",
    forbidden: [/technikai szolgáltatóként készít/i, /\bAPI\b/i, /lefordít/i, /fordítjuk/i],
    required: ["SYMBOLIC_TRADITION_DISCLAIMER"],
  },
  {
    file: "src/routes/aszf.tsx",
    forbidden: [/technikai szolgáltatóként készít/i, /\bAPI\b/i, /lefordít/i, /fordítjuk/i],
    required: ["SYMBOLIC_TRADITION_DISCLAIMER"],
  },
  {
    file: "src/routes/impresszum.tsx",
    forbidden: [/technikai szolgáltatóként készít/i, /\bAPI\b/i, /lefordít/i, /fordítjuk/i],
    required: ["SYMBOLIC_TRADITION_DISCLAIMER"],
  },
  {
    file: "src/routes/elallasi-tajekoztato.tsx",
    forbidden: [
      /technikai szolgáltatóként készít/i,
      /\bAPI\b/i,
      /lefordít/i,
      /fordítjuk/i,
      /szimbolikus, önismereti és szórakoztató tartalmak/i,
    ],
    required: [
      "SYMBOLIC_TRADITION_DISCLAIMER",
      "önmagában nem minősül",
      "hozzáférési hibának",
    ],
  },
  {
    file: "src/lib/roxy.functions.ts",
    forbidden: [
      /roxyAngolForras/,
      /Roxy angol forrás/i,
      /FORDÍTANDÓ FORRÁST/i,
      /raw provider-szöveget/i,
      /endpoint- vagy mezőneveket/i,
    ],
    required: [
      "forrasAdatok",
      "forrasJelentes",
      "forrasJelentesSzabaly",
      "gépházi szöveget",
      "hűséges magyar szerkesztő",
    ],
  },
  {
    file: "src/lib/roxyTranslate.functions.ts",
    forbidden: [
      /Roxy API/i,
      /nyers angol Roxy/i,
      /nyers angol válasz/i,
      /SZIGORÚAN FORDÍTÓ/i,
      /fordítjuk magyarra/i,
      /magyarítás/i,
      /raw provider-szöveget/i,
      /endpoint- vagy mezőneveket/i,
      /fordítója vagy/i,
    ],
    required: [
      "magyar szimbolikus olvasatainak szerkesztője",
      "jelképi forrásanyag",
      "forrásmezők jelentését",
      "magyar olvasat",
    ],
  },
  {
    file: "src/lib/horoscopeNews.server.ts",
    forbidden: [
      /RoxyAPI horoszkóp-forrás/i,
      /Angolról magyarra fordítasz/i,
      /Fordítandó szöveg/i,
      /endpointnevet/i,
      /AI-meta mondatot/i,
      /háttéradat most nem érhető el/i,
    ],
    required: [
      "horoszkóp-rovatának szerkesztője",
      "forrásszöveg jelentését",
      "Forrásanyag",
      "technikai mezőnevet vagy gépházi magyarázatot",
    ],
  },
  {
    file: "src/lib/products/personal30day.server.ts",
    forbidden: [
      /Roxy-forrás/i,
      /Roxy \+ AI flow/i,
      /ROXY NATAL/i,
      /ROXY FORECAST/i,
      /nyers JSON, angol/i,
    ],
    required: [
      "forráshű szerkesztői flow",
      "asztrológiai forrásanyagból",
      "SZÜLETÉSI KÉPLET FORRÁSANYAGA",
      "ASZTROLÓGIAI IDŐVONAL 30 NAPRA",
    ],
  },
  {
    file: "src/lib/products/personalYearly.server.ts",
    forbidden: [
      /Roxy-forrás/i,
      /Roxy \+ AI flow/i,
      /ROXY NATAL/i,
      /ROXY ÉVES/i,
      /Roxy forecast\/timeline/i,
      /nyers JSON, angol/i,
    ],
    required: [
      "forráshű szerkesztői flow",
      "asztrológiai forrásanyagot",
      "asztrológiai forrásanyagból",
      "SZÜLETÉSI KÉPLET FORRÁSANYAGA",
      "ÉVES ASZTROLÓGIAI FORRÁSANYAG",
    ],
  },
  {
    file: "src/lib/products/transitsPersonal.server.ts",
    forbidden: [
      /Roxy-forrás/i,
      /Roxy \+ AI flow/i,
      /ROXY NATAL/i,
      /ROXY TRANZIT/i,
      /Roxy endpointra/i,
      /tranzit-specifikus végpont/i,
      /nyers JSON, angol/i,
    ],
    required: [
      "forráshű szerkesztői flow",
      "tranzit-forrásanyaggal",
      "idővonali asztrológiai forrásanyag",
      "asztrológiai forrásanyagból",
      "SZÜLETÉSI KÉPLET FORRÁSANYAGA",
      "TRANZITFORRÁS 90 NAPRA",
    ],
  },
  {
    file: "src/lib/products/vedicFull.server.ts",
    forbidden: [/ROXY NATAL/i, /nyers JSON, angol/i],
    required: ["VÉDIKUS (SZIDERIKUS) ÉRTÉKEK", "TROPIKUS SZÜLETÉSI KÉPLET FORRÁSANYAGA"],
  },
  {
    file: "src/lib/analytics.ts",
    forbidden: [/roxy_call_/, /roxy_cache_/, /roxy_fallback_/, /roxy_domain_/, /endpoint:/],
    required: [
      "knowledge_lookup_started",
      "knowledge_lookup_succeeded",
      "knowledge_lookup_failed",
      "knowledge_cache_hit",
      "knowledge_cache_miss",
      "local_meaning_used",
    ],
  },
  {
    file: "src/components/RitualTable.tsx",
    forbidden: [/roxy_call_/, /roxy_cache_/, /roxy_fallback_/, /endpoint:/, /code: r\.providerCode/],
    required: [
      "knowledge_lookup_started",
      "knowledge_lookup_failed",
      'trackEvent("knowledge_lookup_failed", { area: "numerology/chart" })',
      'trackEvent("knowledge_lookup_failed", { area: "numerology/compatibility" })',
      "knowledge_cache_hit",
      "local_meaning_used",
    ],
  },
  {
    file: "src/routes/mai-iranytu.tsx",
    forbidden: [/roxy_call_/, /roxy_cache_/, /roxy_fallback_/, /endpoint:/],
    required: ["knowledge_cache_hit", "knowledge_cache_miss", "local_meaning_used"],
  },
];

const failures: string[] = [];

const publicUiFiles = [
  "src/components/ui/dialog.tsx",
  "src/components/ui/sheet.tsx",
  "src/components/ui/pagination.tsx",
  "src/components/ui/carousel.tsx",
  "src/components/ui/sidebar.tsx",
  "src/components/ui/breadcrumb.tsx",
];

function walkPublicUiSources(dir: string): string[] {
  const entries = readdirSync(dir);
  const files: string[] = [];
  for (const entry of entries) {
    const path = `${dir}/${entry}`;
    const stat = statSync(path);
    if (stat.isDirectory()) {
      if (["api", "dev.tudastar", "lovable"].some((part) => path.includes(`/${part}`))) continue;
      files.push(...walkPublicUiSources(path));
      continue;
    }
    if (/\.(tsx|ts)$/.test(entry)) files.push(path);
  }
  return files;
}

for (const file of publicUiFiles) {
  const body = readFileSync(file, "utf8");
  for (const forbidden of [
    />Close</,
    />Previous</,
    />Next</,
    />Previous slide</,
    />Next slide</,
    />More pages</,
    />More</,
    />Toggle Sidebar</,
    /aria-label="Go to previous page"/,
    /aria-label="Go to next page"/,
    /aria-label="Toggle Sidebar"/,
    /aria-label="breadcrumb"/,
    /aria-label="pagination"/,
  ]) {
    if (forbidden.test(body)) {
      failures.push(`${file}: public UI accessibility text must be Hungarian: ${forbidden}`);
    }
  }
}

const publicTrustLeakFiles = [
  ...walkPublicUiSources("src/routes").filter(
    (file) =>
      !file.includes("/api/") &&
      !file.includes("/lovable/") &&
      !file.endsWith("dev.tudastar.tsx") &&
      !file.endsWith("robots[.]txt.tsx"),
  ),
  ...walkPublicUiSources("src/components").filter((file) => !file.includes("/ui/")),
  ...walkPublicUiSources("src/lib/email-templates"),
  "src/lib/error-page.ts",
  "src/lib/products.ts",
];
const publicTrustLeakPatterns = [
  /\bháttéradat\b/i,
  /\bháttértudás\b/i,
  /\bprovider response\b/i,
  /\bprovider error\b/i,
  /\bAPI\b/i,
  /\bapit\b/i,
  /\bRoxy API\b/i,
  /\bOpenAI\b/i,
  /\bGPT\b/i,
  /\bAI hiba\b/i,
  /\bmint AI\b/i,
  /tartalom-előkészítési/i,
  /külső infrastruktúra/i,
  /természetes magyar olvasattá/i,
  /közérthető magyar nyelven fogalmazzuk meg/i,
  /magyarra fordít/i,
  /lefordít/i,
  /fordítjuk/i,
];

for (const file of publicTrustLeakFiles) {
  const body = readFileSync(file, "utf8");
  for (const forbidden of publicTrustLeakPatterns) {
    if (forbidden.test(body)) {
      failures.push(`${file}: public trust copy must not expose internal/provider wording: ${forbidden}`);
    }
  }
}

const symbolicSourceNarrativeFiles = [
  "src/lib/angel.hu.ts",
  "src/lib/horoscope.hu.ts",
  "src/lib/iching.hu.ts",
  "src/lib/roxyTranslate.functions.ts",
  "src/lib/roxyNormalize.ts",
  "src/lib/roxyCardMap.ts",
  "src/lib/roxy.functions.ts",
  "src/lib/products/vedicFull.server.ts",
  "scripts/bake-lifepath.ts",
];
const symbolicSourceNarrativeForbidden = [
  /Roxy API/i,
  /Roxy lookup/i,
  /Roxy English/i,
  /raw Roxy/i,
  /Roxy values/i,
  /Roxy POST/i,
  /Roxy-sourced English/i,
  /English raw/i,
  /Source: Roxy/i,
  /AI translator/i,
  /Lovable AI Gateway/i,
  /translate\/stylize/i,
  /nyers angol/i,
  /raw provider/i,
  /provider-szöveg/i,
  /minden tartalmi forrás Roxy/i,
  /endpoint- vagy/i,
  /roxyapi\.com\/AGENTS\.md/i,
  /cache-elve a roxy\.server-en/i,
  /cache-eli az api_cache/i,
  /Roxy-forrás/i,
  /Angolról magyarra/i,
  /fordítjuk magyarra/i,
  /fordítva magyarra/i,
  /magyarítás/i,
  /magyarító/i,
  /tükörfordíts/i,
  /AI fordít/i,
];

for (const file of symbolicSourceNarrativeFiles) {
  const body = readFileSync(file, "utf8");
  for (const forbidden of symbolicSourceNarrativeForbidden) {
    if (forbidden.test(body)) {
      failures.push(`${file}: internal symbolic-source narrative must avoid provider/translation framing: ${forbidden}`);
    }
  }
}

for (const check of checks) {
  const body = readFileSync(check.file, "utf8");

  for (const forbidden of check.forbidden) {
    if (forbidden.test(body)) {
      failures.push(
        `${check.file}: unsafe static self-reflection claim still present: ${forbidden}`,
      );
    }
  }

  for (const required of check.required ?? []) {
    if (!body.includes(required)) {
      failures.push(`${check.file}: expected safer symbolic wording missing: ${required}`);
    }
  }
}

if (failures.length > 0) {
  console.error(failures.join("\n"));
  process.exit(1);
}

console.log(`Static content safety audit passed: ${checks.length} files.`);
