import { readFileSync } from "node:fs";

type Check = {
  name: string;
  file: string;
  includes: string[];
  excludes?: string[];
  enforceExcludes?: boolean;
};

const checks: Check[] = [
  {
    name: "checkout stores source route",
    file: "src/lib/payments.functions.ts",
    includes: ["source_route: data.sourceRoute ?? null", "stripe_environment: data.environment"],
  },
  {
    name: "checkout survives pending migration",
    file: "src/lib/payments.functions.ts",
    includes: [
      "insertOrderWithMigrationFallback",
      "isMissingColumnError",
      "inserting order without fallback fields",
    ],
  },
  {
    name: "pending payment can be reconciled server-side",
    file: "src/lib/payments.functions.ts",
    includes: [
      "PAYMENT_RECHECK_INTERVAL_MS",
      "reconcilePendingPayment",
      "ORDER_SELECT_BASE",
      "stripe.checkout.sessions.retrieve(sessionId)",
      "session.payment_status",
    ],
  },
  {
    name: "webhook marks payment recheck state",
    file: "src/routes/api/public/payments/webhook.ts",
    includes: ["payment_rechecked_at: new Date().toISOString()"],
  },
  {
    name: "webhook survives pending reconciliation migration",
    file: "src/routes/api/public/payments/webhook.ts",
    includes: [
      "isMissingColumnError",
      "orders reconciliation columns unavailable in webhook",
      "fallbackPaidUpdate",
      "_stripePaymentIntent",
      "_paymentRecheckedAt",
    ],
  },
  {
    name: "webhook stores stable payment failure codes",
    file: "src/routes/api/public/payments/webhook.ts",
    includes: [
      "type PaymentFailureCode",
      '"stripe_async_payment_failed"',
      '"stripe_checkout_expired"',
      "function paymentFailureCode",
      "error_message: paymentFailureCode(event.type)",
    ],
    excludes: ["error_message: event.type"],
  },
  {
    name: "thank-you page can read source route",
    file: "src/lib/payments.functions.ts",
    includes: ["ORDER_SELECT_BASE", "created_at", "guest_email", "source_route"],
  },
  {
    name: "paid memory keeps source route",
    file: "src/lib/orderProcessing.server.ts",
    includes: [
      "source_route, response_payload",
      "source_route: order.source_route",
      "memorySituation(order.input_payload)",
      "data.category ?? data.situation",
      '"situation"',
      "ORDER_PROCESSING_RETRY_AFTER_MS",
      "PROCESSING_RETRY_AFTER_MS",
    ],
  },
  {
    name: "thank-you page exposes continuation CTA",
    file: "src/routes/koszonjuk.tsx",
    includes: ["Innen folytathatod", "Vissza az olvasathoz"],
  },
  {
    name: "thank-you page shows safe captured order summary",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "OrderCapturedSummary",
      "Ezt rögzítettük",
      "biztonságos rendelési link + vásárlási email",
      "biztonságos rendelési link + profil",
      "az előző olvasati útvonaladhoz kapcsolva",
      "csúszásnál a gyorsítás díját külön rendezzük",
      "A személyes kérdést és a megadott adatokat nem ismételjük ki ezen az oldalon",
      "de a rendelés",
      "elkészítéséhez rögzítettük őket",
    ],
    excludes: ["input_payload", "JSON.stringify(order", "JSON.stringify(payload"],
  },
  {
    name: "thank-you page exposes support contact",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "SupportContact",
      "supportMailto({ order })",
      "Jövőd.hu rendelési segítség",
      "Termék:",
      "Állapot:",
      "orderStatusLabel(order.status)",
      "A vásárlási email címem:",
      "Mi történt röviden:",
      "SITE_LEGAL.supportEmail",
      "Ügyfélszolgálat",
    ],
  },
  {
    name: "thank-you page reassures when delivered email delivery needs attention",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      'delivery_email_status?: "queued" | "attention_needed" | null',
      'order.delivery_email_status === "attention_needed"',
      "DeliveryEmailNotice",
      "Email kézbesítés",
      "Az olvasatod már elkészült",
      "innen biztonságosan elérhető",
      "elsődleges közvetlen hozzáférés",
      "SupportContact",
    ],
    excludes: [
      "delivery_email_error",
      "delivery_email_queued_at",
      "legbiztosabb közvetlen hozzáférés",
    ],
    enforceExcludes: true,
  },
  {
    name: "thank-you page distinguishes instant and detailed paid preparation",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "orderPreparationLead",
      "orderPreparationDetail",
      "több szakaszban, a választott hagyomány jelképeivel dolgozzuk össze",
      "a megadott adatokból, kérdésből és a választott hagyomány jelképeiből áll össze",
      "Express rendelésnél",
      "gyorsított határidő csúszna",
      "a gyorsítás díját külön rendezzük",
      "const base = deadline",
      "if (!order.express) return base",
      "pár percig hagyd nyitva",
      "biztonságos rendelési linket érdemes megtartanod",
      "Ha az oldal nem frissül, írj nekünk a vásárlási email címedről",
      "rövid rendelésazonosítót",
    ],
    excludes: [
      "nem egy rövid automata választ",
      "nem egy rövid sablonválaszt",
      "nem azonnali sablonszöveget",
      "rendelés email címéről",
    ],
    enforceExcludes: true,
  },
  {
    name: "thank-you page exposes a short order reference",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "function shortOrderId",
      "Rendelés:",
      "shortOrderId(order.id)",
      "add meg ezt",
      "rövid rendelésazonosítót",
    ],
  },
  {
    name: "thank-you page tells guest customers to save the full secure order link",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "Vendégként vásároltál",
      "ehhez az oldalhoz és a vásárlási email",
      "ezt a teljes, biztonságos rendelési linket",
      "megtartanod",
      "Rögzített cím: {maskEmail(order.guest_email)}",
    ],
    excludes: ["ezért érdemes ezt a linket megtartanod"],
  },
  {
    name: "thank-you page reassures when long polling stops",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "pollingPaused",
      "MAX_ATTEMPTS",
      "setPollingPaused(true)",
      "OrderPollingPaused",
      "Hosszabb ellenőrzés alatt",
      "a rendelésed nem tűnt el",
      "Frissíts rá később erre az oldalra",
      "rövid rendelésazonosítót",
      "ne indíts új fizetést",
      "ne rendeld meg újra ugyanazt az olvasatot",
      "ugyanerről a biztonságos linkről",
      "rendelésazonosító alapján rendezzük a hozzáférést",
      '<SupportContact className="mt-3" order={order} />',
    ],
  },
  {
    name: "thank-you page keeps polling when the order row is initially missing",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "orderLookupPending",
      "setOrderLookupPending(true)",
      "if (!r.order)",
      "setTimeout(tick, 2500)",
      "Fizetés egyeztetése",
      "most összekapcsoljuk a vásárlásoddal",
      "amint az egyeztetés lezárul",
      "a rendelés nem vész el",
      "frissíts rá később erre a teljes linkre",
    ],
    excludes: [
      "keressük hozzá a rendelési sort",
      "rendelésállapot beért",
      "fizetési szolgáltató gyorsabban",
    ],
  },
  {
    name: "profile prefers stored source route",
    file: "src/routes/profil.tsx",
    includes: ["source_route?: string | null", "o.source_route ?? PRODUCTS_BY_SLUG"],
  },
  {
    name: "profile can wake paid or processing orders without exposing session ids",
    file: "src/routes/profil.tsx",
    includes: [
      "processMyOrder",
      "const wakeOrder = useServerFn(processMyOrder)",
      "awakenedOrders",
      'order.status === "paid" || order.status === "processing"',
      "wakeOrder({ data: { orderId: order.id } })",
      "const refreshed = await call({})",
    ],
  },
  {
    name: "profile claims verified guest orders after login",
    file: "src/lib/payments.functions.ts",
    includes: [
      "claimGuestOrdersForAuthenticatedUser",
      "emailFromAuthClaims(context.claims)",
      "normalizeClaimEmail",
      "CLAIMABLE_GUEST_ORDER_STATUSES",
      "claimedGuestOrderCount",
      "supabaseAdmin",
      '.is("user_id", null)',
      '.ilike("guest_email", email)',
      '.in("status", [...CLAIMABLE_GUEST_ORDER_STATUSES])',
      '.from("order_feedback")',
      '.in("order_id", claimedIds)',
      '.is("user_id", null)',
      "feedbackClaimError",
      "guest order claim failed",
      'error_code: "guest_order_claim_failed"',
      "database_code: stableErrorCode(error)",
      'error_code: "guest_order_feedback_claim_failed"',
      "database_code: stableErrorCode(feedbackClaimError)",
      "claimed_order_count: claimedIds.length",
    ],
    excludes: [
      "stripe_session_id: sessionId",
      "stripe_payment_intent: paymentIntent",
      "message: error.message",
      "code: error.code",
      "guest order claim failed:",
      "error: feedbackClaimError",
    ],
  },
  {
    name: "profile tells users when guest purchases were attached",
    file: "src/routes/profil.tsx",
    includes: [
      "claimedGuestOrderCount",
      "setClaimedGuestOrderCount",
      "r.claimedGuestOrderCount",
      "Áthoztuk",
      "korábbi vendégvásárlásodat ebbe a profilba",
      "ugyanazzal az email címmel jelentkeztél be",
      "A biztonságos rendelési linkek továbbra",
    ],
  },
  {
    name: "profile lets customers retry failed paid reading processing safely",
    file: "src/routes/profil.tsx",
    includes: [
      "retryingOrders",
      "retryNotices",
      "type RetryNotice",
      "async function retryOrder",
      "wakeOrder({ data: { orderId } })",
      "OrderRetryNotice",
      "Most nem sikerült újraindítani az olvasatkészítést",
      "A rendelés nem vész el",
      "Feldolgozás újrapróbálása",
      "Rendelés biztonságban",
      "Az olvasatkészítés most elakadt",
      "A fizetést ellenőrizzük",
      "újraindítást csak akkor engedjük",
      "fizetés igazoltan sikeres",
      "pótoljuk az olvasathoz való",
      'aria-live="polite"',
      'role="status"',
      "Újrapróbálás…",
      "retrying={retryingOrders.has(o.id)}",
      "onRetry={() => retryOrder(o.id)}",
    ],
    excludes: ["border-red-400", "bg-red-950", "kézzel elkészítjük az"],
    enforceExcludes: true,
  },
  {
    name: "thank-you page lets guest customers retry failed processing safely",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "retryingFailedOrder",
      "retryNotice",
      "async function retryFailedOrder",
      "paid_order_retry_clicked",
      "runProcess({ data: { sessionId: session_id } })",
      "const refreshed = await fetchOrder",
      "Rendelés biztonságban",
      "Az olvasatkészítés most elakadt",
      "Feldolgozás újrapróbálása",
      "akkor engedjük újraindítani, ha a fizetés igazoltan sikeres",
      "a fizetést ellenőrizzük",
      "Ha az újrapróbálás sem rendezi",
      "A rendelés nem vész el",
      "pótoljuk az",
      "jogos esetben visszatérítési egyeztetést",
      "shortOrderId(order.id)",
      'aria-live="polite"',
      'role="status"',
    ],
    excludes: [
      "Sajnos hiba történt",
      "Kapcsolódási hiba",
      "állapotlekérés",
      "az olvasatot, vagy visszatérítjük",
    ],
    enforceExcludes: true,
  },
  {
    name: "profile order wakeup is server-side and strips private payment fields",
    file: "src/lib/payments.functions.ts",
    includes: [
      "ORDER_SELECT_PROFILE_WITH_RECONCILIATION",
      "ORDER_SELECT_WITH_DELIVERY_STATE",
      "stripe_session_id",
      "delivery_email_queued_at",
      "delivery_email_error",
      "reconcilePendingPayment(order, sessionId)",
      "export const processMyOrder",
      '.eq("user_id", context.userId)',
      "processPaidOrderBySession(order.stripe_session_id)",
      "safeOrderProcessingResult",
      "ORDER_PROCESSING_GENERIC_ERROR",
      "function stripPrivateOrderFields",
      "function publicDeliveryEmailStatus",
      "delivery_email_status: publicDeliveryEmailStatus(order)",
      '"attention_needed"',
      "function sanitizePublicResponsePayload",
      "raw: _raw",
      "generation: rawGeneration",
      "publicPayload.generation",
      'generation.source === "ai"',
      'generation.source === "local_premium_draft"',
      "qualityRejected: generation.qualityRejected === true",
      "qualityIssues: Array.isArray(generation.qualityIssues)",
      "response_payload: sanitizePublicResponsePayload(publicOrder.response_payload)",
      "_stripeSessionId",
      "_deliveryEmailQueuedAt",
      "_deliveryEmailError",
      "reconciled.map(stripPrivateOrderFields)",
    ],
    excludes: [
      "provider: generation.provider",
      "model: generation.model",
      "latencyMs: generation.latencyMs",
    ],
  },
  {
    name: "paid order generation failures store safe codes, not raw exception text",
    file: "src/lib/orderProcessing.server.ts",
    includes: [
      "PUBLIC_ORDER_PROCESSING_ERROR",
      "A rendelés nem vész el; frissíts rá pár perc múlva",
      "vásárlási email címedről, és utánanézünk",
      "ORDER_GENERATION_FAILED_CODE",
      '"paid_reading_generation_failed"',
      "paid order processing failed",
      "function redactOrderId",
      "order_id_redacted: redactOrderId(order.id)",
      "error_code: ORDER_GENERATION_FAILED_CODE",
      "error_message: ORDER_GENERATION_FAILED_CODE",
      "return { ok: false, error: PUBLIC_ORDER_PROCESSING_ERROR }",
    ],
    excludes: [
      "próbáld újra később, vagy írj nekünk a vásárlási email címedről",
      'console.error("paid order processing failed", {\n      order_id: order.id',
      "const message = e instanceof Error ? e.message : String(e)",
      "error: message",
      "error_message: message",
      "return { ok: false, error: message }",
      '.update({ status: "failed", error_message: message })',
    ],
  },
  {
    name: "payment server errors keep customers oriented during checkout and recheck failures",
    file: "src/lib/payments.functions.ts",
    includes: [
      "CHECKOUT_GENERIC_ERROR",
      "Kártyaadat ilyenkor nem jut el hozzánk",
      "indítsd újra nyugodtan",
      "ORDER_PROCESSING_GENERIC_ERROR",
      "A rendelés nem vész el; frissíts rá pár perc múlva",
      "vásárlási email címedről, és utánanézünk",
      "PAYMENT_RECHECK_PUBLIC_ERROR",
      "Most nem sikerült ellenőrizni a fizetést",
      "return { ok: false, error: PAYMENT_RECHECK_PUBLIC_ERROR }",
      "PAYMENT_RECHECK_PUBLIC_ERROR,",
    ],
    excludes: [
      "Most nem sikerült elindítani a fizetést. Kérlek próbáld újra pár perc múlva.",
      "kérlek próbáld újra később, vagy írj nekünk a vásárlási email címedről",
      'return { ok: false, error: "Most nem sikerült ellenőrizni a fizetést" }',
      '"Most nem sikerült ellenőrizni a fizetést",',
    ],
  },
  {
    name: "delivered order email failures store safe codes, not raw provider errors",
    file: "src/lib/orderProcessing.server.ts",
    includes: [
      "delivery_email_error: result.error",
      'delivery_email_error: "delivery_email_exception"',
      "order delivered email queue failed",
      'error_code: "delivery_email_exception"',
    ],
    excludes: [
      "delivery_email_error: result.error.slice",
      "delivery_email_error: message.slice",
      "const message = error instanceof Error ? error.message : String(error)",
      'console.warn("order delivered email queue failed:", {',
      'console.warn("order delivered email queue failed:", message)',
      'console.warn("order delivery email error state failed:", updateError)',
    ],
  },
  {
    name: "email queue stores stable error codes, not raw provider messages",
    file: "src/routes/lovable/email/queue/process.ts",
    includes: [
      "type EmailQueueErrorCode",
      "'email_send_failed'",
      "'email_send_rate_limited'",
      "'email_send_forbidden'",
      "'email_send_ttl_exceeded'",
      "'email_send_retry_exhausted'",
      "function emailQueueErrorCode",
      "function redactQueueMessageId",
      "function redactStableMessageId",
      "error_message: emailQueueErrorCode(error)",
      "queue_msg_id_redacted: redactQueueMessageId(msg.msg_id)",
      "message_id_redacted: redactStableMessageId(payload.message_id)",
      "error_code: emailQueueErrorCode(error)",
      "moveToDlq(supabase, queue, msg, 'email_send_ttl_exceeded')",
      "moveToDlq(supabase, queue, msg, 'email_send_retry_exhausted')",
      "moveToDlq(supabase, queue, msg, 'email_send_forbidden')",
    ],
    excludes: [
      "error_message: errorMsg.slice",
      "await moveToDlq(supabase, queue, msg, errorMsg",
      "await moveToDlq(supabase, queue, msg, `TTL exceeded",
      "await moveToDlq(supabase, queue, msg, `Max retries",
      "msg_id: msg.msg_id",
      "message_id: payload.message_id",
      "error: readError",
      "error: failedRowsError",
      "error: dupDelError",
      "error: delError",
      "error: errorMsg",
      "const errorMsg = error instanceof Error ? error.message : String(error)",
    ],
  },
  {
    name: "transactional email helper returns stable error codes",
    file: "src/lib/email/sendTransactional.server.ts",
    includes: [
      "export type TransactionalEmailError",
      '"unknown_template"',
      '"missing_recipient_email"',
      '"email_suppressed"',
      '"unsubscribe_token_unavailable"',
      '"email_queue_unavailable"',
      'error_message: "email_queue_unavailable"',
      "recipient_redacted: redactEmail",
      "function redactStableMessageId",
      'error_code: "unsubscribe_token_unavailable"',
      'error_code: "email_queue_unavailable"',
      "message_id_redacted: redactStableMessageId(messageId)",
    ],
    excludes: [
      "`Unknown template: ${input.templateName}`",
      '"recipientEmail required"',
      "`unsubscribe token: ${tokErr.message}`",
      "return { ok: false, error: enqErr.message }",
      "error_message: `enqueue: ${enqErr.message}`",
      "error: tokErr",
      "error: enqErr",
      "messageId,",
    ],
  },
  {
    name: "failed order retry verifies Stripe payment before resetting processing",
    file: "src/lib/payments.functions.ts",
    includes: [
      'order.status === "failed"',
      "prepareFailedOrderRetry",
      "stripe.checkout.sessions.retrieve(order.stripe_session_id)",
      'session.payment_status !== "paid" && session.status !== "complete"',
      'status: "paid"',
      "error_message: null",
      '.eq("status", "failed")',
      "export const processOrder",
      '.eq("stripe_session_id", data.sessionId)',
      'if (order?.status === "failed")',
      "prepareFailedOrderRetry(supabaseAdmin, order)",
    ],
  },
  {
    name: "profile explains paid order status",
    file: "src/routes/profil.tsx",
    includes: [
      "OrderOverviewNotice",
      "Rendelési állapot összefoglaló",
      "készül vagy egyeztetés alatt",
      "A profilban is megjelenik; a fizetés utáni rendelési linket is érdemes megtartanod",
      "kész olvasat",
      "másolhatod, letöltheted és visszajelzést küldhetsz",
      "figyelmet kér",
      "újrapróbálhatod a feldolgozást",
      "OrderStatusNote",
      "A fizetés állapotát még egyeztetjük",
      "csak a fizetési visszajelzésre várunk",
      "Az olvasat készül",
      "Az olvasatkészítés most elakadt",
      "pótoljuk az olvasathoz való",
      "jogos esetben visszatérítési egyeztetést",
      "SITE_LEGAL.supportEmail",
    ],
    excludes: ["az olvasatot, vagy visszatérítjük", "Tartsd meg a linket; ha elkészül"],
    enforceExcludes: true,
  },
  {
    name: "profile distinguishes instant and detailed paid preparation",
    file: "src/routes/profil.tsx",
    includes: [
      "profileOrderPreparationLead",
      "profileOrderPreparationDetail",
      "több szakaszos elemzés áll össze",
      "a választott hagyomány jelképeiből",
      "Az azonnali termékek általában pár percen belül",
      "ha az email késik, a profilban akkor is",
      "Express rendelésnél",
      "gyorsított határidő csúszna",
      "a gyorsítás díját külön rendezzük",
    ],
    excludes: ["nem azonnali sablonválasz", "nem azonnali sablonszöveg"],
    enforceExcludes: true,
  },
  {
    name: "profile exposes support contact for stuck orders",
    file: "src/routes/profil.tsx",
    includes: [
      "function shortOrderId",
      "Rendelés:",
      "shortOrderId(o.id)",
      "ProfileSupportContact",
      "profileSupportMailto({ order })",
      "href={profileSupportMailto({ order })}",
      "Jövőd.hu rendelési segítség",
      "Termék:",
      "Állapot:",
      "STATUS_HU[order.status]",
      "A vásárlási email címem:",
      "Mi történt röviden:",
      "Ha továbbra is így marad",
      "vásárlási email címedről",
      "Add meg ezt is",
      "Az olvasat elkészült, de itt nem tudjuk teljes szövegként megjeleníteni",
      "SITE_LEGAL.supportEmail",
    ],
  },
  {
    name: "profile reassures when delivered email delivery needs attention",
    file: "src/routes/profil.tsx",
    includes: [
      'delivery_email_status?: "queued" | "attention_needed" | null',
      'o.delivery_email_status === "attention_needed"',
      "ProfileDeliveryEmailNotice",
      "Email kézbesítés",
      "Az olvasat elkészült és itt a profilban megnyitható",
      "postafiókodban",
      "profilnézet marad az elsődleges hozzáférésed",
      "ProfileSupportContact",
    ],
    excludes: [
      "delivery_email_error",
      "delivery_email_queued_at",
      "profilnézet marad a biztos hozzáférésed",
    ],
    enforceExcludes: true,
  },
  {
    name: "paid reading body can be copied or downloaded for later use",
    file: "src/components/PaidReadingBody.tsx",
    includes: [
      "navigator.clipboard.writeText",
      "URL.createObjectURL",
      "URL.revokeObjectURL",
      'type: "text/plain;charset=utf-8"',
      "formatDownloadedReading(body, { title, productName, orderReference })",
      "function formatDownloadedReading",
      "const clarificationDraft = paidReadingClarificationDraft({",
      "Jövőd.hu",
      "Személyes olvasat",
      "Termék:",
      "Rendelés:",
      "Letöltve:",
      "Hogyan olvasd vissza:",
      "keresd azt a mondatot, amelyiknél megállsz",
      "nézd meg, melyik rész kért figyelmet",
      "melyik téma tért vissza",
      "Mentett példány és pontosítás:",
      "Ha pontosítást kérsz, erre hivatkozz.",
      "vásárlási email címedről írj",
      "rendelés alapján visszanézhessük",
      "Nem kell a teljes olvasatot bemásolni",
      "mit szeretnél pontosítani",
      "mit érdemes még hozzátenni",
      "Pontosítási vázlat:",
      "régi jelképrendszerekből készült önismereti olvasat",
      "SITE_LEGAL.supportEmail",
      "link.download",
      "paidReadingDownloadFilename(orderReference)",
      "function paidReadingDownloadFilename(orderReference?: string): string",
      '.replace(/[^a-z0-9-]+/g, "-")',
      "`jovod-olvasat-${huTodayKey()}-${safeReference}.txt`",
      "jovod-olvasat-",
      "Olvasat másolása",
      "Kimásolva",
      "Nem másolható",
      "Olvasat letöltése",
      "Letöltés indult",
      "Nem indult el",
      "readingSaveStatusMessage",
      'aria-live="polite"',
      "A böngésző most nem engedte a másolást",
      "Az olvasat nem vész el",
      "készíthetsz képernyőképet",
      "A letöltés most nem indult el",
      "Az olvasat nem vész el, ezen az oldalon továbbra is elérhető",
      "másold ki kézzel, vagy készíts képernyőképet",
      "ezen az oldalon továbbra is elérhető",
      "A pontosítási vázlatot most nem sikerült kimásolni",
      "SITE_LEGAL.supportEmail",
      "elég a rendelésazonosítót megadnod",
      "később is visszanézheted",
      "kimásolhatod vagy letöltheted",
      "Mentéskor a fájl tartalmazza a címet",
      "visszaolvasási",
      "rövid pontosítási vázlatot",
      "ReadingUseGuide",
      "ReadingSelfCheck",
      "ReadingContinuationGuide",
      "ReadingAssuranceNotice",
      "paidReadingSelfCheck",
      "function paidReadingClarificationDraft",
      "paidReadingContinuation",
      "paidReadingAssurance",
      "PaidReadingGenerationPublic",
      "selfCheckReadingType",
      "selfCheckItems",
      "Minőségbiztosítás",
      "Ellenőrzött, óvatosan szerkesztett olvasat",
      "konkrétan a rendelésedhez és a megadott helyzetedhez kell kapcsolódnia",
      "Rendelés alapján visszanézhető olvasat",
      "a kártyákból, számokból vagy horoszkópjelekből indul ki",
      "mit szeretnél más fókuszba tenni",
      "generation?: PaidReadingGenerationPublic",
      "Pontosítás, ha továbbírnád",
      "Pontosítási vázlat másolása",
      "Pontosítást kérek emailben",
      "clarificationMailto",
      "function paidReadingClarificationMailto",
      "Jövőd.hu pontosítási kérés${orderReference ?",
      "encodeURIComponent(subject)",
      "encodeURIComponent(body)",
      "Kérlek, nézzétek vissza rendelés alapján",
      "Az email",
      "tartalmazza a rendelésazonosítót",
      "pontosítási vázlatot",
      "Nem másolható",
      "Jövőd.hu pontosítási kérés",
      "Ami kapcsolódott a helyzetemhez:",
      "Amit szeretnék pontosítani:",
      "A helyzetemből ezt érdemes még hozzátenni:",
      "Ebben az irányban kérnék finomítást:",
      "Akkor hasznos, ha az olvasat jó irányba indult",
      "mit pontosítanál",
      "mit érdemes még hozzátenni",
      "Pontosan meg tudod nevezni, mit pontosítanál vagy mit érdemes még hozzátenni",
      "Irányt és mintát mutat, józan önismereti keretben",
      "tempót és realitást is olvas",
      "Olvasási iránytű",
      "Először azt a mondatot keresd",
      "Olvasd vissza azt a részt",
      "7 nap múlva",
      "melyik téma tért vissza azóta",
      "következő jó kérdés",
      "Egy mondatban",
      "Most azt viszem tovább",
      "mit viszel tovább",
      "sm:grid-cols-2 xl:grid-cols-5",
      "mi kapcsolódott a helyzetedhez",
      "milyen irányban kérnél finomítást",
      "visszaviszed a saját helyzetedbe",
      "része pontosítást kér",
      "mailto:${SITE_LEGAL.supportEmail}",
      "rendelésazonosítóval gyorsabban visszanézzük",
      "Innen folytathatod",
      "Ugyanazt a fő kérdést vidd tovább",
      "Új olvasatot akkor érdemes indítani, ha valóban új kérdésed van",
      "ne vásárolj emiatt újra",
      "rendelésazonosító alapján",
      "Mi maradt még nyitva?",
      "Ha ezt a kapcsolatot tovább néznéd",
      "tartós közeledés látszik-e",
      "/osszeillunk",
      "/dontes-elott",
      "/szemelyes-30-napos-horoszkop",
    ],
    excludes: [
      "Az első változat nem ment át",
      "belső ellenőrzésen",
      "Szerkesztett biztonsági változat",
      "biztonsági változat",
      'copyState === "failed"\n                ? "Most nem sikerült"',
      'downloadState === "failed"\n                ? "Most nem sikerült"',
      'clarifyState === "failed"\n              ? "Most nem sikerült"',
      "melyik rész talált",
      "melyik részt finomítanád",
      "mi maradt ki a helyzetedből",
      "milyen irányban vársz pontosítást",
      "Ami túl általános vagy pontatlan volt:",
      "Ne új, általános kérdésként kezdd újra",
      "mi maradt ki vagy melyik részt finomítsuk",
      "Ha leírod pár szóban, mi maradt ki",
      "azt a részt vagy érzést megírni",
      "egy fontos rész kimaradt",
      "próbáld újra, vagy másold ki kézzel",
      "a lenti email címen",
      "Ha valami kimaradt",
      "melyik részt érdemes finomítani",
      "merre finomítsuk",
      "pontosítási teendőket",
    ],
  },
  {
    name: "delivered thank-you page asks for quality feedback safely",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "PaidReadingFeedback",
      "feedback?: FeedbackValue",
      "normalizeFeedbackSearch",
      "emailFeedback={feedback}",
      "emailFeedbackHandled",
      "FEEDBACK_OPTIONS",
      "PaidReadingGenerationPublic",
      "generation?: PaidReadingGenerationPublic",
      "generation={payload.generation}",
      "submitOrderFeedbackBySession",
      "Minőségi visszajelzés",
      "Hasznos volt",
      "Részben volt hasznos",
      "mit pontosítanék vagy tennék hozzá",
      "Pontosítást kérek",
      "paid_reading_feedback_clicked",
      "saved: true",
      'source: "thank_you"',
      "!emailFeedback ||",
      "void saveFeedback(option)",
      "order.feedback ?? null",
      "Köszönjük, mentettük a visszajelzést",
      "feedbackNote",
      "Mit finomítsunk?",
      "ezt a kapcsolati mintát érdemes még hozzátenni",
      "maxLength={600}",
      "Pontosítás mentése",
      "Inkább emailben írom le",
      "note: note?.trim()",
      "A beírt szöveg nem vész el",
      "ugyanazzal a rendelésazonosítóval működik",
      'aria-live="polite"',
      "feedbackMailto",
      "note: feedbackNote",
      "note?: string",
      'opts.note === "string"',
      "opts.note.trim().slice(0, 600)",
      "Rendelés:",
      "Termék:",
      "Ami kapcsolódott a helyzetemhez:",
      "Amit szeretnék pontosítani:",
      "A helyzetemből ezt érdemes még hozzátenni:",
      "A saját helyzetemből ezt érdemes még figyelembe venni:",
      "Ebben az irányban kérnék finomítást:",
      "pontosítási",
      "mit érdemes még hozzátenni vagy melyik részt pontosítanád",
      "olvasat teljes szövegét nem tesszük bele automatikusan",
      "Nem kell a teljes olvasatot bemásolni",
      "elég megírni, mi kapcsolódott",
      "SITE_LEGAL.supportEmail",
    ],
    excludes: [
      "Most nem sikerült menteni a visszajelzést, de emailben elküldheted.",
      "Eltalált",
      "Részben talált",
      "Az olvasat eltalált",
      "Az olvasat részben talált",
      "Melyik rész nem talált?",
      "túl általános volt",
      "nem kötődött eléggé",
      "nem vette figyelembe",
      "Ami nem volt elég pontos:",
      "Mi maradt ki?",
      "Ezt a részt szeretném finomítani:",
      "A helyzetemből ez maradt ki:",
      "Ebben az irányban kérek pontosítást:",
      "Ezt a részt szeretném finomítani:",
      "Melyik részt szeretném finomítani?",
      "melyik részt érdemes tovább finomítani",
      "mi maradt ki vagy melyik részt finomítsuk",
      "Ha leírod pár szóban, mi maradt ki",
      "azt a részt vagy érzést megírni",
      "Mi az a konkrét helyzet",
      "Milyen irányban várnék pontosítást?",
    ],
  },
  {
    name: "profile delivered reading asks for quality feedback safely",
    file: "src/routes/profil.tsx",
    includes: [
      "PaidReadingGenerationPublic",
      "generation?: PaidReadingGenerationPublic",
      "generation={payload.generation}",
      "data.generation as PaidReadingGenerationPublic",
      "ProfilePaidReadingFeedback",
      "submitMyOrderFeedback",
      "Minőségi visszajelzés",
      "Hasznos volt",
      "Részben volt hasznos",
      "mit pontosítanék vagy tennék hozzá",
      "Pontosítást kérek",
      "paid_reading_feedback_clicked",
      "saved: true",
      'source: "profile"',
      "order.feedback ?? null",
      "Köszönjük, mentettük a visszajelzést",
      "feedbackNote",
      "Mit finomítsunk?",
      "ezt a részt szeretném pontosítani",
      "fontos oldalát érdemes még hozzátenni",
      "maxLength={600}",
      "Pontosítás mentése",
      "Inkább emailben írom le",
      "note: note?.trim()",
      "A beírt szöveg nem vész el",
      "ugyanazzal a rendelésazonosítóval működik",
      'aria-live="polite"',
      "profileFeedbackMailto",
      "note: feedbackNote",
      "note?: string",
      'opts.note === "string"',
      "opts.note.trim().slice(0, 600)",
      "Rendelés:",
      "Termék:",
      "Ami kapcsolódott a helyzetemhez:",
      "Amit szeretnék pontosítani:",
      "A helyzetemből ezt érdemes még hozzátenni:",
      "A saját helyzetemből ezt érdemes még figyelembe venni:",
      "Ebben az irányban kérnék finomítást:",
      "pontosítási vázlattal",
      "mit érdemes még hozzátenni",
      "melyik részt",
      "pontosítanád",
      "olvasat teljes szövegét nem tesszük bele automatikusan",
      "Nem kell a teljes olvasatot bemásolni",
      "elég megírni, mi kapcsolódott",
      "SITE_LEGAL.supportEmail",
    ],
    excludes: [
      "Most nem sikerült menteni a visszajelzést, de emailben elküldheted.",
      "Eltalált",
      "Részben talált",
      "Az olvasat eltalált",
      "Az olvasat részben talált",
      "Melyik rész nem talált?",
      "túl általános volt",
      "nem kötődött eléggé",
      "nem vette figyelembe",
      "Ami nem volt elég pontos:",
      "Mi maradt ki?",
      "Ezt a részt szeretném finomítani:",
      "Melyik részt szeretném finomítani?",
      "melyik részt érdemes tovább finomítani",
      "mi maradt ki vagy melyik részt finomítsuk",
      "Ha leírod pár szóban, mi maradt ki",
      "azt a részt vagy érzést megírni",
      "Mi az a konkrét helyzet",
      "Milyen irányban várnék pontosítást?",
    ],
  },
  {
    name: "paid reading feedback is persisted without Stripe or full reading leakage",
    file: "src/lib/payments.functions.ts",
    includes: [
      "type OrderFeedbackValue",
      "const FEEDBACK_VALUES",
      "function normalizeOrderFeedback",
      "function normalizeFeedbackNote",
      "attachOrderFeedback",
      "attachOrdersFeedback",
      '.select("order_id, feedback")',
      "export const submitOrderFeedbackBySession",
      '.eq("stripe_session_id", data.sessionId)',
      'order.status !== "delivered"',
      '.from("order_feedback").upsert',
      'source: "thank_you"',
      "export const submitMyOrderFeedback",
      ".middleware([requireSupabaseAuth])",
      '.eq("user_id", context.userId)',
      'source: "profile"',
    ],
  },
  {
    name: "order feedback migration keeps customer signals private",
    file: "supabase/migrations/20260616163000_order_feedback.sql",
    includes: [
      "CREATE TABLE IF NOT EXISTS public.order_feedback",
      "feedback TEXT NOT NULL CHECK",
      "source TEXT NOT NULL CHECK",
      "UNIQUE (order_id)",
      "ALTER TABLE public.order_feedback ENABLE ROW LEVEL SECURITY",
      "Order feedback selectable by owner",
      "Order feedback insertable by order owner",
      "Order feedback updatable by order owner",
      "GRANT ALL ON public.order_feedback TO service_role",
      "trg_order_feedback_updated",
    ],
    excludes: ["stripe_session_id", "response_payload"],
  },
  {
    name: "order feedback table exists in generated supabase types",
    file: "src/integrations/supabase/types.ts",
    includes: [
      "order_feedback: {",
      'order_feedback_value: "accurate" | "partial" | "missed"',
      'order_feedback_source: "thank_you" | "profile"',
      "order_feedback_order_id_fkey",
      'referencedRelation: "orders"',
    ],
  },
  {
    name: "internal order feedback summary is protected and aggregate-only",
    file: "src/routes/api/internal/order-feedback/summary.ts",
    includes: [
      'createFileRoute("/api/internal/order-feedback/summary")',
      "ORDER_FEEDBACK_SUMMARY_SECRET",
      "SUPABASE_SERVICE_ROLE_KEY",
      "Authorization",
      "Bearer ",
      'return Response.json({ ok: false, error: "unauthorized" }, { status: 401 })',
      "function summarizeRows",
      "ProductFeedbackSummary",
      "type OrderHealthRow",
      "type OrderHealthSummary",
      "type DeliveryEmailState",
      "type DeliveryEmailHealthRow",
      "type DeliveryEmailHealthSummary",
      "missRate",
      "detailCount",
      "negativeDetailCount",
      "detailRate",
      "needsAttention",
      "ReviewPriority",
      "reviewPriorityFor",
      "reviewRecommendation",
      "manual_review_first",
      "read_feedback_details",
      "watch_next_orders",
      "reviewPriorityCounts",
      "ATTENTION_MIN_TOTAL",
      "ATTENTION_MISS_RATE",
      "LEGACY_BUTTON_NOTES",
      "function hasWrittenDetail",
      "function parseStaleProcessingMinutes",
      "function stableDatabaseErrorCode",
      "function normalizeOrderHealthErrorCode",
      "function normalizeDeliveryEmailErrorCode",
      "function deliveryEmailState",
      "internal_error",
      "function summarizeOrderHealth",
      "function summarizeDeliveryEmailHealth",
      "DEFAULT_STALE_PROCESSING_MINUTES",
      "MAX_STALE_PROCESSING_MINUTES",
      '.select("product_slug, product_name, feedback, source, note, created_at")',
      '.from("orders")',
      "product_slug, product_name, category, status, error_message, express, created_at, updated_at",
      '.in("status", ["failed", "processing", "paid"])',
      "product_slug, product_name, category, delivery_email_error, delivery_email_queued_at, delivered_at, created_at, updated_at",
      '.eq("status", "delivered")',
      '.gte("delivered_at", since)',
      "needsAttentionCount",
      "staleProcessingMinutes",
      "orderHealth",
      "deliveryEmailHealth",
      "order_health_summary_unavailable",
      "delivery_email_health_summary_unavailable",
      "order feedback summary failed",
      'error_code: "order_feedback_summary_failed"',
      "database_code: stableDatabaseErrorCode(error)",
      "order health summary failed",
      'error_code: "order_health_summary_failed"',
      "database_code: stableDatabaseErrorCode(orderHealthError)",
      "delivery email health summary failed",
      'error_code: "delivery_email_health_summary_failed"',
      "database_code: stableDatabaseErrorCode(deliveryEmailHealthError)",
      "staleProcessing",
      "oldestCreatedAt",
      "oldestDeliveredAt",
      "newestUpdatedAt",
      "retry_watch",
      "emailState",
      "missing",
      "queued",
      '"Cache-Control": "no-store"',
      "feedback_summary_unavailable",
    ],
    excludes: [
      "stripe_session_id",
      "stripe_payment_intent",
      "guest_email",
      "user_id",
      "input_payload",
      "response_payload",
      "order_id",
      "notes",
      "latestNote",
      "message: error.message",
      "code: error.code",
      "message: orderHealthError.message",
      "code: orderHealthError.code",
      "message: deliveryEmailHealthError.message",
      "code: deliveryEmailHealthError.code",
      "order feedback summary failed:",
      "order health summary failed:",
      "delivery email health summary failed:",
    ],
  },
  {
    name: "internal order feedback runbook explains safe quality triage",
    file: "docs/order-feedback-quality-runbook.md",
    includes: [
      "Fizetős olvasatok minőségi visszajelzésének runbookja",
      "ORDER_FEEDBACK_SUMMARY_SECRET",
      "GET /api/internal/order-feedback/summary?days=30&staleProcessingMinutes=15",
      "Authorization: Bearer <ORDER_FEEDBACK_SUMMARY_SECRET>",
      "reviewPriority",
      "reviewRecommendation",
      "orderHealth",
      "deliveryEmailHealth",
      "staleProcessingMinutes",
      "order_health_summary_unavailable",
      "delivery_email_health_summary_unavailable",
      "manual_review_first",
      "read_feedback_details",
      "watch_next_orders",
      "retry_watch",
      "failed",
      "processing",
      "errorCode",
      "express",
      "queued",
      "missing",
      "negativeDetailCount",
      "nem adhat vissza",
      "rendelésazonosítót",
      "Stripe azonosítót",
      "email címet",
      "teljes olvasati szöveget",
      "nyers ügyfélmegjegyzést",
      "ne a felhasználó személyes történetét másold promptba",
      "accurate",
    ],
  },
  {
    name: "delivered email exposes recovery path",
    file: "src/lib/email-templates/order-delivered.tsx",
    includes: [
      "isGuest?: boolean",
      "isGuest = false",
      "const accessIntro = isGuest",
      "ezen a biztonságos linken és a profilodban is eléred",
      "Ha az emailt később keresed vissza",
      "accessMeta",
      "Rendelés: {shortOrderId}",
      "missingBodyText",
      "SITE_LEGAL.supportEmail",
      "Ha a gomb nem nyílik meg",
      "orderSupportMailto({ productName, shortOrderId })",
      "function orderSupportMailto",
      "Segítséget szeretnék kérni a megrendelt olvasatom megnyitásához.",
      "A vásárlási email címem:",
      "Mi történt röviden:",
      "Rendelés rövid azonosítója",
      "orderId.slice(0, 8)",
      "Vendégvásárlásnál",
      "linket érdemes megtartanod",
      "biztonságos rendelési link a legfontosabb hozzáférés",
      "létrehozása nem kötelező",
      "ezen a biztonságos rendelési linken éred el",
      "ki is másolhatod",
      "letöltheted magadnak",
      "szöveges fájlként",
      "A részletes olvasatot ezen a linken és a profilodban is eléred",
      "Minőségi visszajelzés",
      "Hasznos volt",
      "Részben volt hasznos",
      "mit pontosítanék vagy tennék hozzá",
      "Pontosítást kérek",
      'feedbackValue: "accurate"',
      'feedbackValue: "partial"',
      'feedbackValue: "missed"',
      "feedbackAccessUrl(openUrl, option.feedbackValue)",
      "function feedbackAccessUrl",
      'url.searchParams.set("feedback", feedback)',
      "feedbackMailto",
      "emailben is elküldheted",
      "Röviden ezt szeretném hozzátenni:",
      "Ami kapcsolódott a helyzetemhez:",
      "Amit szeretnék pontosítani:",
      "A helyzetemből ezt érdemes még hozzátenni:",
      "A saját helyzetemből ezt érdemes még figyelembe venni:",
      "Ebben az irányban kérnék finomítást:",
      "pontosítási vázlattal",
      "mit érdemes még hozzátenni",
      "mit pontosítanál",
      "Nem kell a teljes olvasatot bemásolni",
      "elég megírni, mi kapcsolódott",
      "isGuest: true",
    ],
    excludes: [
      "Vendég vásárlás",
      "Eltalált",
      "Részben talált",
      "Ami nem volt elég pontos:",
      "Ezt a részt szeretném finomítani:",
      "A helyzetemből ez maradt ki:",
      "Ebben az irányban kérek pontosítást:",
      "Melyik részt szeretném finomítani?",
      "melyik részt érdemes tovább finomítani",
      "Mi az a konkrét helyzet",
      "Milyen irányban várnék pontosítást?",
    ],
  },
  {
    name: "order processing passes guest state into delivered email",
    file: "src/lib/orderProcessing.server.ts",
    includes: [
      'templateName: "order-delivered"',
      "guestEmail: string | null",
      "isGuest: Boolean(order.guestEmail)",
      "accessUrl: order.stripeSessionId",
    ],
  },
  {
    name: "order delivered email still queues if delivery email state migration is pending",
    file: "src/lib/orderProcessing.server.ts",
    includes: [
      "let canPersistDeliveryEmailState = true",
      "isMissingColumnError(stateError)",
      "canPersistDeliveryEmailState = false",
      "queueing delivered email without state claim",
      "if (canPersistDeliveryEmailState)",
      "function isMissingColumnError",
      "column .* does not exist",
      "Could not find .* column",
    ],
  },
  {
    name: "internal transactional email uses stable message ids for idempotent order emails",
    file: "src/lib/email/sendTransactional.server.ts",
    includes: [
      "const idempotencyKey = input.idempotencyKey ?? crypto.randomUUID()",
      "const messageId = idempotencyKey",
      "metadata: {",
      "idempotency_key: idempotencyKey",
      "message_id: messageId",
    ],
  },
  {
    name: "order delivered email is essential transactional",
    file: "src/lib/email-templates/registry.ts",
    includes: ["essentialTransactional?: boolean", "essentialTransactional: true"],
  },
  {
    name: "internal order delivery bypasses unsubscribe suppression only",
    file: "src/lib/email/sendTransactional.server.ts",
    includes: [
      "const essentialTransactional = Boolean(template.essentialTransactional)",
      'suppressed.reason !== "unsubscribe"',
      "if (!essentialTransactional)",
      "...(unsubscribeToken ? { unsubscribe_token: unsubscribeToken } : {})",
    ],
  },
  {
    name: "lovable send route preserves essential order email delivery",
    file: "src/routes/lovable/email/transactional/send.ts",
    includes: [
      "const essentialTransactional = Boolean(template.essentialTransactional)",
      'suppressed.reason !== "unsubscribe"',
      "if (!essentialTransactional)",
      "...(unsubscribeToken ? { unsubscribe_token: unsubscribeToken } : {})",
    ],
  },
  {
    name: "lovable send route stores stable email log error codes",
    file: "src/routes/lovable/email/transactional/send.ts",
    includes: [
      "type TransactionalSendErrorCode",
      '"unsubscribe_token_lookup_failed"',
      '"unsubscribe_token_create_failed"',
      '"unsubscribe_token_confirm_failed"',
      '"email_suppression_missing"',
      '"email_enqueue_failed"',
      "function redactStableMessageId",
      'error_code: "unsubscribe_token_lookup_failed"',
      'error_code: "unsubscribe_token_create_failed"',
      'error_code: "unsubscribe_token_confirm_failed"',
      'error_code: "email_enqueue_failed"',
      "message_id_redacted: redactStableMessageId(messageId)",
    ],
    excludes: [
      'error_message: "Failed to look up unsubscribe token"',
      'error_message: "Failed to create unsubscribe token"',
      'error_message: "Failed to confirm unsubscribe token storage"',
      'error_message: "Unsubscribe token used but email missing from suppressed list"',
      'error_message: "Failed to enqueue email"',
      "error: tokenLookupError",
      "error: tokenError",
      "error: reReadError",
      "error: enqueueError",
    ],
  },
  {
    name: "unsubscribe page clarifies transactional order notices",
    file: "src/routes/unsubscribe.tsx",
    includes: [
      "nem kötelező emailekről",
      "Rendeléshez kapcsolódó",
      "kézbesítési vagy ügyfélszolgálati értesítés",
      "rendelési értesítéseket",
      "továbbra",
    ],
  },
  {
    name: "order reconciliation migration exists",
    file: "supabase/migrations/20260609143000_order_payment_reconciliation.sql",
    includes: ["stripe_environment TEXT", "payment_rechecked_at TIMESTAMPTZ"],
  },
];

const failed: string[] = [];

for (const check of checks) {
  const body = readFileSync(check.file, "utf8");
  const missing = check.includes.filter((needle) => !body.includes(needle));
  if (missing.length) failed.push(`${check.name}: missing ${missing.join(", ")}`);
  const forbidden = check.enforceExcludes
    ? (check.excludes?.filter((needle) => body.includes(needle)) ?? [])
    : [];
  if (forbidden.length) failed.push(`${check.name}: forbidden ${forbidden.join(", ")}`);
}

if (failed.length) {
  console.error("Order experience audit failed:");
  for (const item of failed) console.error(`- ${item}`);
  process.exit(1);
}

console.log(`Order experience audit passed: ${checks.length} checks.`);
