import { readFileSync } from "node:fs";

type Check = {
  name: string;
  file: string;
  includes: string[];
};

const checks: Check[] = [
  {
    name: "profile clears account and browser memory together",
    file: "src/routes/profil.tsx",
    includes: [
      "clearMyReadingMemories",
      "clearGuestPersonalization",
      "ebből a fiókból és ebből a böngészőből",
      "Töröltük az olvasati memóriát a fiókodból és a helyi böngészőmintát",
    ],
  },
  {
    name: "profile imports guest memory into account after login",
    file: "src/routes/profil.tsx",
    includes: [
      "getGuestReadingMemoriesForAccountImport",
      "importGuestReadingMemories",
      "const importGuestMemories = useServerFn(importGuestReadingMemories)",
      "guestImportAttempted",
      "const guestMemories = guestImportAttempted.current",
      "await importGuestMemories({ data: { memories: guestMemories } })",
      "clearGuestPersonalization()",
      "setGuestImportCount(imported.imported)",
      "Áthoztuk a belépés előtti helyi olvasati mintáidat a profilodba",
      "nem indulnak újra idegenként",
    ],
  },
  {
    name: "server can import guest memories into authenticated account safely",
    file: "src/lib/readingMemory.functions.ts",
    includes: [
      "const ImportGuestMemoryInput",
      "export const importGuestReadingMemories",
      ".middleware([requireSupabaseAuth])",
      ".inputValidator(ImportGuestMemoryInput.parse)",
      ".max(20)",
      "user_id: context.userId",
      "imported_from_guest_browser: true",
      "guest_created_at: memory.createdAt ?? null",
      "return { ok: true, imported: memories.length }",
    ],
  },
  {
    name: "profile explains memory scope gently",
    file: "src/routes/profil.tsx",
    includes: [
      "Itt csak rövid olvasati mintákat őrzünk",
      "nem készítünk belőle biztos jövőállítást",
      "profilt",
      "legfeljebb 180 napig",
      "Később itt látod",
      "milyen témához térsz vissza újra",
      "Miben segít?",
      "nem idegenként indul",
      "Nem készítünk belőle személyiségprofilt",
      "A törlés nem érinti a rendelési előzményeket",
    ],
  },
  {
    name: "profile turns memory insights into gentle next actions",
    file: "src/routes/profil.tsx",
    includes: [
      "MemoryNextSteps",
      "MemoryHistoryItem",
      "memoryContinuation",
      "memoryNextStepItems",
      "Következő jó kérdés",
      "nem kell újra nulláról indulnod",
      "Folytasd innen",
      "Kapcsolati dinamika folytatása",
      "Döntés újranézése",
      "Álom továbbfejtése",
      "Számmisztikai ív mélyítése",
      "Időszakos térkép folytatása",
      "Három lapos folytatás",
      "több ember|több összeill|választási minta|több kapcsolat",
      "Kapcsolati mintázat tisztázása",
      "milyen biztonságot vagy visszajelzést keresel újra több kapcsolatban",
      "Kapcsolati dinamika",
      'to: "/osszeillunk"',
      "Döntés előtt",
      'to: "/dontes-elott"',
      "Három lap",
      'to: "/harom-lap"',
      "Mai iránytű",
      'to: "/mai-iranytu"',
      "30 napos térkép",
      'to: "/szemelyes-30-napos-horoszkop"',
      "ha nem napi jegyszöveg kell",
    ],
  },
  {
    name: "empty profile offers a deeper astrology entry path",
    file: "src/routes/profil.tsx",
    includes: [
      "Születési képlet",
      'to: "/szuletesi-keplet"',
      "mélyebb személyes alapot",
      "későbbi 30 napos vagy éves térkép",
      "Képlet megnézése",
    ],
  },
  {
    name: "privacy page exposes guest memory clearing",
    file: "src/routes/adatkezelesi-tajekoztato.tsx",
    includes: [
      "hasGuestPersonalizationDecision",
      "clearGuestPersonalization",
      "setGuestPersonalizationEnabled",
      "Helyi olvasati minta törlése",
      "Helyi személyesítés kikapcsolása",
      "Helyi személyesítés visszakapcsolása",
      "csak akkor indul el, ha ebben a böngészőben bekapcsolod",
      "localStorage-ban és",
      "cookie-jelzésben",
      "legfeljebb 180 napig használjuk",
    ],
  },
  {
    name: "guest personalization clears and expires local and cookie signals",
    file: "src/lib/guestReadingMemory.ts",
    includes: [
      "const ACCEPTED_KEY =",
      "const DISABLED_KEY =",
      "export function isGuestPersonalizationEnabled",
      "loadLocal<boolean>(ACCEPTED_KEY) === true",
      "export function hasGuestPersonalizationDecision",
      "export function setGuestPersonalizationEnabled",
      "saveLocal(ACCEPTED_KEY, enabled)",
      "if (!isGuestPersonalizationEnabled()) return",
      "const RETENTION_DAYS = 180",
      "new Date(row.createdAt).getTime() >= cutoff",
      "window.localStorage.removeItem(`jovod:${KEY}`)",
      "deleteCookie(COOKIE_TOTAL_KEY)",
      "deleteCookie(COMPATIBILITY_COUNT_KEY)",
      "deleteCookie(COMPATIBILITY_STATUS_KEY)",
      "export function getGuestReadingMemoriesForAccountImport",
      "return readAll().slice(0, 20)",
    ],
  },
  {
    name: "guest memory builds a real returning-user arc",
    file: "src/lib/guestReadingMemory.ts",
    includes: [
      "export type GuestReadingInsights",
      "weeklySummary",
      "monthlySummary",
      "recurringQuestion",
      "changeSinceLast",
      "gentleNudge",
      "Miben kérdezel újra",
      "Múltkorihoz képest",
    ],
  },
  {
    name: "account memory keeps a cross-reading returning-user arc",
    file: "src/lib/readingMemory.functions.ts",
    includes: [
      "function prioritizeMemories",
      "const relevant = memories.filter((memory) => topicMatches(memory, input))",
      "const source = relevant.length ? relevant : memories",
      "a.reading_type === input.readingType",
      ".limit(Math.max((data.limit ?? 8) * 4, 16))",
      "Finom irány: ${insights.gentleNudge}",
    ],
  },
  {
    name: "guest compatibility pattern is tracked before signup",
    file: "src/lib/guestReadingMemory.ts",
    includes: [
      "distinctCompatibilityTopics(rows, 30)",
      "saveLocal(",
      "COMPATIBILITY_KEY",
      "saveCookie(COMPATIBILITY_COUNT_KEY",
      "saveCookie(COMPATIBILITY_STATUS_KEY",
      "Több emberrel is megnézted az összeillést",
    ],
  },
  {
    name: "guest memory notice is visible and controllable",
    file: "src/components/GuestMemoryNotice.tsx",
    includes: [
      "guest_reading_memory_count",
      "hasGuestPersonalizationDecision",
      "needsDecision",
      "clearGuestPersonalization",
      "setGuestPersonalizationEnabled",
      "ne minden alkalom",
      "idegenként induljon",
      "A minta helyben marad ebben a böngészőben",
      "készítünk belőle biztos jövőállítást",
      "A személyesítés nem kötelező",
      "a törlés nem érinti a rendeléseidet",
      "Bekapcsolom",
      "Most nem",
      "Később az adatkezelési oldalon bármikor visszakapcsolhatod",
      "Helyi minta törlése",
      "Személyesítés kikapcsolása",
      "Új vendégmintát nem mentünk",
      "Adatkezelés",
      "guest_memory_notice_dismissed",
    ],
  },
  {
    name: "guest memory insight panel shows returning-user arc gently",
    file: "src/components/GuestMemoryInsightPanel.tsx",
    includes: [
      "getGuestReadingContext",
      "setGuestPersonalizationEnabled",
      "context.memories.length < 2",
      "Ismétlődő mintád",
      "insights.recurringQuestion",
      "insights.changeSinceLast",
      "distinctCompatibilityCount >= 3",
      "Csak ebben a böngészőben tárolt",
      "Beállítások",
      "clearGuestPersonalization",
      "Helyi minta törlése",
      "Személyesítés kikapcsolása",
      "Új vendégmintát nem mentünk",
      "adatkezelési oldalon",
    ],
  },
  {
    name: "layout mounts guest memory notice",
    file: "src/components/Layout.tsx",
    includes: ["GuestMemoryNotice", "<GuestMemoryNotice />"],
  },
  {
    name: "key reading pages surface guest memory insight panel",
    file: "src/routes/osszeillunk.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      'readingType="compatibility"',
      "topic={q || status}",
      "topic: q || status",
      "situation={status}",
      'id="compat-question"',
      "question: q.trim() || undefined",
      "question: q.trim() ||",
      "question={",
      "q.trim() ||",
      "q,",
    ],
  },
  {
    name: "tarot relationship pages surface guest memory insight panel",
    file: "src/routes/randi-elott.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      'readingType="love"',
      "topic={q || sit}",
      "situation={sit}",
    ],
  },
  {
    name: "decision and three-card pages surface guest memory insight panel",
    file: "src/routes/dontes-elott.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      'readingType="decision"',
      "topic={q || cat}",
      "situation={cat}",
    ],
  },
  {
    name: "three-card page surfaces guest memory insight panel",
    file: "src/routes/harom-lap.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      'readingType="tarot"',
      "topic={question || category}",
      "situation={category}",
    ],
  },
  {
    name: "daily card page records explicit revealed draw safely",
    file: "src/routes/mai-lap.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      "recordGuestReadingMemory",
      "rememberDailyCard",
      "rememberedDrawKeyRef",
      'readingType: "tarot"',
      'topic: "mai lap"',
      'sourceRoute: "/mai-lap"',
      'readingType="tarot"',
      'topic="mai lap"',
      "setRevealed(false)",
    ],
  },
  {
    name: "dream page surfaces guest memory insight panel",
    file: "src/routes/alomfejtes.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      'readingType="dream"',
      "topic={result?.title || text}",
      "situation={emotion}",
    ],
  },
  {
    name: "angel number page records and surfaces guest memory",
    file: "src/routes/angyalszam.index.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      "recordGuestReadingMemory",
      'readingType: "angel"',
      'sourceRoute: "/angyalszam"',
      'readingType="angel"',
      "topic={m?.number}",
      "Milyen helyzetben láttad?",
      "angelSituationReflection",
      "situation.trim() || m?.meaning.title",
      "question: situation.trim() || undefined",
      "situation: situation.trim() || meaning.title",
      "inputPayload={",
      "number: m.number",
      "angel_number_completed",
    ],
  },
  {
    name: "crystal page records only explicit guest interest",
    file: "src/routes/kristaly.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      "recordGuestReadingMemory",
      'readingType: "crystal"',
      'sourceRoute: "/kristaly"',
      "rememberCrystalReading",
      "load({ remember = false }",
      "load({ remember: true })",
      'readingType="crystal"',
      "topic={r?.name}",
      "situation={crystalTopic(mode, month, sign)}",
    ],
  },
  {
    name: "home daily compass uses and records returning-user context",
    file: "src/components/PersonalDailyBriefing.tsx",
    includes: [
      "getGuestReadingContext",
      "recordGuestReadingMemory",
      "memoryContext",
      'readingType: "daily_compass"',
      'topic: "mai iránytű"',
    ],
  },
  {
    name: "daily compass route records and surfaces guest memory",
    file: "src/routes/mai-iranytu.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      "recordGuestReadingMemory",
      "rememberDailyCompass",
      'readingType: "daily_compass"',
      'sourceRoute: "/mai-iranytu"',
      'topic: "mai iránytű"',
      'readingType="daily_compass"',
      'topic="mai iránytű"',
      "Mi foglalkoztat ma?",
      "dailyFocusReflection",
      "question: focus.trim() || undefined",
      "situation: focus.trim() || signName",
      "A mai fókuszod",
      "situation: focus.trim() || undefined",
      "question: focus.trim() || undefined",
      "daily_compass_completed",
    ],
  },
  {
    name: "numerology page records safe explicit guest memory",
    file: "src/routes/szammisztika.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      "recordGuestReadingMemory",
      "rememberNumerologyReading",
      'readingType: "numerology"',
      'sourceRoute: "/szammisztika"',
      "fetchReading(dob, name, callName, true)",
      'readingType="numerology"',
      "profile.lifePathNumber",
      "profile.personalYearNumber",
      "Születésnap száma:",
      "Személyes hónap:",
    ],
  },
  {
    name: "horoscope paid entries carry returning-user context",
    file: "src/routes/horoszkop.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      "getGuestReadingContext",
      "openPersonalHoroscopePaywall",
      'readingType: "horoscope"',
      'readingType="horoscope"',
      "horoscopeSituation",
      "memoryContext",
      'productSlug="horoszkop_szemelyre"',
    ],
  },
  {
    name: "horoscope article paid CTA carries returning-user context",
    file: "src/routes/horoszkop.$period.$sign.tsx",
    includes: [
      "GuestMemoryInsightPanel",
      "getGuestReadingContext",
      "openPersonalHoroscopePaywall",
      'readingType: "horoscope"',
      'readingType="horoscope"',
      "articleSituation",
      "memoryContext",
      'productSlug="horoszkop_szemelyre"',
    ],
  },
  {
    name: "compatibility fallback memory reflects status and repeated comparisons",
    file: "src/routes/osszeillunk.tsx",
    includes: [
      "function compatibilityMemorySentence",
      "Több emberrel is megnézted az összeillést",
      "Visszatérő történetnél nem csak az számít",
      "ismerkedésnél a kezdeti vonzalom",
      "relationshipNumber: fallbackProfile.relationshipNumber",
      "summary: `${fallbackReading.oneSentence} ${memorySentence}`",
      "oneSentence: memorySentence",
    ],
  },
  {
    name: "compatibility cached AI reading still returns display profile",
    file: "src/lib/readingQuality/functions.ts",
    includes: [
      "const localProfile = calculateCompatibilityProfile",
      "const compatHit = await readCachedReading(compatCacheKey)",
      "profile: localProfile",
      "...localProfile",
    ],
  },
  {
    name: "server daily briefing can personalize from memory without exposing it",
    file: "src/lib/roxy.functions.ts",
    includes: [
      "memoryContext: z.string().max(1600).optional()",
      "felhasznaloiIv",
      "hasMemoryContext",
      "Ne nevezd memóriának",
      "memoryKey",
    ],
  },
];

const failed: string[] = [];

for (const check of checks) {
  const body = readFileSync(check.file, "utf8");
  const missing = check.includes.filter((needle) => !body.includes(needle));
  if (missing.length) failed.push(`${check.name}: missing ${missing.join(", ")}`);
}

if (failed.length) {
  console.error("Memory experience audit failed:");
  for (const item of failed) console.error(`- ${item}`);
  process.exit(1);
}

console.log(`Memory experience audit passed: ${checks.length} checks.`);
