import { readFileSync } from "node:fs";

type Check = {
  name: string;
  file: string;
  includes: string[];
};

const checks: Check[] = [
  {
    name: "checkout stores source route",
    file: "src/lib/payments.functions.ts",
    includes: ["source_route: data.sourceRoute ?? null", "stripe_environment: data.environment"],
  },
  {
    name: "checkout survives pending migration",
    file: "src/lib/payments.functions.ts",
    includes: [
      "insertOrderWithMigrationFallback",
      "isMissingColumnError",
      "inserting order without fallback fields",
    ],
  },
  {
    name: "pending payment can be reconciled server-side",
    file: "src/lib/payments.functions.ts",
    includes: [
      "PAYMENT_RECHECK_INTERVAL_MS",
      "reconcilePendingPayment",
      "ORDER_SELECT_BASE",
      "stripe.checkout.sessions.retrieve(sessionId)",
      "session.payment_status",
    ],
  },
  {
    name: "webhook marks payment recheck state",
    file: "src/routes/api/public/payments/webhook.ts",
    includes: ["payment_rechecked_at: new Date().toISOString()"],
  },
  {
    name: "webhook survives pending reconciliation migration",
    file: "src/routes/api/public/payments/webhook.ts",
    includes: [
      "isMissingColumnError",
      "orders reconciliation columns unavailable in webhook",
      "fallbackPaidUpdate",
      "_stripePaymentIntent",
      "_paymentRecheckedAt",
    ],
  },
  {
    name: "webhook stores stable payment failure codes",
    file: "src/routes/api/public/payments/webhook.ts",
    includes: [
      "type PaymentFailureCode",
      '"stripe_async_payment_failed"',
      '"stripe_checkout_expired"',
      "function paymentFailureCode",
      "error_message: paymentFailureCode(event.type)",
    ],
    excludes: ["error_message: event.type"],
  },
  {
    name: "thank-you page can read source route",
    file: "src/lib/payments.functions.ts",
    includes: ["ORDER_SELECT_BASE", "created_at", "guest_email", "source_route"],
  },
  {
    name: "paid memory keeps source route",
    file: "src/lib/orderProcessing.server.ts",
    includes: [
      "source_route, response_payload",
      "source_route: order.source_route",
      "memorySituation(order.input_payload)",
      "data.category ?? data.situation",
      '"situation"',
      "ORDER_PROCESSING_RETRY_AFTER_MS",
      "PROCESSING_RETRY_AFTER_MS",
    ],
  },
  {
    name: "thank-you page exposes continuation CTA",
    file: "src/routes/koszonjuk.tsx",
    includes: ["Innen folytathatod", "Vissza az olvasathoz"],
  },
  {
    name: "thank-you page exposes support contact",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "SupportContact",
      "supportMailto(shortId)",
      "Jövőd.hu rendelési segítség",
      "A vásárlási email címem:",
      "Mi történt röviden:",
      "SITE_LEGAL.supportEmail",
      "Ügyfélszolgálat",
    ],
  },
  {
    name: "thank-you page reassures when delivered email delivery needs attention",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      'delivery_email_status?: "queued" | "attention_needed" | null',
      'order.delivery_email_status === "attention_needed"',
      "DeliveryEmailNotice",
      "Email kézbesítés",
      "Az olvasatod már elkészült",
      "innen biztonságosan elérhető",
      "SupportContact",
    ],
    excludes: ["delivery_email_error", "delivery_email_queued_at"],
  },
  {
    name: "thank-you page distinguishes instant and detailed paid preparation",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "orderPreparationLead",
      "orderPreparationDetail",
      "nem egy rövid automata választ",
      "több szakaszban dolgozzuk össze",
      "pár percig hagyd nyitva",
      "biztonságos rendelési linket érdemes megtartanod",
    ],
  },
  {
    name: "thank-you page exposes a short order reference",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "function shortOrderId",
      "Rendelés:",
      "shortOrderId(order.id)",
      "add meg ezt",
      "rövid rendelésazonosítót",
    ],
  },
  {
    name: "thank-you page reassures when long polling stops",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "pollingPaused",
      "MAX_ATTEMPTS",
      "setPollingPaused(true)",
      "OrderPollingPaused",
      "Hosszabb ellenőrzés alatt",
      "a rendelésed nem tűnt el",
      "Frissíts rá később erre az oldalra",
      "rövid rendelésazonosítót",
    ],
  },
  {
    name: "thank-you page keeps polling when the order row is initially missing",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "orderLookupPending",
      "setOrderLookupPending(true)",
      "if (!r.order)",
      "setTimeout(tick, 2500)",
      "Fizetés egyeztetése",
      "most összekapcsoljuk a vásárlásoddal",
      "amint az egyeztetés lezárul",
      "a rendelés nem vész el",
      "frissíts rá később erre a teljes linkre",
    ],
    excludes: [
      "keressük hozzá a rendelési sort",
      "rendelésállapot beért",
      "fizetési szolgáltató gyorsabban",
    ],
  },
  {
    name: "profile prefers stored source route",
    file: "src/routes/profil.tsx",
    includes: ["source_route?: string | null", "o.source_route ?? PRODUCTS_BY_SLUG"],
  },
  {
    name: "profile can wake paid or processing orders without exposing session ids",
    file: "src/routes/profil.tsx",
    includes: [
      "processMyOrder",
      "const wakeOrder = useServerFn(processMyOrder)",
      "awakenedOrders",
      'order.status === "paid" || order.status === "processing"',
      "wakeOrder({ data: { orderId: order.id } })",
      "const refreshed = await call({})",
    ],
  },
  {
    name: "profile claims verified guest orders after login",
    file: "src/lib/payments.functions.ts",
    includes: [
      "claimGuestOrdersForAuthenticatedUser",
      "emailFromAuthClaims(context.claims)",
      "normalizeClaimEmail",
      "CLAIMABLE_GUEST_ORDER_STATUSES",
      "claimedGuestOrderCount",
      "supabaseAdmin",
      '.is("user_id", null)',
      '.ilike("guest_email", email)',
      '.in("status", [...CLAIMABLE_GUEST_ORDER_STATUSES])',
      '.from("order_feedback")',
      '.in("order_id", claimedIds)',
      '.is("user_id", null)',
    ],
    excludes: ["stripe_session_id: sessionId", "stripe_payment_intent: paymentIntent"],
  },
  {
    name: "profile tells users when guest purchases were attached",
    file: "src/routes/profil.tsx",
    includes: [
      "claimedGuestOrderCount",
      "setClaimedGuestOrderCount",
      "r.claimedGuestOrderCount",
      "Áthoztuk",
      "korábbi vendégvásárlásodat ebbe a profilba",
      "ugyanazzal az email címmel jelentkeztél be",
      "A biztonságos rendelési linkek továbbra",
    ],
  },
  {
    name: "profile lets customers retry failed paid reading processing safely",
    file: "src/routes/profil.tsx",
    includes: [
      "retryingOrders",
      "retryNotices",
      "type RetryNotice",
      "async function retryOrder",
      "wakeOrder({ data: { orderId } })",
      "OrderRetryNotice",
      "Most nem sikerült újraindítani a feldolgozást",
      "Feldolgozás újrapróbálása",
      "akkor engedjük, ha a fizetés igazoltan sikeres",
      "Újrapróbálás…",
      "retrying={retryingOrders.has(o.id)}",
      "onRetry={() => retryOrder(o.id)}",
    ],
  },
  {
    name: "thank-you page lets guest customers retry failed processing safely",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "retryingFailedOrder",
      "retryNotice",
      "async function retryFailedOrder",
      "paid_order_retry_clicked",
      "runProcess({ data: { sessionId: session_id } })",
      "const refreshed = await fetchOrder",
      "Feldolgozás újrapróbálása",
      "akkor engedjük, ha a fizetés igazoltan sikeres",
      "Ha az újrapróbálás sem rendezi",
      "A rendelés nem vész el",
      "shortOrderId(order.id)",
    ],
  },
  {
    name: "profile order wakeup is server-side and strips private payment fields",
    file: "src/lib/payments.functions.ts",
    includes: [
      "ORDER_SELECT_PROFILE_WITH_RECONCILIATION",
      "ORDER_SELECT_WITH_DELIVERY_STATE",
      "stripe_session_id",
      "delivery_email_queued_at",
      "delivery_email_error",
      "reconcilePendingPayment(order, sessionId)",
      "export const processMyOrder",
      '.eq("user_id", context.userId)',
      "processPaidOrderBySession(order.stripe_session_id)",
      "safeOrderProcessingResult",
      "ORDER_PROCESSING_GENERIC_ERROR",
      "function stripPrivateOrderFields",
      "function publicDeliveryEmailStatus",
      "delivery_email_status: publicDeliveryEmailStatus(order)",
      '"attention_needed"',
      "function sanitizePublicResponsePayload",
      "raw: _raw",
      "generation: rawGeneration",
      "publicPayload.generation",
      'generation.source === "ai"',
      'generation.source === "local_premium_draft"',
      "qualityRejected: generation.qualityRejected === true",
      "qualityIssues: Array.isArray(generation.qualityIssues)",
      "response_payload: sanitizePublicResponsePayload(publicOrder.response_payload)",
      "_stripeSessionId",
      "_deliveryEmailQueuedAt",
      "_deliveryEmailError",
      "reconciled.map(stripPrivateOrderFields)",
    ],
    excludes: [
      "provider: generation.provider",
      "model: generation.model",
      "latencyMs: generation.latencyMs",
    ],
  },
  {
    name: "paid order generation failures store safe codes, not raw exception text",
    file: "src/lib/orderProcessing.server.ts",
    includes: [
      "PUBLIC_ORDER_PROCESSING_ERROR",
      "ORDER_GENERATION_FAILED_CODE",
      '"paid_reading_generation_failed"',
      "paid order processing failed",
      "error_message: ORDER_GENERATION_FAILED_CODE",
      "return { ok: false, error: PUBLIC_ORDER_PROCESSING_ERROR }",
    ],
    excludes: [
      "error_message: message",
      "return { ok: false, error: message }",
      '.update({ status: "failed", error_message: message })',
    ],
  },
  {
    name: "delivered order email failures store safe codes, not raw provider errors",
    file: "src/lib/orderProcessing.server.ts",
    includes: [
      "delivery_email_error: result.error",
      'delivery_email_error: "delivery_email_exception"',
      "order delivered email queue failed:",
    ],
    excludes: ["delivery_email_error: result.error.slice", "delivery_email_error: message.slice"],
  },
  {
    name: "email queue stores stable error codes, not raw provider messages",
    file: "src/routes/lovable/email/queue/process.ts",
    includes: [
      "type EmailQueueErrorCode",
      "'email_send_failed'",
      "'email_send_rate_limited'",
      "'email_send_forbidden'",
      "'email_send_ttl_exceeded'",
      "'email_send_retry_exhausted'",
      "function emailQueueErrorCode",
      "error_message: emailQueueErrorCode(error)",
      "moveToDlq(supabase, queue, msg, 'email_send_ttl_exceeded')",
      "moveToDlq(supabase, queue, msg, 'email_send_retry_exhausted')",
      "moveToDlq(supabase, queue, msg, 'email_send_forbidden')",
    ],
    excludes: [
      "error_message: errorMsg.slice",
      "await moveToDlq(supabase, queue, msg, errorMsg",
      "await moveToDlq(supabase, queue, msg, `TTL exceeded",
      "await moveToDlq(supabase, queue, msg, `Max retries",
    ],
  },
  {
    name: "transactional email helper returns stable error codes",
    file: "src/lib/email/sendTransactional.server.ts",
    includes: [
      "export type TransactionalEmailError",
      '"unknown_template"',
      '"missing_recipient_email"',
      '"email_suppressed"',
      '"unsubscribe_token_unavailable"',
      '"email_queue_unavailable"',
      'error_message: "email_queue_unavailable"',
      "recipient_redacted: redactEmail",
    ],
    excludes: [
      "`Unknown template: ${input.templateName}`",
      '"recipientEmail required"',
      "`unsubscribe token: ${tokErr.message}`",
      "return { ok: false, error: enqErr.message }",
      "error_message: `enqueue: ${enqErr.message}`",
    ],
  },
  {
    name: "failed order retry verifies Stripe payment before resetting processing",
    file: "src/lib/payments.functions.ts",
    includes: [
      'order.status === "failed"',
      "prepareFailedOrderRetry",
      "stripe.checkout.sessions.retrieve(order.stripe_session_id)",
      'session.payment_status !== "paid" && session.status !== "complete"',
      'status: "paid"',
      "error_message: null",
      '.eq("status", "failed")',
      "export const processOrder",
      '.eq("stripe_session_id", data.sessionId)',
      'if (order?.status === "failed")',
      "prepareFailedOrderRetry(supabaseAdmin, order)",
    ],
  },
  {
    name: "profile explains paid order status",
    file: "src/routes/profil.tsx",
    includes: [
      "OrderStatusNote",
      "A fizetés állapotát még egyeztetjük",
      "csak a fizetési visszajelzésre várunk",
      "Az olvasat készül",
      "A feldolgozás elakadt",
      "kézzel elkészítjük az",
      "visszatérítjük",
      "SITE_LEGAL.supportEmail",
    ],
  },
  {
    name: "profile distinguishes instant and detailed paid preparation",
    file: "src/routes/profil.tsx",
    includes: [
      "profileOrderPreparationLead",
      "profileOrderPreparationDetail",
      "nem azonnali sablonválasz",
      "több szakaszos elemzés",
      "Az azonnali termékek általában pár percen belül",
      "ha az email késik, a profilban akkor is",
    ],
  },
  {
    name: "profile exposes support contact for stuck orders",
    file: "src/routes/profil.tsx",
    includes: [
      "function shortOrderId",
      "Rendelés:",
      "shortOrderId(o.id)",
      "ProfileSupportContact",
      "profileSupportMailto(shortId)",
      "href={profileSupportMailto(shortId)}",
      "Jövőd.hu rendelési segítség",
      "A vásárlási email címem:",
      "Mi történt röviden:",
      "Ha továbbra is így marad",
      "vásárlási email címedről",
      "Add meg ezt is",
      "Az olvasat elkészült, de itt nem tudjuk teljes szövegként megjeleníteni",
      "SITE_LEGAL.supportEmail",
    ],
  },
  {
    name: "profile reassures when delivered email delivery needs attention",
    file: "src/routes/profil.tsx",
    includes: [
      'delivery_email_status?: "queued" | "attention_needed" | null',
      'o.delivery_email_status === "attention_needed"',
      "ProfileDeliveryEmailNotice",
      "Az olvasat elkészült és itt a profilban megnyitható",
      "profilnézet marad a biztos hozzáférésed",
      "ProfileSupportContact",
    ],
    excludes: ["delivery_email_error", "delivery_email_queued_at"],
  },
  {
    name: "paid reading body can be copied or downloaded for later use",
    file: "src/components/PaidReadingBody.tsx",
    includes: [
      "navigator.clipboard.writeText",
      "URL.createObjectURL",
      "URL.revokeObjectURL",
      'type: "text/plain;charset=utf-8"',
      "formatDownloadedReading(body, { title, productName, orderReference })",
      "function formatDownloadedReading",
      "Jövőd.hu",
      "Személyes olvasat",
      "Termék:",
      "Rendelés:",
      "Letöltve:",
      "szimbolikus, önismereti digitális tartalom",
      "SITE_LEGAL.supportEmail",
      "link.download",
      "jovod-olvasat-",
      "Olvasat másolása",
      "Kimásolva",
      "Olvasat letöltése",
      "Letöltés indult",
      "később is visszanézheted",
      "kimásolhatod vagy letöltheted",
      "Mentéskor a fájl tartalmazza a címet",
      "ReadingUseGuide",
      "ReadingSelfCheck",
      "ReadingAssuranceNotice",
      "paidReadingSelfCheck",
      "paidReadingAssurance",
      "PaidReadingGenerationPublic",
      "selfCheckReadingType",
      "selfCheckItems",
      "Minőségbiztosítás",
      "Ellenőrzött, óvatosan szerkesztett olvasat",
      "konkrétan a rendelésedhez és a megadott helyzetedhez kell kapcsolódnia",
      "Rendelés alapján visszanézhető olvasat",
      "a kártyákból, számokból vagy horoszkópjelekből indul ki",
      "generation?: PaidReadingGenerationPublic",
      "Pontosítás, ha valami kimaradt",
      "Pontosítási vázlat másolása",
      "Jövőd.hu pontosítási kérés",
      "Ami talált:",
      "Ami túl általános vagy pontatlan volt:",
      "A helyzetemből ez maradt ki:",
      "Ebben az irányban kérek pontosítást:",
      "Akkor hasznos, ha az olvasat jó irányba indult",
      "Nem állít biztos jövőt",
      "nem ígér visszatérést",
      "Olvasási iránytű",
      "Először azt a mondatot keresd",
      "Olvasd vissza azt a részt",
      "7 nap múlva",
      "melyik téma tért vissza azóta",
      "következő jó kérdés",
      "sm:grid-cols-2 lg:grid-cols-4",
      "mi maradt ki a helyzetedből",
      "milyen irányban vársz pontosítást",
      "visszaviszed a saját helyzetedbe",
      "Ha az olvasat valamelyik része félrement",
      "mailto:${SITE_LEGAL.supportEmail}",
      "rendelésazonosítóval gyorsabban visszanézzük",
    ],
    excludes: [
      "Az első változat nem ment át",
      "belső ellenőrzésen",
      "Szerkesztett biztonsági változat",
      "biztonsági változat",
    ],
  },
  {
    name: "delivered thank-you page asks for quality feedback safely",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "PaidReadingFeedback",
      "feedback?: FeedbackValue",
      "normalizeFeedbackSearch",
      "emailFeedback={feedback}",
      "emailFeedbackHandled",
      "FEEDBACK_OPTIONS",
      "PaidReadingGenerationPublic",
      "generation?: PaidReadingGenerationPublic",
      "generation={payload.generation}",
      "submitOrderFeedbackBySession",
      "Minőségi visszajelzés",
      "Eltalált",
      "Részben talált",
      "Nem volt elég pontos",
      "paid_reading_feedback_clicked",
      "saved: true",
      'source: "thank_you"',
      "!emailFeedback ||",
      "void saveFeedback(option)",
      "order.feedback ?? null",
      "Köszönjük, mentettük a visszajelzést",
      "feedbackNote",
      "Mi maradt ki?",
      "maxLength={600}",
      "Pontosítás mentése",
      "Inkább emailben írom le",
      "note: note?.trim()",
      "feedbackMailto",
      "note: feedbackNote",
      "note?: string",
      "opts.note === \"string\"",
      "opts.note.trim().slice(0, 600)",
      "Rendelés:",
      "Termék:",
      "Melyik rész nem talált?",
      "Mi az a konkrét helyzet",
      "Milyen irányban várnék pontosítást?",
      "konkrét pontosítási kéréssel",
      "olvasat teljes szövegét nem tesszük bele automatikusan",
      "Nem kell a teljes olvasatot bemásolni",
      "elég azt a részt vagy érzést megírni",
      "SITE_LEGAL.supportEmail",
    ],
  },
  {
    name: "profile delivered reading asks for quality feedback safely",
    file: "src/routes/profil.tsx",
    includes: [
      "PaidReadingGenerationPublic",
      "generation?: PaidReadingGenerationPublic",
      "generation={payload.generation}",
      "data.generation as PaidReadingGenerationPublic",
      "ProfilePaidReadingFeedback",
      "submitMyOrderFeedback",
      "Minőségi visszajelzés",
      "Eltalált",
      "Részben talált",
      "Nem volt elég pontos",
      "paid_reading_feedback_clicked",
      "saved: true",
      'source: "profile"',
      "order.feedback ?? null",
      "Köszönjük, mentettük a visszajelzést",
      "feedbackNote",
      "Mi maradt ki?",
      "maxLength={600}",
      "Pontosítás mentése",
      "Inkább emailben írom le",
      "note: note?.trim()",
      "profileFeedbackMailto",
      "note: feedbackNote",
      "note?: string",
      "opts.note === \"string\"",
      "opts.note.trim().slice(0, 600)",
      "Rendelés:",
      "Termék:",
      "Melyik rész nem talált?",
      "Mi az a konkrét helyzet",
      "Milyen irányban várnék pontosítást?",
      "konkrét pontosítási kéréssel",
      "olvasat teljes szövegét nem tesszük bele automatikusan",
      "Nem kell a teljes olvasatot bemásolni",
      "elég azt a részt vagy érzést megírni",
      "SITE_LEGAL.supportEmail",
    ],
  },
  {
    name: "paid reading feedback is persisted without Stripe or full reading leakage",
    file: "src/lib/payments.functions.ts",
    includes: [
      "type OrderFeedbackValue",
      "const FEEDBACK_VALUES",
      "function normalizeOrderFeedback",
      "function normalizeFeedbackNote",
      "attachOrderFeedback",
      "attachOrdersFeedback",
      '.select("order_id, feedback")',
      "export const submitOrderFeedbackBySession",
      '.eq("stripe_session_id", data.sessionId)',
      'order.status !== "delivered"',
      '.from("order_feedback").upsert',
      'source: "thank_you"',
      "export const submitMyOrderFeedback",
      ".middleware([requireSupabaseAuth])",
      '.eq("user_id", context.userId)',
      'source: "profile"',
    ],
  },
  {
    name: "order feedback migration keeps customer signals private",
    file: "supabase/migrations/20260616163000_order_feedback.sql",
    includes: [
      "CREATE TABLE IF NOT EXISTS public.order_feedback",
      "feedback TEXT NOT NULL CHECK",
      "source TEXT NOT NULL CHECK",
      "UNIQUE (order_id)",
      "ALTER TABLE public.order_feedback ENABLE ROW LEVEL SECURITY",
      "Order feedback selectable by owner",
      "Order feedback insertable by order owner",
      "Order feedback updatable by order owner",
      "GRANT ALL ON public.order_feedback TO service_role",
      "trg_order_feedback_updated",
    ],
    excludes: ["stripe_session_id", "response_payload"],
  },
  {
    name: "order feedback table exists in generated supabase types",
    file: "src/integrations/supabase/types.ts",
    includes: [
      "order_feedback: {",
      'feedback: "accurate" | "partial" | "missed"',
      'source: "thank_you" | "profile"',
      "order_feedback_order_id_fkey",
      'referencedRelation: "orders"',
    ],
  },
  {
    name: "internal order feedback summary is protected and aggregate-only",
    file: "src/routes/api/internal/order-feedback/summary.ts",
    includes: [
      'createFileRoute("/api/internal/order-feedback/summary")',
      "ORDER_FEEDBACK_SUMMARY_SECRET",
      "SUPABASE_SERVICE_ROLE_KEY",
      "Authorization",
      "Bearer ",
      'return Response.json({ ok: false, error: "unauthorized" }, { status: 401 })',
      "function summarizeRows",
      "ProductFeedbackSummary",
      "type OrderHealthRow",
      "type OrderHealthSummary",
      "type DeliveryEmailState",
      "type DeliveryEmailHealthRow",
      "type DeliveryEmailHealthSummary",
      "missRate",
      "detailCount",
      "negativeDetailCount",
      "detailRate",
      "needsAttention",
      "ReviewPriority",
      "reviewPriorityFor",
      "reviewRecommendation",
      "manual_review_first",
      "read_feedback_details",
      "watch_next_orders",
      "reviewPriorityCounts",
      "ATTENTION_MIN_TOTAL",
      "ATTENTION_MISS_RATE",
      "LEGACY_BUTTON_NOTES",
      "function hasWrittenDetail",
      "function parseStaleProcessingMinutes",
      "function normalizeOrderHealthErrorCode",
      "function normalizeDeliveryEmailErrorCode",
      "function deliveryEmailState",
      "internal_error",
      "function summarizeOrderHealth",
      "function summarizeDeliveryEmailHealth",
      "DEFAULT_STALE_PROCESSING_MINUTES",
      "MAX_STALE_PROCESSING_MINUTES",
      '.select("product_slug, product_name, feedback, source, note, created_at")',
      '.from("orders")',
      "product_slug, product_name, category, status, error_message, express, created_at, updated_at",
      '.in("status", ["failed", "processing", "paid"])',
      "product_slug, product_name, category, delivery_email_error, delivery_email_queued_at, delivered_at, created_at, updated_at",
      '.eq("status", "delivered")',
      '.gte("delivered_at", since)',
      "needsAttentionCount",
      "staleProcessingMinutes",
      "orderHealth",
      "deliveryEmailHealth",
      "order_health_summary_unavailable",
      "delivery_email_health_summary_unavailable",
      "staleProcessing",
      "oldestCreatedAt",
      "oldestDeliveredAt",
      "newestUpdatedAt",
      "retry_watch",
      "emailState",
      "missing",
      "queued",
      '"Cache-Control": "no-store"',
      "feedback_summary_unavailable",
    ],
    excludes: [
      "stripe_session_id",
      "stripe_payment_intent",
      "guest_email",
      "user_id",
      "input_payload",
      "response_payload",
      "order_id",
      "notes",
      "latestNote",
    ],
  },
  {
    name: "internal order feedback runbook explains safe quality triage",
    file: "docs/order-feedback-quality-runbook.md",
    includes: [
      "Fizetős olvasatok minőségi visszajelzésének runbookja",
      "ORDER_FEEDBACK_SUMMARY_SECRET",
      "GET /api/internal/order-feedback/summary?days=30&staleProcessingMinutes=15",
      "Authorization: Bearer <ORDER_FEEDBACK_SUMMARY_SECRET>",
      "reviewPriority",
      "reviewRecommendation",
      "orderHealth",
      "deliveryEmailHealth",
      "staleProcessingMinutes",
      "order_health_summary_unavailable",
      "delivery_email_health_summary_unavailable",
      "manual_review_first",
      "read_feedback_details",
      "watch_next_orders",
      "retry_watch",
      "failed",
      "processing",
      "errorCode",
      "express",
      "queued",
      "missing",
      "negativeDetailCount",
      "nem adhat vissza",
      "rendelésazonosítót",
      "Stripe azonosítót",
      "email címet",
      "teljes olvasati szöveget",
      "nyers ügyfélmegjegyzést",
      "ne a felhasználó személyes történetét másold promptba",
      "accurate",
    ],
  },
  {
    name: "delivered email exposes recovery path",
    file: "src/lib/email-templates/order-delivered.tsx",
    includes: [
      "isGuest?: boolean",
      "isGuest = false",
      "const accessIntro = isGuest",
      "ezen a biztonságos linken és a profilodban is eléred",
      "Ha az emailt később keresed vissza",
      "accessMeta",
      "Rendelés: {shortOrderId}",
      "missingBodyText",
      "SITE_LEGAL.supportEmail",
      "Ha a gomb nem nyílik meg",
      "orderSupportMailto({ productName, shortOrderId })",
      "function orderSupportMailto",
      "Segítséget szeretnék kérni a megrendelt olvasatom megnyitásához.",
      "A vásárlási email címem:",
      "Mi történt röviden:",
      "Rendelés rövid azonosítója",
      "orderId.slice(0, 8)",
      "Vendégvásárlásnál",
      "linket érdemes megtartanod",
      "biztonságos rendelési link a legfontosabb hozzáférés",
      "létrehozása nem kötelező",
      "ezen a biztonságos rendelési linken éred el",
      "ki is másolhatod",
      "letöltheted magadnak",
      "szöveges fájlként",
      "A részletes olvasatot ezen a linken és a profilodban is eléred",
      "Minőségi visszajelzés",
      "Eltalált",
      "Részben talált",
      "Nem volt elég pontos",
      "feedbackValue: \"accurate\"",
      "feedbackValue: \"partial\"",
      "feedbackValue: \"missed\"",
      "feedbackAccessUrl(openUrl, option.feedbackValue)",
      "function feedbackAccessUrl",
      "url.searchParams.set(\"feedback\", feedback)",
      "feedbackMailto",
      "emailben is elküldheted",
      "Röviden ezt szeretném hozzátenni:",
      "Melyik rész nem talált?",
      "Mi az a konkrét helyzet",
      "Milyen irányban várnék pontosítást?",
      "konkrét pontosítási kéréssel",
      "visszanézzük, és konkrét pontosítási kéréssel",
      "Nem kell a teljes olvasatot bemásolni",
      "elég azt a részt vagy érzést megírni",
      "isGuest: true",
    ],
    excludes: ["Vendég vásárlás"],
  },
  {
    name: "order processing passes guest state into delivered email",
    file: "src/lib/orderProcessing.server.ts",
    includes: [
      'templateName: "order-delivered"',
      "guestEmail: string | null",
      "isGuest: Boolean(order.guestEmail)",
      "accessUrl: order.stripeSessionId",
    ],
  },
  {
    name: "order delivered email still queues if delivery email state migration is pending",
    file: "src/lib/orderProcessing.server.ts",
    includes: [
      "let canPersistDeliveryEmailState = true",
      "isMissingColumnError(stateError)",
      "canPersistDeliveryEmailState = false",
      "queueing delivered email without state claim",
      "if (canPersistDeliveryEmailState)",
      "function isMissingColumnError",
      "column .* does not exist",
      "Could not find .* column",
    ],
  },
  {
    name: "internal transactional email uses stable message ids for idempotent order emails",
    file: "src/lib/email/sendTransactional.server.ts",
    includes: [
      "const idempotencyKey = input.idempotencyKey ?? crypto.randomUUID()",
      "const messageId = idempotencyKey",
      "metadata: {",
      "idempotency_key: idempotencyKey",
      "message_id: messageId",
    ],
  },
  {
    name: "order delivered email is essential transactional",
    file: "src/lib/email-templates/registry.ts",
    includes: ["essentialTransactional?: boolean", "essentialTransactional: true"],
  },
  {
    name: "internal order delivery bypasses unsubscribe suppression only",
    file: "src/lib/email/sendTransactional.server.ts",
    includes: [
      "const essentialTransactional = Boolean(template.essentialTransactional)",
      'suppressed.reason !== "unsubscribe"',
      "if (!essentialTransactional)",
      "...(unsubscribeToken ? { unsubscribe_token: unsubscribeToken } : {})",
    ],
  },
  {
    name: "lovable send route preserves essential order email delivery",
    file: "src/routes/lovable/email/transactional/send.ts",
    includes: [
      "const essentialTransactional = Boolean(template.essentialTransactional)",
      'suppressed.reason !== "unsubscribe"',
      "if (!essentialTransactional)",
      "...(unsubscribeToken ? { unsubscribe_token: unsubscribeToken } : {})",
    ],
  },
  {
    name: "lovable send route stores stable email log error codes",
    file: "src/routes/lovable/email/transactional/send.ts",
    includes: [
      "type TransactionalSendErrorCode",
      '"unsubscribe_token_lookup_failed"',
      '"unsubscribe_token_create_failed"',
      '"unsubscribe_token_confirm_failed"',
      '"email_suppression_missing"',
      '"email_enqueue_failed"',
    ],
    excludes: [
      'error_message: "Failed to look up unsubscribe token"',
      'error_message: "Failed to create unsubscribe token"',
      'error_message: "Failed to confirm unsubscribe token storage"',
      'error_message: "Unsubscribe token used but email missing from suppressed list"',
      'error_message: "Failed to enqueue email"',
    ],
  },
  {
    name: "unsubscribe page clarifies transactional order notices",
    file: "src/routes/unsubscribe.tsx",
    includes: [
      "nem kötelező emailekről",
      "Rendeléshez kapcsolódó",
      "kézbesítési vagy ügyfélszolgálati értesítés",
      "rendelési értesítéseket",
      "továbbra",
    ],
  },
  {
    name: "order reconciliation migration exists",
    file: "supabase/migrations/20260609143000_order_payment_reconciliation.sql",
    includes: ["stripe_environment TEXT", "payment_rechecked_at TIMESTAMPTZ"],
  },
];

const failed: string[] = [];

for (const check of checks) {
  const body = readFileSync(check.file, "utf8");
  const missing = check.includes.filter((needle) => !body.includes(needle));
  if (missing.length) failed.push(`${check.name}: missing ${missing.join(", ")}`);
}

if (failed.length) {
  console.error("Order experience audit failed:");
  for (const item of failed) console.error(`- ${item}`);
  process.exit(1);
}

console.log(`Order experience audit passed: ${checks.length} checks.`);
