import { readFileSync } from "node:fs";

type Check = {
  name: string;
  file: string;
  includes: string[];
  excludes?: string[];
};

const checks: Check[] = [
  {
    name: "support email is centralized through legal config",
    file: "src/components/PaidReadingBody.tsx",
    includes: ["SITE_LEGAL.supportEmail", "`Kapcsolat: ${SITE_LEGAL.supportEmail}`"],
    excludes: ["hello@jovod.hu", "hello@jovod.hu"],
  },
  {
    name: "homepage explains free entry, paid price floor, and safe access",
    file: "src/routes/index.tsx",
    includes: [
      "const SITE_URL = SITE_LEGAL.siteUrl",
      'links: [{ rel: "canonical", href: SITE_URL }]',
      "ENTRY_PRICE",
      "formatHuf(ENTRY_PRICE)",
      "Kezdj ingyenesen",
      "Fizetős olvasatok",
      "Biztonságos hozzáférés",
      "A rövid olvasatok ingyen is elindíthatók első tájékozódásként",
      "kötött irányt kérsz",
      "rejtett díj nélkül",
      "A kártyaadatot Stripe kezeli",
      "profilban is",
      "Miért személyesebb?",
      "A kérdésedből, a jelekből és a visszatérő mintáidból indul",
      "Konkrét helyzet",
      "Hagyományos jelképek",
      "nagy hagyományú, történeti jelképrendszereit",
      "népi megfigyeléseit józan, mai nyelven olvassuk",
      "Visszatérő ív",
      "Opcionális, törölhető",
      "csak finomabb folytatást ad",
      "Minőségi korlát",
      "Kipróbálom ingyen",
      "Személyes olvasatok",
    ],
    excludes: ["biztosan", "garantáltan", "mindenképpen"],
  },
  {
    name: "pricing FAQ frames readings through tradition, not machinery",
    file: "src/routes/arak.tsx",
    includes: [
      "Ezek jóslatok?",
      "nagy hagyományú, történeti jelképrendszerekből",
      "népi megfigyelésekből indul",
      "nem biztos jövőként",
      "önismereti olvasatként kezeljük",
    ],
    excludes: ["Roxy", "API", "provider", "lefordít", "fordítjuk"],
  },
  {
    name: "homepage personal briefing failure keeps trust and next action",
    file: "src/components/PersonalDailyBriefing.tsx",
    includes: [
      "A mai személyes összefoglaló most nem állt össze elég tisztán",
      "A lapod megmaradt",
      "fizetés nem indult",
      "félkész olvasatot nem mentettünk",
      "Újrapróbálom az összefoglalót",
      "Inkább kérek személyes olvasatot erre a lapra",
      "setPaywallOpen(true)",
    ],
    excludes: ["Most nem tudtam összeállítani a mai olvasatot"],
  },
  {
    name: "root head does not force homepage canonical onto every route",
    file: "src/routes/__root.tsx",
    includes: ["BRAND_OG_IMAGE_URL", 'rel: "manifest"', "Organization", "WebSite"],
    excludes: ['{ rel: "canonical", href: SITE_URL }'],
  },
  {
    name: "root route errors use localized UI and redacted console logs",
    file: "src/routes/__root.tsx",
    includes: [
      "function ErrorComponent",
      "Ez az oldal most nem töltött be",
      "Valami megakadt nálunk",
      "A rendelésed vagy olvasatod ettől nem vész el",
      "Újrapróbálom",
      "vásárlási email címedről",
      "SITE_LEGAL.supportEmail",
      "mailto:${SITE_LEGAL.supportEmail}",
      "reportLovableError(error",
      "Root route error",
      'error_code: "root_route_error"',
    ],
    excludes: [
      "console.error(error)",
      "error.message",
      "error.stack",
      "Valami technikai hiba",
      "Something went wrong",
    ],
    excludes: ["Először próbáld ki", "Ha betalál a hang"],
  },
  {
    name: "profile access is visible in main and mobile navigation",
    file: "src/components/Layout.tsx",
    includes: ['to="/profil"', "Profil", "Profil és előzmények", "hidden lg:flex", "lg:hidden"],
  },
  {
    name: "private and transactional pages are kept out of search index",
    file: "src/routes/profil.tsx",
    includes: ['{ name: "robots", content: "noindex,nofollow" }'],
  },
  {
    name: "thank-you page with order access is kept out of search index",
    file: "src/routes/koszonjuk.tsx",
    includes: ['{ name: "robots", content: "noindex,nofollow" }'],
  },
  {
    name: "login page does not dilute public search appearance",
    file: "src/routes/bejelentkezes.tsx",
    includes: ['{ name: "robots", content: "noindex,follow" }'],
  },
  {
    name: "global footer exposes support contact from legal config",
    file: "src/components/Layout.tsx",
    includes: [
      "SITE_LEGAL.supportEmail",
      "Rendeléssel vagy hozzáféréssel kapcsolatban",
      "mailto:${SITE_LEGAL.supportEmail}",
    ],
  },
  {
    name: "about page builds trust before paid use",
    file: "src/routes/rolunk.tsx",
    includes: [
      "href: `${SITE_LEGAL.siteUrl}/rolunk`",
      "Egy csendes magyar rituálé",
      "hagyományos jelképrendszerekből induló, rövid és személyes önismereti olvasatokat ad",
      "magyar nyelvű, hagyományalapú önismereti olvasatokat ad",
      "Milyen hagyományból indul?",
      "régi jelképrendszerekből indulnak",
      "a tarot képeiből",
      "időminőségekből",
      "a számmisztika mintáiból",
      "népi megfigyelésekből",
      "használható önismereti kapaszkodót",
      "A fizetést Stripe dolgozza fel",
      "bankkártyaadatot nem tárolunk",
      "biztonságos rendelési linken és emailben",
      "szimbólumaiból indulnak",
      "adataidhoz és helyzetedhez kapcsolódnak",
      'to="/arak"',
      "SITE_LEGAL.operator.name",
      "SITE_LEGAL.operator.registeredOffice",
      "SITE_LEGAL.operator.companyRegistrationNumber",
      "SITE_LEGAL.operator.taxNumber",
      "mailto:${SITE_LEGAL.supportEmail}",
      "nem szakmai döntéshelyettesítő",
    ],
    excludes: [
      "garantáltan",
      "mindenképpen",
      "biztosan",
      "Évtizedes szimbólumismeret",
      "természetes magyar nyelven",
      "közérthető",
      "önismereti és szórakoztató platform",
      "szórakoztató platform",
      "jóslatgyár",
    ],
  },
  {
    name: "privacy notice explains paid reading feedback data",
    file: "src/routes/adatkezelesi-tajekoztato.tsx",
    includes: [
      "minőségi visszajelzést és opcionális rövid pontosítást",
      "Minőségi visszajelzés fizetős olvasatoknál",
      "az olvasat hasznos volt",
      "részben volt hasznos",
      "pontosítást kérsz",
      "kapcsolódott a helyzetedhez",
      "részt finomítanád",
      "kizárólag ügyfélszolgálati",
      "hibajavítási",
      "szolgáltatásminőségi célra",
      "nem helyettesíti a",
      "panaszt vagy",
      "ügyfélszolgálati kérést",
      "rendelési",
      "adatokkal együtt őrizhetjük meg",
    ],
    excludes: ["teljes olvasatot automatikusan"],
  },
  {
    name: "privacy notice explains guest order profile attachment",
    file: "src/routes/adatkezelesi-tajekoztato.tsx",
    includes: [
      "Vendégvásárlások és profil",
      "Vendégként is vásárolhatsz",
      "biztonságos rendelési linkhez kapcsoljuk",
      "ugyanazzal az igazolt email címmel jelentkezel be",
      "gazdátlan",
      "vendégvásárlásaidat a profilodhoz",
      "nem indít új fizetést",
      "nem érinti a Stripe által",
      "bankkártyaadatokat",
      "A biztonságos rendelési link ilyenkor is működik",
      "csak azonos email cím",
      "ügyfélszolgálatához és minőségi visszajelzéséhez",
    ],
    excludes: ["automatikusan minden rendelést"],
  },
  {
    name: "terms explain paid reading feedback expectations",
    file: "src/routes/aszf.tsx",
    includes: [
      "Minőségi visszajelzés",
      "mennyire volt hasznos",
      "kapcsolódott-e a helyzetedhez",
      "mi maradt ki a helyzetedből",
      "szolgáltatás javítására",
      "ügyfélszolgálati ellenőrzésre",
      "rendelési azonosítóval együtt",
    ],
    excludes: ["garantált javítás", "automatikus visszatérítés", "mennyire talált"],
  },
  {
    name: "terms explain safe digital fulfillment support path",
    file: "src/routes/aszf.tsx",
    includes: [
      "A digitális olvasatok elkészítése a sikeres fizetés után indul el",
      "a rendelési oldalon vagy a felhasználói profilban érhető el",
      "Vendégvásárlásnál",
      "fizetés utáni rendelési linket",
      "vásárláshoz használt email címet",
      "az elkészült olvasat a profilban is",
      "visszanézhető",
      "nem nyílik meg",
      "nem hozzáférhető",
      "hibásan jelenik meg",
      "rövid rendelésazonosító alapján",
      "pótoljuk a hozzáférést",
      "javítjuk a hibás megjelenítést",
      "újraküldjük az olvasatot",
      "emailes értesítés melyik ponton akadt el",
    ],
    excludes: [
      "garantáltan pótoljuk",
      "feltétel nélkül visszatérítjük",
      "automatikusan készülnek el",
    ],
    excludes: ["az olvasat eltalált", "részben talált"],
  },
  {
    name: "mobile bottom navigation gives direct profile access",
    file: "src/components/BottomNav.tsx",
    includes: ['to: "/profil"', 'label: "Profil"', "M5 21a7 7 0 0 1 14 0"],
  },
  {
    name: "login page never displays raw auth provider errors",
    file: "src/routes/bejelentkezes.tsx",
    includes: [
      "const normalizedEmail = normalizeAuthEmail(email)",
      "email: normalizedEmail",
      "onBlur={() => setEmail(normalizeAuthEmail(email))}",
      "function normalizeAuthEmail",
      'value.trim().toLocaleLowerCase("hu-HU")',
      "safeAuthErrorMessage(e, mode)",
      "function safeAuthErrorMessage",
      "useAuthModeSwitch",
      "setErr(null)",
      "setMsg(null)",
      "switchAuthMode",
      "Megerősítő emailt küldtünk",
      "ha vendégként vásároltál",
      "ugyanazzal az email címmel tudjuk a korábbi rendeléseidet",
      "A biztonságos rendelési linkjeid addig is működnek",
      "Google",
      "Apple",
      "a korábbi rendeléseid nem vesznek el",
      "A korábbi rendeléseid nem vesznek el",
      "biztonságos rendelési linkjeid továbbra is működnek",
      "authSupportMailto",
      "Jövőd.hu bejelentkezési segítség",
      "Segítséget szeretnék kérni a bejelentkezéshez.",
      "Ha vendégként vásároltam, a vásárlási email címem:",
      'aria-live="polite"',
      'role="status"',
      "rounded-md border border-gold/15 bg-gold/[0.06]",
      "invalid login",
      "email not confirmed",
      "already registered",
      "Túl sok próbálkozás történt",
      "SITE_LEGAL.supportEmail",
      "Segítünk.",
    ],
    excludes: [
      'setErr(e instanceof Error ? e.message : "Hiba történt.")',
      "Bejelentkezés sikertelen. Próbáld újra.",
      "text-red-300",
    ],
  },
  {
    name: "login page explains profile value without implying a new payment",
    file: "src/routes/bejelentkezes.tsx",
    includes: [
      "Miért érdemes belépni?",
      "Vendégvásárlás után",
      "ugyanazzal az igazolt email címmel",
      "korábbi vendégvásárlásaidat át tudjuk hozni ebbe a profilba",
      "új",
      "fizetés nélkül",
      "A fizetés utáni biztonságos rendelési link ilyenkor is működik",
      "kényelmesebb helyre gyűjti az elkészült olvasatokat és állapotokat",
      "korábbi fizetős olvasataidat",
      "rendelési állapotaidat",
      "személyes memória",
      "visszatérő témáidra",
      "ingyenes",
      "nem indít új fizetést",
      "Vendégként is működik",
      "egyben látod az olvasataidat és a visszatérő ívedet",
    ],
    excludes: ["kötelező", "bankkártya szükséges"],
  },
  {
    name: "checkout start failures reassure customers and give a manual support path",
    file: "src/components/StripeEmbeddedCheckout.tsx",
    includes: [
      "A fizetés most nem nyílt meg",
      "Kártyaadat ilyenkor nem jut el hozzánk",
      "indítsd újra nyugodtan",
      "vásárlási email címedről",
      "a választott olvasatot és a hozzáférést rendelés előtt is segítünk rendezni",
      "checkoutSupportMailto",
      "Jövőd.hu fizetési segítség",
      "isLoggedIn: Boolean(userId)",
      "Fizetési próbálkozás:",
      'aria-live="polite"',
      'role="status"',
      "Újrapróbálom",
    ],
    excludes: [
      "Nem jött vissza checkout azonosító",
      "próbáld újra pár perc múlva",
      "Nem indult el a fizetés",
    ],
  },
  {
    name: "paywall blocker avoids a technical dead end when checkout cannot start",
    file: "src/components/PaywallDialog.tsx",
    includes: [
      "A fizetés indításához most segítség kell",
      "Kártyaadat ilyenkor nem jut el hozzánk",
      "vásárlási email címedről",
      "a választott olvasatot rendelés előtt segítünk rendezni",
    ],
    excludes: [
      "technikai segítség kell",
      "kézzel is utánanézünk a rendelésnek",
      "kézzel is segítünk elindítani a rendelést",
    ],
  },
  {
    name: "profile load failures are visible and safe",
    file: "src/routes/profil.tsx",
    includes: [
      "ordersError",
      "memoryError",
      "ProfileLoadError",
      "profileLoadErrorMailto",
      "A rendelési előzményeket most nem tudtuk betölteni",
      "A rendeléseid ettől nem vesznek el",
      "Az olvasati memóriát most nem tudtuk betölteni",
      "Ez nem érinti a rendeléseidet",
      "Rendelési előzmény segítség",
      "Memória betöltési segítség",
      "Segítséget szeretnék kérni a profilom betöltéséhez.",
      "SITE_LEGAL.supportEmail",
    ],
    excludes: [
      "loadOrders().catch(() => setOrdersLoading(false))",
      "loadAndImportMemory().catch(() => setMemoriesLoading(false))",
      "setOrdersError(e instanceof Error ? e.message",
      "setMemoryError(e instanceof Error ? e.message",
    ],
  },
  {
    name: "empty profile gives a useful first journey instead of a dead end",
    file: "src/routes/profil.tsx",
    includes: [
      "ProfileStarterActions",
      "Hogyan induljon az íved?",
      "Gyors első jel",
      "Kapcsolati kérdés",
      "Döntés előtt",
      'to: "/mai-lap"',
      'to: "/osszeillunk"',
      'to: "/dontes-elott"',
      'to="/arak"',
      "Még nincs vásárlásod. Kezdhetsz ingyenes olvasattal",
      "Minden fizetős olvasat és ár áttekintése",
    ],
    excludes: ["Még nincs vásárlásod. <Link"],
  },
  {
    name: "thank-you page never displays raw order status errors",
    file: "src/routes/koszonjuk.tsx",
    includes: [
      "Hiányzik a rendelési azonosító",
      "nem a fizetés utáni teljes visszatérési link",
      "kapott teljes köszönőoldali linket",
      "Vendégvásárlásnál a vásárlási email cím a legfontosabb azonosító",
      'to="/profil"',
      'to="/arak"',
      "safeOrderStatusErrorMessage(e)",
      "function safeOrderStatusErrorMessage",
      "function OrderPreparationTimeline",
      "Mi történik most?",
      "most összekapcsoljuk a vásárlásoddal",
      "amint az egyeztetés lezárul",
      "A fizetés megérkezett, a kérdésedet és a megadott adatokat rögzítettük.",
      "Az azonnali olvasat általában pár percen belül megjelenik ezen az oldalon.",
      "ez a biztonságos rendelési link akkor is a közvetlen hozzáférésed marad",
      "Rendelés egyeztetése",
      "A fizetésed ettől nem vész el",
      "rendelés nem található",
      "A rendelés nem vész el",
      "A rendelés állapota most nem frissült",
      "vásárlási email címedről",
      "Ellenőrizd, hogy a fizetés utáni teljes linket nyitottad-e meg",
    ],
    excludes: [
      'setErr(e instanceof Error ? e.message : "Hiba")',
      "Kapcsolódási hiba",
      "állapotlekérés",
      "keressük hozzá a rendelési sort",
      "rendelésállapot beért",
      "fizetési szolgáltató gyorsabban",
    ],
  },
  {
    name: "unsubscribe endpoint never logs raw unsubscribe tokens",
    file: "src/routes/email/unsubscribe.ts",
    includes: [
      "function redactToken",
      "function stableErrorCode",
      'error_code: "unsubscribe_token_mark_used_failed"',
      'error_code: "unsubscribe_email_suppression_failed"',
      "database_code: stableErrorCode(updateError)",
      "database_code: stableErrorCode(suppressError)",
      "token_redacted: redactToken(token)",
      "email_redacted: redactEmail(tokenRecord.email)",
    ],
    excludes: [
      'console.error("Failed to mark token as used", { error: updateError, token })',
      "error: updateError,\n            token_redacted",
      "error: suppressError,\n            email_redacted",
    ],
  },
  {
    name: "unsubscribe endpoint returns localized public errors",
    file: "src/routes/email/unsubscribe.ts",
    includes: [
      "PUBLIC_UNSUBSCRIBE_ERROR",
      "MISSING_UNSUBSCRIBE_TOKEN",
      "INVALID_UNSUBSCRIBE_LINK",
      "function unsubscribeError",
      "A leiratkozási kérést most nem tudtuk feldolgozni",
      "A leiratkozási linkből hiányzik a biztonságos ellenőrző rész",
      "Nyisd meg az emailben kapott teljes linket",
      "Ez a leiratkozási link érvénytelen vagy lejárt.",
    ],
    excludes: [
      "Hiányzó leiratkozási azonosító.",
      'Response.json({ error: "Server configuration error" }',
      'Response.json({ error: "Token is required" }',
      'Response.json({ error: "Invalid or expired token" }',
      'Response.json({ error: "Failed to process unsubscribe" }',
    ],
  },
  {
    name: "unsubscribe page error state offers support instead of a dead end",
    file: "src/routes/unsubscribe.tsx",
    includes: [
      "SITE_LEGAL.supportEmail",
      "A leiratkozási kérést most nem tudtuk végigellenőrizni",
      "Frissíts rá pár perc múlva",
      "Jövőd.hu leiratkozási segítség",
      "mailto:${SITE_LEGAL.supportEmail}",
    ],
    excludes: ["Valami megakadt. Kérlek próbáld újra később."],
  },
  {
    name: "Lovable suppression webhook returns localized public errors",
    file: "src/routes/lovable/email/suppression.ts",
    includes: [
      "PUBLIC_EMAIL_WEBHOOK_ERROR",
      "PUBLIC_EMAIL_WEBHOOK_AUTH_ERROR",
      "PUBLIC_EMAIL_WEBHOOK_PAYLOAD_ERROR",
      "function publicEmailWebhookError",
      "Az email eseményt most nem tudtuk feldolgozni",
      "Nincs jogosultság az email esemény feldolgozásához.",
      "Az email esemény adatai hiányosak vagy hibásak.",
    ],
    excludes: [
      'Response.json({ error: "Server configuration error" }',
      'Response.json({ error: "Invalid signature" }',
      'Response.json({ error: "Stale timestamp" }',
      'Response.json({ error: "Invalid payload" }',
      'Response.json({ error: "Verification failed" }',
      'Response.json({ error: "Internal error" }',
      'Response.json({ error: "Failed to write suppression" }',
    ],
  },
  {
    name: "Lovable suppression webhook stores stable email log error codes",
    file: "src/routes/lovable/email/suppression.ts",
    includes: [
      "type SuppressionLogErrorCode",
      "function mapReasonToLogCode",
      '"email_bounced"',
      '"email_complained"',
      '"email_unsubscribed"',
      '"email_suppressed"',
      "const sendLogMessage = mapReasonToLogCode(payload.reason)",
      "error_message: sendLogMessage",
    ],
    excludes: [
      "Permanent bounce",
      "Spam complaint",
      "Recipient unsubscribed",
      "Email suppressed",
      "function mapReasonToMessage",
    ],
  },
  {
    name: "Lovable suppression webhook redacts operational logs",
    file: "src/routes/lovable/email/suppression.ts",
    includes: [
      "function redactEmail",
      "function redactMessageId",
      'error_code: "email_webhook_configuration_missing"',
      'error_code: "email_webhook_invalid_signature"',
      'error_code: "email_webhook_stale_timestamp"',
      'error_code: "email_webhook_invalid_payload"',
      'error_code: "email_webhook_verification_failed"',
      'error_code: "email_webhook_verification_exception"',
      'error_code: "email_suppression_upsert_failed"',
      'error_code: "email_send_log_insert_failed"',
      "email_redacted: redactEmail(normalizedEmail)",
      "message_id_redacted: redactMessageId(payload.message_id)",
    ],
    excludes: [
      "Missing required environment variables",
      "Invalid webhook signature",
      "Stale webhook timestamp",
      'console.error("Invalid payload", { code: error.code })',
      "message: error.message",
      "{ error }",
      "error: suppressError,\n            email_redacted",
      "error: insertError,\n          }",
      'normalizedEmail[0] + "***@" + normalizedEmail.split("@")[1]',
    ],
  },
  {
    name: "Lovable transactional preview returns localized public errors",
    file: "src/routes/lovable/email/transactional/preview.ts",
    includes: [
      "PUBLIC_EMAIL_PREVIEW_ERROR",
      "PUBLIC_EMAIL_PREVIEW_AUTH_ERROR",
      "function publicEmailPreviewError",
      "Az email előnézetet most nem tudtuk elkészíteni",
      "Nincs jogosultság az email előnézet megnyitásához.",
      "errorMessage: PUBLIC_EMAIL_PREVIEW_ERROR",
    ],
    excludes: [
      'Response.json({ error: "Server configuration error" }',
      'Response.json({ error: "Unauthorized" }',
      "errorMessage: err instanceof Error ? err.message : String(err)",
    ],
  },
  {
    name: "Lovable transactional send returns localized public errors",
    file: "src/routes/lovable/email/transactional/send.ts",
    includes: [
      "PUBLIC_EMAIL_SEND_ERROR",
      "PUBLIC_EMAIL_SEND_AUTH_ERROR",
      "PUBLIC_EMAIL_SEND_PAYLOAD_ERROR",
      "function publicEmailSendError",
      "function redactStableMessageId",
      'error_code: "suppression_check_failed"',
      'error_code: "unsubscribe_token_lookup_failed"',
      'error_code: "unsubscribe_token_create_failed"',
      'error_code: "unsubscribe_token_confirm_failed"',
      'error_code: "email_enqueue_failed"',
      "message_id_redacted: redactStableMessageId(messageId)",
      "Az emailt most nem tudtuk előkészíteni",
      "Nincs jogosultság az email küldéséhez.",
      "Az email küldéséhez szükséges adatok hiányosak vagy hibásak.",
    ],
    excludes: [
      'Response.json({ error: "Server configuration error" }',
      'Response.json({ error: "Unauthorized" }',
      'Response.json({ error: "Invalid JSON in request body" }',
      'Response.json({ error: "templateName is required" }',
      'Response.json({ error: "Failed to verify suppression status" }',
      'Response.json({ error: "Failed to prepare email" }',
      'Response.json({ error: "Failed to enqueue email" }',
      "Available: ${Object.keys(TEMPLATES).join",
      "recipientEmail is required (unless the template defines a fixed recipient)",
      'console.error("Suppression check failed — refusing to send", {\n            error: suppressionError',
      'console.error("Token lookup failed", {\n              error: tokenLookupError',
      'console.error("Failed to create unsubscribe token", {\n                error: tokenError',
      'console.error("Failed to read back unsubscribe token after upsert", {\n                error: reReadError',
      'console.error("Failed to enqueue email", {\n            error: enqueueError',
    ],
  },
  {
    name: "Lovable email queue process returns localized public errors",
    file: "src/routes/lovable/email/queue/process.ts",
    includes: [
      "PUBLIC_EMAIL_QUEUE_ERROR",
      "PUBLIC_EMAIL_QUEUE_AUTH_ERROR",
      "function publicEmailQueueError",
      "Az email sort most nem tudtuk feldolgozni",
      "Nincs jogosultság az email sor feldolgozásához.",
    ],
    excludes: [
      "Response.json(\n            { error: 'Server configuration error' }",
      "Response.json({ error: 'Unauthorized' }",
      "Response.json({ error: 'Forbidden' }",
    ],
  },
  {
    name: "SSR fallback logging does not include raw response bodies",
    file: "src/server.ts",
    includes: [
      "function swallowedSsrError",
      "function logSsrFallbackError",
      "JSON.parse(body)",
      "h3 swallowed SSR error: ${message} (${status})",
      "logSsrFallbackError(consumeLastCapturedError() ?? swallowedSsrError(body))",
      "SSR fallback error",
      'error_code: "ssr_fallback_error"',
      'error_name: error instanceof Error ? error.name : "unknown"',
    ],
    excludes: [
      "new Error(`h3 swallowed SSR error: ${body}`)",
      "console.error(consumeLastCapturedError() ?? swallowedSsrError(body))",
      "console.error(error)",
      "error.message",
      "error.stack",
    ],
  },
  {
    name: "catastrophic error page is localized and not indexed",
    file: "src/lib/error-page.ts",
    includes: [
      '<html lang="hu">',
      "Az oldal most nem töltött be | Jövőd.hu",
      '<meta name="robots" content="noindex,nofollow" />',
      "Most nem töltött be az oldal",
      "Valami megakadt az oldal betöltésénél",
      "A rendelésed vagy olvasatod ettől nem vész el",
      "Újrapróbálom",
      "Vissza a főoldalra",
    ],
    excludes: [
      '<html lang="en">',
      "This page didn't load",
      "Something went wrong on our end",
      "Valami technikai hiba történt nálunk",
      "Try again",
      "Go home",
    ],
  },
  {
    name: "checkout insert errors redact Stripe session ids",
    file: "src/lib/payments.functions.ts",
    includes: [
      "function redactStripeId",
      "function stableErrorCode",
      'error_code: "checkout_order_insert_failed"',
      "session_id_redacted: redactStripeId(session.id)",
      "database_code: stableErrorCode(orderError)",
      "createCheckoutSession order insert failed",
      "createCheckoutSession failed",
      "error_code: safeCheckoutErrorCode(error)",
      "has_user_id: Boolean(data.userId)",
      'error_code: "checkout_session_expire_failed"',
      'error_code: "order_reconciliation_processing_failed"',
      'error_code: "checkout_payment_reconciliation_failed"',
      'error_code: "failed_order_retry_payment_verification_failed"',
      "provider_code: stableErrorCode(error)",
      "session_id_redacted: redactStripeId(sessionId)",
      "session_id_redacted: redactStripeId(order.stripe_session_id)",
    ],
    excludes: [
      "sessionId: session.id",
      "error: orderError.message",
      'console.error("createCheckoutSession error:", error)',
      'console.warn("Could not expire checkout session without order:", error)',
      'console.warn("order reconciliation processing failed:", error)',
      'console.warn("checkout payment reconciliation failed:", error)',
      'console.warn("failed order retry payment verification failed:", error)',
    ],
  },
  {
    name: "payment webhooks redact Stripe session ids in operational logs",
    file: "src/routes/api/public/payments/webhook.ts",
    includes: [
      "function redactStripeId",
      "function redactOrderId",
      "session_id_redacted: redactStripeId(sessionId)",
      "order_id_redacted: redactOrderId(existing.id)",
      'error_code: "paid_order_processing_failed"',
      'error_code: "paid_order_processing_exception"',
      'error_code: "payment_webhook_failed"',
      "checkout.session.completed for unknown session",
    ],
    excludes: [
      'console.error("checkout.session.completed for unknown session:", sessionId)',
      'console.log("Order already delivered:", existing.id)',
      'console.log("Order is not processable from webhook:", existing.id, existing.status)',
      'console.error("processPaidOrderBySession failed:", result.error)',
      'console.error("processPaidOrderBySession failed:", e)',
      'console.error("Webhook error:", e)',
    ],
  },
  {
    name: "homepage daily briefing never displays raw provider or AI errors",
    file: "src/components/PersonalDailyBriefing.tsx",
    includes: [
      "SAFE_DAILY_BRIEFING_ERROR",
      "setError(SAFE_DAILY_BRIEFING_ERROR)",
      "A mai személyes összefoglaló most nem állt össze elég tisztán",
      "A lapod megmaradt",
      "fizetés nem indult",
    ],
    excludes: ["setError(\n        res.message ??", "setError(res.message"],
  },
  {
    name: "daily briefing server returns a stable public failure message",
    file: "src/lib/roxy.functions.ts",
    includes: [
      "PERSONAL_DAILY_BRIEFING_ERROR",
      "message: PERSONAL_DAILY_BRIEFING_ERROR",
      "A mai személyes összefoglaló most nem állt össze elég tisztán",
      "félkész olvasatot nem mentettünk",
    ],
    excludes: ['message: ai.error ?? "AI hiba"', 'message: "AI hiba"'],
  },
  {
    name: "shared tarot AI readings never expose model or guard diagnostics",
    file: "src/lib/roxy.functions.ts",
    includes: [
      "TAROT_AI_READING_ERROR",
      "message: TAROT_AI_READING_ERROR",
      "Most nem sikerült elkészíteni az olvasatot",
    ],
    excludes: ['message: guard.issues.join("; ")'],
  },
  {
    name: "withdrawal page gives clear recovery steps for paid delivery issues",
    file: "src/routes/elallasi-tajekoztato.tsx",
    includes: [
      "elkészítés a sikeres fizetés után",
      "az elkészült olvasat pedig a rendelési oldalon vagy a felhasználói profilban",
      "Hibás teljesítés vagy hozzáférési gond",
      "vásárláshoz használt email címet",
      "rövid rendelésazonosítót",
      "melyik olvasatnál akadt el",
      "fizetés utáni",
      "köszönőoldalt",
      "profilod rendelési előzményeit",
      "nem csak emailben",
      "SYMBOLIC_TRADITION_DISCLAIMER",
      "önmagában nem minősül",
      "hozzáférési hibának",
    ],
    excludes: ["automatikusan készülnek el", "szimbolikus, önismereti és szórakoztató tartalmak"],
  },
  {
    name: "numerology SEO pages never expose raw router error messages",
    file: "src/routes/sorsszam.$n.tsx",
    includes: [
      "SAFE_NUMEROLOGY_PAGE_ERROR",
      "A számmisztikai oldal most nem nyílt meg elég tisztán",
      "Nem veszett el semmilyen adat",
      "indítsd újra nyugodtan",
      "Megpróbálom újra",
    ],
    excludes: ["lead={error.message}", "Kérlek próbáld újra", 'eyebrow="Hiba"'],
  },
  {
    name: "numerology type pages never expose raw router error messages",
    file: "src/routes/numerologia.$type.tsx",
    includes: [
      "SAFE_NUMEROLOGY_PAGE_ERROR",
      "A számmisztikai oldal most nem nyílt meg elég tisztán",
      "Nem veszett el semmilyen adat",
      "indítsd újra nyugodtan",
      "Megpróbálom újra",
    ],
    excludes: ["lead={error.message}", "Kérlek próbáld újra", 'eyebrow="Hiba"'],
  },
  {
    name: "natal chart page never displays raw provider or AI errors",
    file: "src/routes/szuletesi-keplet.tsx",
    includes: [
      "SAFE_NATAL_CHART_ERROR",
      "A képlet most nem állt össze elég tisztán",
      "Nem mentettünk félkész olvasatot",
      "indítsd újra nyugodtan",
      "setErr(SAFE_NATAL_CHART_ERROR)",
    ],
    excludes: [
      "Próbáld újra később",
      'setErr(r.message ?? "A képletet most nem sikerült elkészíteni.")',
      "setErr(r.message",
    ],
  },
  {
    name: "natal chart translation returns stable public failure copy",
    file: "src/lib/roxyTranslate.functions.ts",
    includes: [
      "PUBLIC_NATAL_ERROR",
      "A születési képlet olvasata most nem állt össze elég tisztán",
      "message: PUBLIC_NATAL_ERROR",
      "reading: null",
    ],
    excludes: [
      "A születési képletet most nem érem el",
      "A születési képlet magyar olvasata most nem készült el",
      'message: t.error ?? "Magyarítási hiba."',
      "message: t.error",
    ],
  },
  {
    name: "magazine article fallback keeps readers in the content journey",
    file: "src/routes/magazin.$slug.tsx",
    includes: [
      "ArticleFallback",
      "Ez a cikk nem található",
      "Most nem töltött be a cikk",
      "A magazin főoldalán megtalálod",
      "Valami megakadt a cikk megnyitásakor",
      "Magazin főoldal",
      "Vissza a főoldalra",
    ],
    excludes: ["Kérlek próbáld újra később"],
  },
  {
    name: "homepage tarot spread avoids horizontal viewport overflow",
    file: "src/components/SpreadDeck.tsx",
    includes: ["const spreadX = (t - 0.5) * 70"],
    excludes: ["const spreadX = (t - 0.5) * 92"],
  },
  {
    name: "share card failure gives a useful save fallback",
    file: "src/components/ShareCardButton.tsx",
    includes: [
      "statusKind",
      'aria-live="polite"',
      "Most nem sikerült menteni",
      "készíts képernyőképet az olvasatról",
      "Megosztás / mentés",
    ],
    excludes: ['setStatus("Most nem sikerült.")', 'busy ? "Készítem…" : (status ??'],
  },
  {
    name: "free draw failures do not feel like lost readings",
    file: "src/routes/mai-lap.tsx",
    includes: [
      'aria-live="polite"',
      "rounded-md border border-gold/15 bg-gold/[0.06]",
      "A húzás most nem érkezett meg",
      "Nem mentettünk félkész olvasatot",
      "indíts új húzást nyugodtan",
    ],
    excludes: ["Próbáld újra egy pillanat múlva"],
  },
  {
    name: "relationship draw failures do not feel like lost readings",
    file: "src/routes/randi-elott.tsx",
    includes: [
      'aria-live="polite"',
      "rounded-md border border-gold/15 bg-gold/[0.06]",
      "A húzás most nem érkezett meg",
      "Nem mentettünk félkész olvasatot",
      "indíts új húzást nyugodtan",
    ],
    excludes: ["Próbáld újra."],
  },
  {
    name: "decision draw failures do not feel like lost readings",
    file: "src/routes/dontes-elott.tsx",
    includes: [
      'aria-live="polite"',
      "rounded-md border border-gold/15 bg-gold/[0.06]",
      "A húzás most nem érkezett meg",
      "Nem mentettünk félkész olvasatot",
      "indíts új húzást nyugodtan",
    ],
    excludes: ["Próbáld újra."],
  },
  {
    name: "three-card draw failures do not feel like lost readings",
    file: "src/routes/harom-lap.tsx",
    includes: [
      'aria-live="polite"',
      "rounded-md border border-gold/15 bg-gold/[0.06]",
      "A húzás most nem érkezett meg",
      "A húzás nem teljes",
      "Nem mentettünk félkész olvasatot",
      "indíts új húzást nyugodtan",
    ],
    excludes: ["Próbáld újra egy pillanat múlva", "próbáld újra."],
  },
  {
    name: "homepage daily draw failures do not feel like lost readings",
    file: "src/components/PersonalDailyBriefing.tsx",
    includes: [
      'aria-live="polite"',
      "rounded-md border border-gold/15 bg-gold/[0.06]",
      "A húzás most nem érkezett meg",
      "Nem mentettünk félkész olvasatot",
      "indíts új húzást nyugodtan",
    ],
    excludes: ["Próbáld újra egy pillanat múlva"],
  },
  {
    name: "yes-no widget frames answers as tarot guidance, not decisions",
    file: "src/components/YesNoWidget.tsx",
    includes: [
      "Egy kérdés — egy tarot-irányjel",
      "a tarot hagyományából ad",
      "nem dönt helyetted",
      "nem ígér biztos jövőt",
      "irányjel",
      "Tarot-hagyomány szerinti fókusz, nem végleges döntés",
    ],
    excludes: ["egyértelmű választ ad", "biztos választ ad", "végleges válasz"],
  },
  {
    name: "yes-no widget failures never expose server messages",
    file: "src/components/YesNoWidget.tsx",
    includes: [
      "SAFE_YES_NO_ERROR",
      "A válasz most nem állt össze elég tisztán",
      "Nem mentettünk félkész olvasatot",
      "fogalmazd újra a kérdést",
      "setErr(SAFE_YES_NO_ERROR)",
      "} catch {",
    ],
    excludes: ["setErr(r.message", "Most nem érkezett válasz"],
  },
  {
    name: "yes-no server failures use stable public copy",
    file: "src/lib/roxyTranslate.functions.ts",
    includes: [
      "PUBLIC_YES_NO_ERROR",
      "A válasz most nem állt össze elég tisztán",
      "message: PUBLIC_YES_NO_ERROR",
      "Tarot yes/no kérdésre adott rövid, hagyomány-alapú irányjel",
      "ne ígérj biztos jövőt",
      "ne dönts a kérdező helyett",
    ],
    excludes: [
      "Üres válasz a forrásból",
      "Most nem érkezett válasz",
      'message: "A magyar olvasat most nem készült el."',
    ],
  },
  {
    name: "symbolic reading server failures avoid data-access wording",
    file: "src/lib/roxyTranslate.functions.ts",
    includes: [
      "PUBLIC_HOROSCOPE_ERROR",
      "PUBLIC_CRYSTAL_ERROR",
      "PUBLIC_ANGEL_ERROR",
      "PUBLIC_DREAM_ERROR",
      "PUBLIC_NUMEROLOGY_ERROR",
      "PUBLIC_MOON_ERROR",
      "A mai horoszkóp most nem állt össze elég tisztán",
      "A kristályjel most nem állt össze elég tisztán",
      "Az angyalszám olvasata most nem állt össze elég tisztán",
      "Az álomjel most nem állt össze elég tisztán",
      "A számmisztikai olvasat most nem állt össze elég tisztán",
      "A holdfázis üzenete most nem állt össze elég tisztán",
      "Nem mentettünk félkész olvasatot",
      "Nem mentettünk félkész szöveget",
      "indítsd újra nyugodtan",
    ],
    excludes: [
      "Próbáld újra később",
      "próbáld újra később",
      "Most nem értem el a horoszkóp adatot",
      "Most nem értem el a kristály adatot",
      "Most nem értem el az angyalszám adatot",
      "Most nem értem el az álom adatot",
      "Most nem értem el a számmisztika adatot",
      "Most nem érem el a holdfázist",
    ],
  },
];

const failed: string[] = [];

for (const check of checks) {
  const body = readFileSync(check.file, "utf8");
  const missing = check.includes.filter((needle) => !body.includes(needle));
  if (missing.length) failed.push(`${check.name}: missing ${missing.join(", ")}`);
  const forbidden = (check.excludes ?? []).filter((needle) => body.includes(needle));
  if (forbidden.length) failed.push(`${check.name}: forbidden ${forbidden.join(", ")}`);
}

if (failed.length) {
  console.error("Trust experience audit failed:");
  for (const item of failed) console.error(`- ${item}`);
  process.exit(1);
}

console.log(`Trust experience audit passed: ${checks.length} checks.`);
