// One-off script: fetch life-path interpretations from Roxy for representative
// birth dates, translate to Hungarian via Lovable AI, and write
// src/data/lifePathMeanings.hu.ts.
//
// Run: bun run scripts/bake-lifepath.ts
//
// Requires env: ROXY_API_KEY, LOVABLE_API_KEY.

import { writeFileSync } from "node:fs";

const ROXY = "https://roxyapi.com/api/v2";
const ROXY_KEY = process.env.ROXY_API_KEY!;
const LOV_KEY = process.env.LOVABLE_API_KEY!;

// Representative birth dates that reduce to each life path.
const SAMPLES: { n: number; date: { year: number; month: number; day: number } }[] = [
  { n: 1, date: { year: 1990, month: 1, day: 1 } },
  { n: 2, date: { year: 1990, month: 1, day: 2 } },
  { n: 3, date: { year: 1990, month: 1, day: 3 } },
  { n: 4, date: { year: 1990, month: 1, day: 4 } },
  { n: 5, date: { year: 1990, month: 1, day: 5 } },
  { n: 6, date: { year: 1990, month: 1, day: 6 } },
  { n: 7, date: { year: 1990, month: 1, day: 7 } },
  { n: 8, date: { year: 1990, month: 1, day: 8 } },
  { n: 9, date: { year: 1990, month: 1, day: 9 } },
  { n: 11, date: { year: 1991, month: 1, day: 8 } }, // 1+9+9+1+1+8=29 -> 11
  { n: 22, date: { year: 1993, month: 8, day: 1 } }, // 1+9+9+3+8+1=31 -> 4? recompute
  { n: 33, date: { year: 1980, month: 12, day: 25 } }, // tune below
];

function reduce(n: number, keepMaster = true): number {
  while (n > 9 && !(keepMaster && (n === 11 || n === 22 || n === 33))) {
    n = String(n).split("").reduce((s, d) => s + Number(d), 0);
  }
  return n;
}

// Auto-find a date whose life-path reduces to target n (if hard-coded sample is wrong).
function findDate(target: number): { year: number; month: number; day: number } {
  for (let y = 1980; y <= 2000; y++)
    for (let m = 1; m <= 12; m++)
      for (let d = 1; d <= 28; d++) {
        const sum = (`${y}${m}${d}`).split("").reduce((s, c) => s + Number(c), 0);
        if (reduce(sum) === target) return { year: y, month: m, day: d };
      }
  throw new Error(`no date for ${target}`);
}

async function callRoxy(date: { year: number; month: number; day: number }) {
  const res = await fetch(`${ROXY}/numerology/life-path`, {
    method: "POST",
    headers: {
      "X-API-Key": ROXY_KEY,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(date),
  });
  if (!res.ok) throw new Error(`Roxy ${res.status}: ${await res.text()}`);
  return res.json();
}

async function translateAndStructure(n: number, raw: unknown) {
  const prompt = `Az alábbi angol numerológiai életút (Life Path ${n}) leírást alakítsd át magyar nyelvű, önismereti hangvételű tartalommá. NE jósolj, NE ígérj. Egyetlen JSON objektumot adj vissza pontosan ezekkel a kulcsokkal:
{
  "title": "Sorsszám ${n} jelentése — rövid alcím",
  "lead": "1-2 mondatos bevezető magyarul",
  "essence": "3-4 mondat a szám alaprezgéséről",
  "strengths": "3-4 mondat az erősségekről",
  "shadow": "3-4 mondat az árnyékoldalról / kihívásokról",
  "love": "2-3 mondat a szerelmi/párkapcsolati mintáról",
  "career": "2-3 mondat a munka/hivatás területéről",
  "advice": "2-3 mondat önismereti tanács, ne parancsolj"
}
CSAK a JSON-t add vissza, magyarázat nélkül.

Forrás (angol):
${JSON.stringify(raw).slice(0, 4000)}`;

  const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${LOV_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "google/gemini-2.5-flash",
      messages: [{ role: "user", content: prompt }],
      response_format: { type: "json_object" },
    }),
  });
  if (!res.ok) throw new Error(`AI ${res.status}: ${await res.text()}`);
  const json = (await res.json()) as { choices: { message: { content: string } }[] };
  return JSON.parse(json.choices[0].message.content);
}

async function main() {
  const out: Record<string, unknown> = {};
  for (const { n } of SAMPLES) {
    const date = findDate(n);
    console.log(`Life path ${n} — date ${date.year}-${date.month}-${date.day}`);
    const raw = await callRoxy(date);
    const structured = await translateAndStructure(n, raw);
    out[String(n)] = structured;
    await new Promise((r) => setTimeout(r, 800));
  }

  const body = `// AUTO-GENERATED by scripts/bake-lifepath.ts — do not edit by hand.
// Source: Roxy /numerology/life-path, fordítva magyarra.

export type LifePathMeaning = {
  title: string;
  lead: string;
  essence: string;
  strengths: string;
  shadow: string;
  love: string;
  career: string;
  advice: string;
};

export const LIFE_PATH_MEANINGS_HU: Record<string, LifePathMeaning> = ${JSON.stringify(out, null, 2)};

export const LIFE_PATH_NUMBERS = ${JSON.stringify(SAMPLES.map((s) => s.n))} as const;
`;
  writeFileSync("src/data/lifePathMeanings.hu.ts", body);
  console.log("Wrote src/data/lifePathMeanings.hu.ts");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});