/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SzammisztikaRouteImport } from './routes/szammisztika'
import { Route as RandiElottRouteImport } from './routes/randi-elott'
import { Route as OsszeillunkRouteImport } from './routes/osszeillunk'
import { Route as MaiLapRouteImport } from './routes/mai-lap'
import { Route as HaromLapRouteImport } from './routes/harom-lap'
import { Route as DontesElottRouteImport } from './routes/dontes-elott'
import { Route as IndexRouteImport } from './routes/index'

const SzammisztikaRoute = SzammisztikaRouteImport.update({
  id: '/szammisztika',
  path: '/szammisztika',
  getParentRoute: () => rootRouteImport,
} as any)
const RandiElottRoute = RandiElottRouteImport.update({
  id: '/randi-elott',
  path: '/randi-elott',
  getParentRoute: () => rootRouteImport,
} as any)
const OsszeillunkRoute = OsszeillunkRouteImport.update({
  id: '/osszeillunk',
  path: '/osszeillunk',
  getParentRoute: () => rootRouteImport,
} as any)
const MaiLapRoute = MaiLapRouteImport.update({
  id: '/mai-lap',
  path: '/mai-lap',
  getParentRoute: () => rootRouteImport,
} as any)
const HaromLapRoute = HaromLapRouteImport.update({
  id: '/harom-lap',
  path: '/harom-lap',
  getParentRoute: () => rootRouteImport,
} as any)
const DontesElottRoute = DontesElottRouteImport.update({
  id: '/dontes-elott',
  path: '/dontes-elott',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dontes-elott': typeof DontesElottRoute
  '/harom-lap': typeof HaromLapRoute
  '/mai-lap': typeof MaiLapRoute
  '/osszeillunk': typeof OsszeillunkRoute
  '/randi-elott': typeof RandiElottRoute
  '/szammisztika': typeof SzammisztikaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dontes-elott': typeof DontesElottRoute
  '/harom-lap': typeof HaromLapRoute
  '/mai-lap': typeof MaiLapRoute
  '/osszeillunk': typeof OsszeillunkRoute
  '/randi-elott': typeof RandiElottRoute
  '/szammisztika': typeof SzammisztikaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dontes-elott': typeof DontesElottRoute
  '/harom-lap': typeof HaromLapRoute
  '/mai-lap': typeof MaiLapRoute
  '/osszeillunk': typeof OsszeillunkRoute
  '/randi-elott': typeof RandiElottRoute
  '/szammisztika': typeof SzammisztikaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dontes-elott'
    | '/harom-lap'
    | '/mai-lap'
    | '/osszeillunk'
    | '/randi-elott'
    | '/szammisztika'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dontes-elott'
    | '/harom-lap'
    | '/mai-lap'
    | '/osszeillunk'
    | '/randi-elott'
    | '/szammisztika'
  id:
    | '__root__'
    | '/'
    | '/dontes-elott'
    | '/harom-lap'
    | '/mai-lap'
    | '/osszeillunk'
    | '/randi-elott'
    | '/szammisztika'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DontesElottRoute: typeof DontesElottRoute
  HaromLapRoute: typeof HaromLapRoute
  MaiLapRoute: typeof MaiLapRoute
  OsszeillunkRoute: typeof OsszeillunkRoute
  RandiElottRoute: typeof RandiElottRoute
  SzammisztikaRoute: typeof SzammisztikaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/szammisztika': {
      id: '/szammisztika'
      path: '/szammisztika'
      fullPath: '/szammisztika'
      preLoaderRoute: typeof SzammisztikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randi-elott': {
      id: '/randi-elott'
      path: '/randi-elott'
      fullPath: '/randi-elott'
      preLoaderRoute: typeof RandiElottRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osszeillunk': {
      id: '/osszeillunk'
      path: '/osszeillunk'
      fullPath: '/osszeillunk'
      preLoaderRoute: typeof OsszeillunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mai-lap': {
      id: '/mai-lap'
      path: '/mai-lap'
      fullPath: '/mai-lap'
      preLoaderRoute: typeof MaiLapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harom-lap': {
      id: '/harom-lap'
      path: '/harom-lap'
      fullPath: '/harom-lap'
      preLoaderRoute: typeof HaromLapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dontes-elott': {
      id: '/dontes-elott'
      path: '/dontes-elott'
      fullPath: '/dontes-elott'
      preLoaderRoute: typeof DontesElottRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DontesElottRoute: DontesElottRoute,
  HaromLapRoute: HaromLapRoute,
  MaiLapRoute: MaiLapRoute,
  OsszeillunkRoute: OsszeillunkRoute,
  RandiElottRoute: RandiElottRoute,
  SzammisztikaRoute: SzammisztikaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
