/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaiLapRouteImport } from './routes/mai-lap'
import { Route as HaromLapRouteImport } from './routes/harom-lap'
import { Route as IndexRouteImport } from './routes/index'

const MaiLapRoute = MaiLapRouteImport.update({
  id: '/mai-lap',
  path: '/mai-lap',
  getParentRoute: () => rootRouteImport,
} as any)
const HaromLapRoute = HaromLapRouteImport.update({
  id: '/harom-lap',
  path: '/harom-lap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harom-lap': typeof HaromLapRoute
  '/mai-lap': typeof MaiLapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harom-lap': typeof HaromLapRoute
  '/mai-lap': typeof MaiLapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/harom-lap': typeof HaromLapRoute
  '/mai-lap': typeof MaiLapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/harom-lap' | '/mai-lap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/harom-lap' | '/mai-lap'
  id: '__root__' | '/' | '/harom-lap' | '/mai-lap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HaromLapRoute: typeof HaromLapRoute
  MaiLapRoute: typeof MaiLapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mai-lap': {
      id: '/mai-lap'
      path: '/mai-lap'
      fullPath: '/mai-lap'
      preLoaderRoute: typeof MaiLapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harom-lap': {
      id: '/harom-lap'
      path: '/harom-lap'
      fullPath: '/harom-lap'
      preLoaderRoute: typeof HaromLapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HaromLapRoute: HaromLapRoute,
  MaiLapRoute: MaiLapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
