/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SzammisztikaRouteImport } from './routes/szammisztika'
import { Route as RolunkRouteImport } from './routes/rolunk'
import { Route as RandiElottRouteImport } from './routes/randi-elott'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as OsszeillunkRouteImport } from './routes/osszeillunk'
import { Route as MaiLapRouteImport } from './routes/mai-lap'
import { Route as MaiIranytuRouteImport } from './routes/mai-iranytu'
import { Route as KristalyRouteImport } from './routes/kristaly'
import { Route as HoroszkopRouteImport } from './routes/horoszkop'
import { Route as HaromLapRouteImport } from './routes/harom-lap'
import { Route as DontesElottRouteImport } from './routes/dontes-elott'
import { Route as BejelentkezesRouteImport } from './routes/bejelentkezes'
import { Route as AngyalszamRouteImport } from './routes/angyalszam'
import { Route as AlomfejtesRouteImport } from './routes/alomfejtes'
import { Route as IndexRouteImport } from './routes/index'

const SzammisztikaRoute = SzammisztikaRouteImport.update({
  id: '/szammisztika',
  path: '/szammisztika',
  getParentRoute: () => rootRouteImport,
} as any)
const RolunkRoute = RolunkRouteImport.update({
  id: '/rolunk',
  path: '/rolunk',
  getParentRoute: () => rootRouteImport,
} as any)
const RandiElottRoute = RandiElottRouteImport.update({
  id: '/randi-elott',
  path: '/randi-elott',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const OsszeillunkRoute = OsszeillunkRouteImport.update({
  id: '/osszeillunk',
  path: '/osszeillunk',
  getParentRoute: () => rootRouteImport,
} as any)
const MaiLapRoute = MaiLapRouteImport.update({
  id: '/mai-lap',
  path: '/mai-lap',
  getParentRoute: () => rootRouteImport,
} as any)
const MaiIranytuRoute = MaiIranytuRouteImport.update({
  id: '/mai-iranytu',
  path: '/mai-iranytu',
  getParentRoute: () => rootRouteImport,
} as any)
const KristalyRoute = KristalyRouteImport.update({
  id: '/kristaly',
  path: '/kristaly',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroszkopRoute = HoroszkopRouteImport.update({
  id: '/horoszkop',
  path: '/horoszkop',
  getParentRoute: () => rootRouteImport,
} as any)
const HaromLapRoute = HaromLapRouteImport.update({
  id: '/harom-lap',
  path: '/harom-lap',
  getParentRoute: () => rootRouteImport,
} as any)
const DontesElottRoute = DontesElottRouteImport.update({
  id: '/dontes-elott',
  path: '/dontes-elott',
  getParentRoute: () => rootRouteImport,
} as any)
const BejelentkezesRoute = BejelentkezesRouteImport.update({
  id: '/bejelentkezes',
  path: '/bejelentkezes',
  getParentRoute: () => rootRouteImport,
} as any)
const AngyalszamRoute = AngyalszamRouteImport.update({
  id: '/angyalszam',
  path: '/angyalszam',
  getParentRoute: () => rootRouteImport,
} as any)
const AlomfejtesRoute = AlomfejtesRouteImport.update({
  id: '/alomfejtes',
  path: '/alomfejtes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alomfejtes': typeof AlomfejtesRoute
  '/angyalszam': typeof AngyalszamRoute
  '/bejelentkezes': typeof BejelentkezesRoute
  '/dontes-elott': typeof DontesElottRoute
  '/harom-lap': typeof HaromLapRoute
  '/horoszkop': typeof HoroszkopRoute
  '/kristaly': typeof KristalyRoute
  '/mai-iranytu': typeof MaiIranytuRoute
  '/mai-lap': typeof MaiLapRoute
  '/osszeillunk': typeof OsszeillunkRoute
  '/profil': typeof ProfilRoute
  '/randi-elott': typeof RandiElottRoute
  '/rolunk': typeof RolunkRoute
  '/szammisztika': typeof SzammisztikaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alomfejtes': typeof AlomfejtesRoute
  '/angyalszam': typeof AngyalszamRoute
  '/bejelentkezes': typeof BejelentkezesRoute
  '/dontes-elott': typeof DontesElottRoute
  '/harom-lap': typeof HaromLapRoute
  '/horoszkop': typeof HoroszkopRoute
  '/kristaly': typeof KristalyRoute
  '/mai-iranytu': typeof MaiIranytuRoute
  '/mai-lap': typeof MaiLapRoute
  '/osszeillunk': typeof OsszeillunkRoute
  '/profil': typeof ProfilRoute
  '/randi-elott': typeof RandiElottRoute
  '/rolunk': typeof RolunkRoute
  '/szammisztika': typeof SzammisztikaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alomfejtes': typeof AlomfejtesRoute
  '/angyalszam': typeof AngyalszamRoute
  '/bejelentkezes': typeof BejelentkezesRoute
  '/dontes-elott': typeof DontesElottRoute
  '/harom-lap': typeof HaromLapRoute
  '/horoszkop': typeof HoroszkopRoute
  '/kristaly': typeof KristalyRoute
  '/mai-iranytu': typeof MaiIranytuRoute
  '/mai-lap': typeof MaiLapRoute
  '/osszeillunk': typeof OsszeillunkRoute
  '/profil': typeof ProfilRoute
  '/randi-elott': typeof RandiElottRoute
  '/rolunk': typeof RolunkRoute
  '/szammisztika': typeof SzammisztikaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alomfejtes'
    | '/angyalszam'
    | '/bejelentkezes'
    | '/dontes-elott'
    | '/harom-lap'
    | '/horoszkop'
    | '/kristaly'
    | '/mai-iranytu'
    | '/mai-lap'
    | '/osszeillunk'
    | '/profil'
    | '/randi-elott'
    | '/rolunk'
    | '/szammisztika'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alomfejtes'
    | '/angyalszam'
    | '/bejelentkezes'
    | '/dontes-elott'
    | '/harom-lap'
    | '/horoszkop'
    | '/kristaly'
    | '/mai-iranytu'
    | '/mai-lap'
    | '/osszeillunk'
    | '/profil'
    | '/randi-elott'
    | '/rolunk'
    | '/szammisztika'
  id:
    | '__root__'
    | '/'
    | '/alomfejtes'
    | '/angyalszam'
    | '/bejelentkezes'
    | '/dontes-elott'
    | '/harom-lap'
    | '/horoszkop'
    | '/kristaly'
    | '/mai-iranytu'
    | '/mai-lap'
    | '/osszeillunk'
    | '/profil'
    | '/randi-elott'
    | '/rolunk'
    | '/szammisztika'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlomfejtesRoute: typeof AlomfejtesRoute
  AngyalszamRoute: typeof AngyalszamRoute
  BejelentkezesRoute: typeof BejelentkezesRoute
  DontesElottRoute: typeof DontesElottRoute
  HaromLapRoute: typeof HaromLapRoute
  HoroszkopRoute: typeof HoroszkopRoute
  KristalyRoute: typeof KristalyRoute
  MaiIranytuRoute: typeof MaiIranytuRoute
  MaiLapRoute: typeof MaiLapRoute
  OsszeillunkRoute: typeof OsszeillunkRoute
  ProfilRoute: typeof ProfilRoute
  RandiElottRoute: typeof RandiElottRoute
  RolunkRoute: typeof RolunkRoute
  SzammisztikaRoute: typeof SzammisztikaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/szammisztika': {
      id: '/szammisztika'
      path: '/szammisztika'
      fullPath: '/szammisztika'
      preLoaderRoute: typeof SzammisztikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolunk': {
      id: '/rolunk'
      path: '/rolunk'
      fullPath: '/rolunk'
      preLoaderRoute: typeof RolunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randi-elott': {
      id: '/randi-elott'
      path: '/randi-elott'
      fullPath: '/randi-elott'
      preLoaderRoute: typeof RandiElottRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osszeillunk': {
      id: '/osszeillunk'
      path: '/osszeillunk'
      fullPath: '/osszeillunk'
      preLoaderRoute: typeof OsszeillunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mai-lap': {
      id: '/mai-lap'
      path: '/mai-lap'
      fullPath: '/mai-lap'
      preLoaderRoute: typeof MaiLapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mai-iranytu': {
      id: '/mai-iranytu'
      path: '/mai-iranytu'
      fullPath: '/mai-iranytu'
      preLoaderRoute: typeof MaiIranytuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kristaly': {
      id: '/kristaly'
      path: '/kristaly'
      fullPath: '/kristaly'
      preLoaderRoute: typeof KristalyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoszkop': {
      id: '/horoszkop'
      path: '/horoszkop'
      fullPath: '/horoszkop'
      preLoaderRoute: typeof HoroszkopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harom-lap': {
      id: '/harom-lap'
      path: '/harom-lap'
      fullPath: '/harom-lap'
      preLoaderRoute: typeof HaromLapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dontes-elott': {
      id: '/dontes-elott'
      path: '/dontes-elott'
      fullPath: '/dontes-elott'
      preLoaderRoute: typeof DontesElottRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bejelentkezes': {
      id: '/bejelentkezes'
      path: '/bejelentkezes'
      fullPath: '/bejelentkezes'
      preLoaderRoute: typeof BejelentkezesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angyalszam': {
      id: '/angyalszam'
      path: '/angyalszam'
      fullPath: '/angyalszam'
      preLoaderRoute: typeof AngyalszamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alomfejtes': {
      id: '/alomfejtes'
      path: '/alomfejtes'
      fullPath: '/alomfejtes'
      preLoaderRoute: typeof AlomfejtesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlomfejtesRoute: AlomfejtesRoute,
  AngyalszamRoute: AngyalszamRoute,
  BejelentkezesRoute: BejelentkezesRoute,
  DontesElottRoute: DontesElottRoute,
  HaromLapRoute: HaromLapRoute,
  HoroszkopRoute: HoroszkopRoute,
  KristalyRoute: KristalyRoute,
  MaiIranytuRoute: MaiIranytuRoute,
  MaiLapRoute: MaiLapRoute,
  OsszeillunkRoute: OsszeillunkRoute,
  ProfilRoute: ProfilRoute,
  RandiElottRoute: RandiElottRoute,
  RolunkRoute: RolunkRoute,
  SzammisztikaRoute: SzammisztikaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
