// AUTO-GENERATED by scripts/bake-lifepath.ts — do not edit by hand.
// Számmisztikai jelentéstár magyar olvasatokhoz.

export type LifePathMeaning = {
  title: string;
  lead: string;
  essence: string;
  strengths: string;
  shadow: string;
  love: string;
  career: string;
  advice: string;
};

export const LIFE_PATH_MEANINGS_HU: Record<string, LifePathMeaning> = {
  "1": {
    title: "Sorsszám 1 jelentése – Az önálló kezdeményező",
    lead: "Az 1-es sorsszám az önállóság, az újrakezdések és a saját irány keresésének jelképe. Nem vezetői rangot vagy kész szerepet ír le, inkább azt a mintát mutatja, amikor fontos lehet a kezdeményezés és a felelős önállóság.",
    essence:
      "Az 1-es hagyományos olvasata a kezdeményezés, újrakezdés és önálló iránykeresés témáit emeli előtérbe. Nem azt állítja, hogy mindent egyedül kell alakítanod, inkább arra figyelmeztet, hogy a saját döntési tér felismerése akkor támogató, ha felelősséggel és másokra is figyelő jelenléttel társul.",
    strengths:
      "Az 1-es sorsszám mintája az önálló kezdeményezést, a saját irány keresését és a cselekvő bátorságot emeli ki. Erőssége akkor látszik tisztán, amikor az újrakezdés nem türelmetlen bizonyítás, hanem felelősen vállalt első lépés. A hagyomány szerint ez a szám kreatív megoldáskeresést és kezdeményező ritmust jelezhet.",
    shadow:
      "Az 1-es árnyéka lehet, amikor a kezdeményezés türelmetlen bizonyítássá, túl gyors döntéssé vagy mások ritmusának figyelmen kívül hagyásává válik. Nem dominanciát vagy rejtett bizonytalanságot ír elő, inkább arra hívja fel a figyelmet, hogy az önállóság akkor marad tiszta, ha kapcsolódik visszajelzéshez és önreflexióhoz is.",
    love: "Párkapcsolataikban az önállóság és a tisztelet kulcsfontosságú lehet. Olyan kapcsolat illhet ehhez a mintához, ahol van tér a saját ritmusnak, mégis megmarad a figyelmes jelenlét és a kölcsönös alkalmazkodás.",
    career:
      "Nem kész karriertanács, inkább azt jelzi, hogy az 1-es mintázathoz jól illhet az önálló feladatvállalás, az új ötletek elindítása és a döntési tér. Támogató lehet minden olyan közeg, ahol van felelősség, mozgástér és világos cél, de a jó ritmushoz együttműködésre és visszajelzésre is szükség van.",
    advice:
      "Érdemes tudatosítani az önállóság iránti igényedet és a saját irány keresését. Figyelj arra, hogy az előrehaladásod során ne feledkezz meg mások érzéseiről és igényeiről, és néha lassíts le, hogy láthasd a teljes képet.",
  },
  "2": {
    title: "Sorsszám 2 jelentése — A Béketeremtő",
    lead: "A 2-es sorsszámot a numerológiai hagyomány az együttműködés, az érzékeny figyelem és az egyensúlykeresés jelképeként olvassa. Nem kész személyiségcímke, inkább azt mutatja, hol lehet fontos a tapintat, a határtartás és a kapcsolódás ritmusa.",
    essence:
      "A 2-es szám a numerológiában a befogadás, az arányérzék és a finom kapcsolati figyelem mintáját képviseli. Az együttműködésre fókuszálhat, és gyakran azt a kérdést hozza elő, hogyan lehet békét és egyensúlyt teremteni anélkül, hogy közben eltűnnének a saját határok. Intuitív, érzékeny jelként arra hívhatja fel a figyelmet, hogy az empátia akkor támogató, ha a tiszta önkifejezéssel is együtt jár.",
    strengths:
      "Erőssége a finomhangolás lehet: könnyebben észreveheti a kimondatlan feszültségeket, a kapcsolati ritmust és azt, mikor van szükség türelmesebb jelenlétre. A 2-es mintázat béketeremtő irányt jelezhet, de akkor működik egészségesen, ha a diplomácia nem önfeladás. Hatása gyakran csendes: nem irányít látványosan, inkább teret ad annak, hogy a felek meghallják egymást.",
    shadow:
      "Árnyéka akkor jelenhet meg, amikor a béke kedvéért túl sokáig marad kimondatlan, mire van valójában szükség. A középen maradás vágya elbizonytalaníthat döntéshelyzetekben, és könnyen háttérbe szoríthatja a saját igényeket. A 2-es mintázat ezért nem csak alkalmazkodást, hanem egészséges határokat is kér.",
    love: "Kapcsolatokban a 2-es sorsszám érzékeny, empatikus és gondoskodó mintát jelezhet. Támogató párkapcsolatban akkor nyílik ki igazán, ha a béke nem a konfliktus kerülését, hanem a tiszta, gyengéd kimondást jelenti.",
    career:
      "Ez a sorsszám olyan szerepekben érzi magát otthonosabban, ahol diplomácia, empátia és együttműködés kell. Jól illhet hozzá a közvetítés, támogatás, emberi kapcsolatok rendezése, csapatmunka vagy olyan háttérszerep, ahol finoman lehet egyensúlyt teremteni. A támogató környezetben könnyebben nyílik ki, mint a kíméletlen versenyben.",
    advice:
      "Érdemes tudatosítani az asszertivitás jelentőségét és azt, hogy a saját szükségleteink kielégítése nem feltétlenül rombolja a harmóniát. Fontos megtanulni határokat húzni és kimondani a véleményünket, még ha az eltér is másoktól. Próbálja meg gyakorolni a döntéshozatalt kisebb dolgokban, hogy fejlessze az önbizalmát ezen a téren.",
  },
  "3": {
    title: "Sorsszám 3 jelentése — A kreatív önkifejezés",
    lead: "A 3-as sorsszámot a numerológiai hagyomány az önkifejezés, a kommunikáció és a kreatív mozgástér jelképeként olvassa. Nem örök derűt vagy kész személyiségcímkét ír le, inkább azt a mintát mutatja, ahol a gondolatok, érzések és kapcsolódások formát keresnek.",
    essence:
      "A 3-as hagyományos olvasata az alkotás, beszéd, játékosság és kapcsolódás témáit emeli előtérbe. Nem állítja, hogy valaki mindig könnyed vagy vidám, inkább arra figyelmeztet, hogy a belső tartalmaknak szükségük lehet nyelvre, ritmusra és látható formára. Akkor támogató, ha a kreatív lendület mellett marad elég fókusz és érzelmi őszinteség is.",
    strengths:
      "A 3-as mintázat erőssége lehet a könnyebb megszólalás, az ötletek összekapcsolása és az, hogy a nehéz érzések is kaphatnak emberi, alkotó formát. Nem kiemelkedő képességet vagy természetes karizmát ígér, inkább azt jelzi, hogy a beszélgetés, írás, humor vagy alkotás segíthet rendezni a belső anyagot.",
    shadow:
      "A 3-as árnyéka lehet a szétszóródás, a túl gyors témaváltás vagy az, amikor a könnyed hang elfedi a nehezebb érzéseket. Nem felszínességet ír elő, hanem arra hívja fel a figyelmet, hogy az önkifejezés akkor marad hiteles, ha a vidámabb forma mögött a valós tartalom is helyet kap.",
    love: "Párkapcsolatban a 3-as mintázat a beszélgetés, játékosság és közös alkotás témáit hozhatja elő. Nem könnyed vagy konfliktusmentes kapcsolatot ígér, inkább azt mutatja, hogy a kapcsolódás akkor mélyülhet, ha a humor és spontaneitás mellett a nehezebb mondatoknak is van tere.",
    career:
      "Nem kész szakmai útmutató, inkább azt jelzi, hogy a 3-as mintázatban fontos lehet az önkifejezés, a kommunikáció és a kreatív mozgástér. Jól illhet hozzá olyan közeg, ahol ötleteket lehet formába rendezni, beszélgetni, alkotni vagy kapcsolatokat építeni. A munka akkor támogató, ha a változatosság mellett marad elég fókusz és józan ritmus is.",
    advice:
      "A 3-as tanulsága a hagyomány szerint az, hogy a kifejezés nem csak könnyedség, hanem felelősség is. Érdemes egyszerre teret adni az ötleteknek és a fókusznak: kimondani, ami formát keres, majd kiválasztani azt a néhány irányt, amelyet valóban végig tudsz vinni.",
  },
  "4": {
    title: "Sorsszám 4 jelentése —  Az építő alapokon",
    lead: "A 4-es sorsszámot a numerológiai hagyomány a stabilitás, rendszerezettség és tartós építkezés jelképeként olvassa. Nem kész személyiségcímke, inkább azt a mintát mutatja, ahol fontos lehet a megbízható ritmus, a határok és az alapok gondos felépítése.",
    essence:
      "A 4-es hagyományos olvasata a földelés, kitartó munka és gyakorlati rend témáit emeli előtérbe. Nem azt állítja, hogy valaki csak mérhető eredményekben gondolkodik, inkább arra figyelmeztet, hogy a biztonság érzése sokszor átlátható keretekből, követhető lépésekből és vállalt ritmusból épül.",
    strengths:
      "A 4-es sorsszám erőssége a rend, kitartás és gyakorlati építkezés jelképes mintájában jelenhet meg. Józan formában stabil alapokat keres, figyel a részletekre, és értékeli azt, ami idővel válik megbízhatóvá. Kapcsolatokban és munkában is akkor támogató, ha a biztonság nem merevségként, hanem tartós figyelemként jelenik meg.",
    shadow:
      "A 4-es árnyéka lehet, amikor a biztonság keresése merev ragaszkodássá vagy túl szűk keretté válik. Nem rugalmatlanságot ír elő, inkább arra hívja fel a figyelmet, hogy a stabilitás akkor marad élő, ha van benne párbeszéd, tanulás és hely az új szempontoknak is.",
    love: "Párkapcsolatban a 4-es mintázat a stabilitás, megbízhatóság és közösen épített biztonság témáit hozhatja elő. Nem hűséget vagy hosszú távú elköteleződést ígér, inkább azt mutatja, hogy a kapcsolat akkor marad megtartó, ha a rutin mellett az érzések kimondása és a rugalmasság is helyet kap.",
    career:
      "A 4-es sorsszámhoz jól illhetnek azok a munkakörnyezetek, ahol precizitás, szervezettség és módszeres gondolkodás érték. Nem kész szakmai útmutató, inkább arra ad nézőpontot, hogy a stabil alapok, rendszerek és tartós építés témái erősebbek lehetnek nálad. A kitartás és a részletekre figyelés akkor hasznos, ha nem merevséggé, hanem megbízható ritmussá válik.",
    advice:
      "Érdemes nyitottságot fejlesztened az új ötletek és perspektívák iránt, még akkor is, ha az elsőre szokatlannak tűnik. Engedd meg magadnak a rugalmasságot, és kísérletezz néha a megszokott mintákon kívül. Emlékezz, a stabilitás érték, de az alkalmazkodás képessége, az építő újdonságok befogadása tovább építheti az életed alapjait.",
  },
  "5": {
    title: "Sorsszám 5 jelentése — A Szabadság keresője",
    lead: "Az 5-ös sorsszámot a numerológiai hagyomány a változás, szabadság és tapasztalati tanulás jelképeként olvassa. Nem kész életstílust ír elő, inkább azt mutatja, hol lehet fontos a mozgástér, kíváncsiság és józan belső irány egyensúlya.",
    essence:
      "A sorsszám középpontjában a kíváncsiság és a változatosság iránti igény állhat. A hagyomány szerint ez a minta akkor támogató, ha az új tapasztalatok nem szétszórnak, hanem tágítják a látókört. A kísérletezés itt nem céltalanság, hanem annak keresése, hogyan lehet szabadságban is felelősen jelen lenni.",
    strengths:
      "Az 5-ös sorsszám erőssége a kíváncsiságban, mozgékonyságban és tapasztalati tanulásban jelenhet meg. Ez a minta könnyebben kapcsolódik új helyzetekhez, emberekhez és nézőpontokhoz, ha közben marad elég belső irány is. Támogató oldala a rugalmasság: az a képesség, hogy a változás ne szétszórjon, hanem tágítsa a látókört.",
    shadow:
      "Árnyékban az 5-ös mintázat szétszóródást, türelmetlenséget vagy a kötöttségektől való túl gyors távolodást jelezhet. Ilyenkor a sok lehetőség nem feltétlenül szabadságot ad, hanem nehezítheti az elmélyülést és a befejezést. A józan keretek segíthetnek abban, hogy a változás ne menekülés, hanem tudatos mozgás legyen.",
    love: "Párkapcsolatban az 5-ös mintázat a szabadság, frissesség és őszinte mozgástér kérdéseit hozhatja elő. Nem szenvedélyt vagy tartós kötődést ígér, inkább arra figyelmeztet, hogy a közelség akkor marad élhető, ha a függetlenség és a felelős jelenlét egyszerre kap helyet.",
    career:
      "Nem kész karrierutat jelöl, inkább azt mutatja, hogy az 5-ös mintázathoz jól illhet a változatosság, tanulás, kommunikáció és mozgástér. Támogató lehet olyan közeg, ahol új helyzetekhez lehet alkalmazkodni, de marad elég fókusz, keret és felelősség ahhoz, hogy az ötletek ne csak elinduljanak, hanem végig is érjenek.",
    advice:
      "Érdemes tudatosan keresni azt a stabil keretet, amely nem zár be, hanem megtartja a kíváncsiságot. A változékonyság ereje akkor válhat hasznossá, ha van mellette néhány vállalt irány, lezárt lépés és visszatérő kapaszkodó. Így a szabadság nem szétszóródásként, hanem felelősen kezelt mozgástérként jelenhet meg.",
  },
  "6": {
    title: "Sorsszám 6 jelentése — A gondoskodó szív",
    lead: "A 6-os sorsszámot a numerológiai hagyomány a gondoskodás, felelősség és kapcsolati harmónia jelképeként olvassa. Nem kész szerepet ír elő, inkább azt a mintát mutatja, ahol fontos lehet a figyelmes jelenlét és az egészséges határtartás egyensúlya.",
    essence:
      "A 6-os szám hagyományos olvasata a szeretet, a harmónia és a felelősség témáit emeli előtérbe. Nem azt állítja, hogy mindig neked kell megtartanod másokat, inkább arra emlékeztethet, hogy a gondoskodás akkor marad tiszta, ha önmagad felé is működik.",
    strengths:
      "A 6-os mintázat erőssége a figyelmes kapcsolódás, a felelősségvállalás és a békésebb légkör keresése lehet. Támogató oldala akkor látszik tisztán, amikor a gondoskodás nem önfeladás, hanem kölcsönös, emberi léptékű jelenlét. A hagyomány szerint ez a szám a szépség, rend és kapcsolati figyelem iránti érzékenységet is jelezheti.",
    shadow:
      "A 6-os árnyéka akkor jelenhet meg, amikor a gondoskodás csendes önfeladásba, túlzott alkalmazkodásba vagy kimondatlan elvárásba fordul. A harmónia keresése ilyenkor nem pihenést ad, hanem belső feszültséget gyűjthet. A hagyomány szerint ez a szám arra emlékeztet, hogy a szeretet csak akkor marad tiszta, ha önmagad felé is működik.",
    love: "Párkapcsolatban a 6-os mintázat a gondoskodás, otthonosság és kölcsönös figyelem témáit erősítheti. Nem hűséget vagy romantikát ígér, inkább arra figyelmeztet, hogy a szeretet akkor marad megtartó, ha nem válik túlzott alkalmazkodássá vagy csendes önfeladássá.",
    career:
      "Nem kész pályaképet ad, inkább azt jelzi, hogy a 6-os mintázathoz jól illhetnek azok a közegek, ahol a felelősség, a rendezettség, a szépség vagy a kapcsolati figyelem kap szerepet. Támogató lehet minden olyan munka, ahol a gondoskodás nem önfeladás, hanem átlátható keretekkel és kölcsönösséggel társul.",
    advice:
      "A 6-os tanulsága a hagyomány szerint az, hogy a figyelem nem azonos az önfeladással. Érdemes különválasztani, mi az, amit szívesen adsz, és mi az, amit már csak békefenntartásból vállalsz. A kapcsolataid akkor maradnak megtartók, ha a gondoskodás mellett a saját pihenésednek és határaidnak is van helye.",
  },
  "7": {
    title: "Sorsszám 7 jelentése – A tudáskereső útja",
    lead: "A 7-es sorsszámot a numerológiai hagyomány a csendes elmélyülés, a kérdezés és a belső figyelem jelképeként olvassa. Nem rejtett igazságot vagy különleges tudást ígér, inkább azt a mintát mutatja, ahol fontos lehet a megértés keresése és a józan kapcsolódás egyensúlya.",
    essence:
      "A 7-es szám hagyományos olvasata a kutatás, elemzés és befelé figyelés témáit emeli előtérbe. Támogató oldala nem felsőbb tudás, hanem annak igénye, hogy a felszín mögött is legyen idő kérdezni, rendszerezni és megérteni. Akkor marad földelt, ha a csend nem elszigetelődésbe, hanem tisztább rálátásba vezet.",
    strengths:
      "A 7-es mintázat erőssége a figyelmes megfigyelés, az elemzés és az elmélyült tanulás lehet. Jól működhet ott, ahol nem kell azonnal választ adni, hanem lehet időt hagyni a pontosabb megértésnek. A hagyomány szerint ez a szám a belső csend és a józan kíváncsiság értékére emlékeztethet.",
    shadow:
      "Árnyékban a 7-es mintázat túlzott elvonulást, túlelemzést vagy bizalmatlanabb belső ritmust jelezhet. Ilyenkor a csend nem feltétlenül pihenés, hanem távolságtartás is lehet, ezért fontos a kapcsolódás apró, biztonságos formáit megtartani. A józan kérdezés segíthet abban, hogy a mélységkeresés ne elszigetelődésbe forduljon.",
    love: "Párkapcsolatban a 7-es mintázat a bizalom, a belső tér és a fokozatos megnyílás kérdéseit hozhatja elő. Nem hűséget vagy különleges spirituális kapcsolódást ígér, inkább arra figyelmeztet, hogy a közelség akkor mélyülhet, ha az elmélyülés mellett marad őszinte kommunikáció és hétköznapi jelenlét is.",
    career:
      "Nem kész pályaválasztási tanács, inkább azt jelzi, hogy a 7-es mintázatban erős lehet a kutatás, elemzés és csendes elmélyülés igénye. Jól illhet hozzá olyan közeg, ahol van idő kérdezni, rendszerezni, írni vagy összefüggéseket keresni, de ez nem igazol konkrét hivatást. A munka akkor támogató, ha nem zár el teljesen másoktól, és a tudáskeresést józan kapcsolódással egészíti ki.",
    advice:
      "Érdemes tudatosan keresnie az egyensúlyt a belső elmélyülés és a külvilággal való kapcsolódás között. Próbáljon meg nyitottabb lenni, és megosztani gondolatait másokkal, anélkül, hogy attól tartana, hogy nem értik meg. Engedje meg magának, hogy időnként csak legyen, és ne mindig a válaszokat keresse.",
  },
  "8": {
    title: "Sorsszám 8 jelentése – A Végrehajtó energiája",
    lead: "A 8-as sorsszám a numerológiában az eredményesség, felelősség és hatás jelképe. Nem sikert vagy rangot ígér, inkább azt a mintát mutatja, ahol fontos lehet az erő, a mérték és a józan építkezés egyensúlya.",
    essence:
      "A 8-as sorsszám a kiegyensúlyozott erőfeszítés és következmény körforgását jelképezi. Ez a szám az eredmény, felelősség és hatás kérdését hozza előtérbe: hogyan bánsz az erőddel, a döntéseiddel és azzal, amit felépítesz. A szimmetrikus alakja is a stabilitás és méltányosság fontosságára utal.",
    strengths:
      "A 8-as mintázat erőssége a céltudatos építkezés, a stratégiai gondolkodás és a felelősségvállalás lehet. Akkor működik jól, ha az eredmény nem önigazolás, hanem rendezett, másokat is figyelembe vevő építés. A kitartás és a türelem itt nem garantált jólétet jelent, hanem azt, hogy a nagyobb célokhoz következetes, józan lépésekre van szükség.",
    shadow:
      "A 8-as árnyéka akkor erősödhet fel, amikor az eredmény, kontroll vagy külső elismerés túl nagy szerepet kap. Ilyenkor a felelősség könnyen nyomássá, a céltudatosság pedig keménységgé válhat. A hagyomány szerint ez a szám arra hív, hogy az erő mellé mérték, méltányosság és valódi együttműködés társuljon.",
    love: "Párkapcsolatban a 8-as mintázat a stabilitás, kölcsönös tisztelet és közös építkezés témáit hozhatja elő. Nem erős vagy ambiciózus partnert ír elő, inkább azt mutatja, hogy a kapcsolat akkor marad egyensúlyban, ha egyik fél eredményei sem nyomják el a másik ritmusát. A közös siker itt akkor megtartó, ha emberi figyelemmel párosul.",
    career:
      "A 8-as mintázathoz jól illhetnek azok a helyzetek, ahol stratégia, felelősség, szervezés és mérhető eredmény is megjelenik. Nem vezetői rangot vagy vállalkozói sorsot igazol, inkább azt jelzi, hogy a hatás és az erőforrások kezelése fontos tanulási tér lehet. A munka akkor támogató, ha az eredmény nem puszta önigazolás, hanem tartós rend és felelős értékteremtés.",
    advice:
      "A 8-as tanulsága a hagyomány szerint az, hogy az erő akkor marad tiszta, ha nem válik ellenőrzéssé. Érdemes figyelni, hol akarsz túl gyorsan bizonyítani, és hol lenne bölcsebb bevonni másokat. A valódi tartás nem a nyomás fokozásából, hanem a mértékből, következetességből és méltányos együttműködésből épül.",
  },
  "9": {
    title: "Sorsszám 9 jelentése — A tágabb rálátás",
    lead: "A 9-es sorsszámot a numerológiai hagyomány a lezárás, elengedés és tágabb emberi rálátás jelképeként olvassa. Nem spirituális állomást vagy segítő szerepet ír elő, inkább azt a mintát mutatja, ahol a tapasztalatból együttérzőbb, józanabb jelenlét formálódhat.",
    essence:
      "Ez a sorsszám az emberségesség, a bölcsesség és az együttérzés jelképe a numerológiai hagyományban. Nem kész spirituális válaszokat ad, inkább a lezárás, elengedés és tágabb rálátás témáit hozza előtérbe. A 9-es mintázat akkor támogató, ha a jó szándék nem önfeladásba fordul, hanem józan figyelemmel és egészséges határokkal párosul.",
    strengths:
      "A 9-es mintázat erőssége lehet a tapasztalatokból érkező együttérzés, a tágabb nézőpont és az, hogy könnyebben észreveszed mások emberi oldalát. Nem felsőbb tudást vagy megmentő szerepet jelent, inkább azt, hogy a nehézségekből tanulságot, mértéket és tiszteletteljes jelenlétet lehet formálni. Akkor működik jól, ha a segítő szándék mellett a saját határaidat is komolyan veszed.",
    shadow:
      "A 9-es árnyéka lehet, amikor a régi sérelmek túl nagy teret kapnak, vagy a segítő szándék csendes önfeladásba fordul. Nem személyes kötelességet ír elő mások nehézségeivel kapcsolatban, inkább arra figyelmeztet, hogy az együttérzés csak világos határokkal marad tartós és tiszta.",
    love: "Párkapcsolatban a 9-es mintázat az együttérzés, a lezáratlan történetek és a közös fejlődés témáit hozhatja elő. Nem mély elköteleződést vagy spirituális összeillést ígér, inkább azt mutatja, hogy a kapcsolódás akkor marad egészséges, ha a figyelem mellett az önazonosság és a határtartás is jelen van.",
    career:
      "A 9-es sorsszám olyan munkákban találhat több értelmet, ahol emberi figyelem, tanítás, támogatás, közösségi szemlélet vagy kreatív önkifejezés kap helyet. Nem pusztán a cím vagy fizetés érdekli, hanem az, hogy amit csinál, hordoz-e tágabb emberi értelmet.",
    advice:
      "A 9-es tanulsága a hagyomány szerint az, hogy az együttérzés nem önfeladás. Érdemes a lezáratlan történetekre józan figyelemmel ránézni, közben pedig megtartani a saját szükségleteidet, pihenésedet és döntési teredet is.",
  },
  "11": {
    title: "A Sorsszám 11 jelentése — A Mester-Intuitív",
    lead: "A 11-es sorsszámot a numerológiai hagyomány mesterszámként, az ihlet, érzékeny figyelem és földelt jelenlét jelképeként olvassa. Nem különleges képességet vagy spirituális rangot ír le, inkább azt a mintát mutatja, ahol fontos lehet az érzékenység józan formába rendezése.",
    essence:
      "A 11-es sorsszám hagyományos olvasata az intuíció, érzékenység és belső figyelem témáit emeli előtérbe. Nem különleges képességet vagy gondolatolvasást jelent, hanem azt jelezheti, hogy a finom benyomásokat érdemes józan keretben vizsgálni. A 11-es út ezért nem elszakadás a valóságtól, hanem annak tanulása, hogyan lehet az ihletet földelt, józan formába rendezni.",
    strengths:
      "A 11-es mintázat erőssége lehet az érzékeny megfigyelés, az ihlet és az, hogy a finomabb hangulatokból is értelmes formát keressen. Támogató oldala akkor látszik tisztán, ha az intuíció nem bizonyosságként jelenik meg, hanem kérdésként, figyelemként és földelt megfogalmazásként. A határok itt különösen fontosak.",
    shadow:
      "Árnyékban a 11-es mintázat túlterheltséget, túlelemzést vagy a külső visszajelzésekre való túl erős ráhangolódást jelezhet. Ilyenkor az érzékenység nem feltétlenül tisztább látás, hanem zajosabb belső tér is lehet. A józan ritmus, pihenés és ellenőrizhető valóságkapcsolat segíthet abban, hogy az ihlet ne önbizonytalanságba forduljon.",
    love: "Párkapcsolatban a 11-es mintázat az őszinteség, finom figyelem és érzelmi biztonság kérdéseit hozhatja elő. Nem spirituális kapcsolódást vagy különleges összeillést ígér, inkább arra figyelmeztet, hogy a közelség akkor marad megtartó, ha az érzékenység mellett világos kommunikáció és határtartás is jelen van.",
    career:
      "Nem spirituális hivatást vagy különleges rangot jelöl, inkább azt mutatja, hogy a 11-es mintázatban fontos lehet az értelmes, figyelmes és emberi léptékű munka. Jól illhet hozzá olyan közeg, ahol az intuíció, kreativitás, írás, tanítás vagy támogatás józan keretek között kap helyet. A munka akkor marad megtartó, ha az ihlet nem önfeladásba fordul, hanem világos határokkal és földelt felelősséggel társul.",
    advice:
      "Érdemes az érzékeny benyomásokat nem azonnali igazságként, hanem finom jelzésként kezelni. Segíthet, ha az ihletet leírod, összeveted a helyzet tényeivel, és hagysz időt a döntéseknek. A 11-es mintázat akkor válhat megtartóvá, ha a belső figyelemhez földelt ritmus és emberi léptékű elvárás társul.",
  },
  "22": {
    title: "Sorsszám 22 jelentése — A felelős építés",
    lead: "A 22-es sorsszámot a numerológiai hagyomány a nagyobb tervek, gyakorlati forma és felelős építkezés jelképeként olvassa. Nem rangot vagy különleges sorsot ír le, inkább azt a mintát mutatja, ahol az elképzelések józan, lépésről lépésre követhető formát keresnek.",
    essence:
      "A 22-es hagyományos olvasata az elképzelés és a konkrét tett közötti hidat emeli előtérbe. Nem nagyobb teherbírást vagy különleges feladatot bizonyít, inkább arra figyelmeztet, hogy a nagyobb tervek csak emberi ritmussal, átlátható lépésekkel és másokra is figyelő felelősséggel maradnak megtartók.",
    strengths:
      "A 22-es mintázat erőssége lehet, hogy az ötletek nem maradnak puszta elképzelések, hanem rendszert, tervet és következő lépést kaphatnak. Nem minden akadály legyőzését ígéri, inkább azt támogatja, hogy a nagyobb célok mellett is maradjon mérték, együttműködés és emberi lépték.",
    shadow:
      "A 22-es árnyéka lehet, amikor a tökéletesség keresése késlelteti a józanul elégséges megoldásokat, vagy a felelősség túl nagy belső nyomássá válik. Nem azt jelenti, hogy mindent egyedül kell kézben tartani, inkább arra hívja fel a figyelmet, hogy a tartós építéshez pihenés, delegálás és kapcsolati jelenlét is kell.",
    love: "Párkapcsolatban a 22-es mintázat a közös tervek, felelősség és hosszabb távú építkezés témáit hozhatja elő. Nem ambiciózus vagy intenzív kapcsolatot ír elő, inkább azt mutatja, hogy a nagyobb célok mellett a pihenés, az érzelmi jelenlét és a kölcsönös ritmus is számít.",
    career:
      "Nem kész szakmai címke, inkább azt jelzi, hogy a 22-es mintázatban fontos lehet a rendszerek, struktúrák és hosszabb távú tervek építése. Jól illhet hozzá olyan közeg, ahol a víziót módszeres munkává, felelősen követhető lépésekké és mások számára is átlátható renddé lehet formálni. Ez nem vezetői rangot ígér, hanem a nagyobb léptékű feladatok józan, emberi ritmusának keresését támogatja.",
    advice:
      "A 22-es tanulsága a hagyomány szerint az, hogy a nagyobb tervek is csak emberi léptékben tarthatók meg. Érdemes a víziót kisebb, ellenőrizhető lépésekre bontani, közben pedig komolyan venni a pihenést, a segítségkérést és a kapcsolatok hétköznapi gondozását is.",
  },
  "33": {
    title: "Sorsszám 33 jelentése — Az Önzetlen Tanító",
    lead: "A 33-as sorsszámot a numerológiai hagyomány mesterszámként, a gondoskodó figyelem és felelősen adott támogatás jelképeként olvassa. Nem önzetlen szolgálatot vagy spirituális küldetést ír elő, inkább azt a mintát mutatja, ahol fontos lehet a szeretetteljes jelenlét és az egészséges határtartás együttese.",
    essence:
      "A 33-as szám hagyományos olvasata a gondoskodás, tanítás, közösségi figyelem és emberi felelősség témáit emeli előtérbe. Nem egyetemes szeretetet vagy különleges rangot igazol, inkább arra emlékeztethet, hogy a támogatás akkor marad tiszta, ha nem önfeladásból, hanem józan jelenlétből indul.",
    strengths:
      "A 33-as mintázat erőssége lehet a figyelmes támogatás, a tanulás átadása és az, hogy a nehéz tapasztalatokból emberibb forma születhet. Támogató oldala akkor látszik tisztán, amikor a gondoskodás nem megmentő szerep, hanem kölcsönös tisztelet és mérték. A hagyomány szerint ez a szám kreatív vagy közösségi közvetítésben is erősebb témává válhat.",
    shadow:
      "Árnyékban a 33-as mintázat túl nagy felelősségvállalást, önmagad háttérbe szorítását vagy megmentő szerepbe csúszást jelezhet. Ilyenkor a segítség könnyen kimerítővé válhat, ha nincs mellette pihenés, visszajelzés és világos határ. A józan mérték segít abban, hogy a gondoskodás ne váljon csendes önfeladássá.",
    love: "Párkapcsolatban a 33-as mintázat a gondoskodás, érzékeny figyelem és kölcsönös felelősség kérdéseit hozhatja elő. Nem mély elköteleződést vagy spirituális összeillést ígér, inkább arra figyelmeztet, hogy a szeretet akkor marad megtartó, ha egyik fél sem válik a másik megmentőjévé.",
    career:
      "A 33-as mintázathoz jól illhetnek azok a helyzetek, ahol tanítás, támogatás, közösségi figyelem vagy kreatív közvetítés kap szerepet. Nem spirituális rangot vagy hivatást igazol, inkább azt jelzi, hogy a gondoskodó jelenlét és az értelmes forma erősebb témává válhat. Művészi, írásos vagy segítő jellegű közegben akkor hasznos, ha egészséges határokkal és józan felelősséggel társul.",
    advice:
      "Érdemes figyelni arra, hogy a támogatás ne menjen a saját szükségleteid rovására. A 33-as mintázat akkor válhat érettebbé, ha a gondoskodás mellett pihenés, visszajelzés és kölcsönösség is helyet kap. Nem kell tökéletesen tartanod másokat: elég, ha emberi léptékben, világos határokkal vagy jelen.",
  },
};

export const LIFE_PATH_NUMBERS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 22, 33] as const;
