// AUTO-GENERATED by scripts/bake-lifepath.ts — do not edit by hand.
// Számmisztikai jelentéstár magyar olvasatokhoz.

export type LifePathMeaning = {
  title: string;
  lead: string;
  essence: string;
  strengths: string;
  shadow: string;
  love: string;
  career: string;
  advice: string;
};

export const LIFE_PATH_MEANINGS_HU: Record<string, LifePathMeaning> = {
  "1": {
    title: "Sorsszám 1 jelentése – Az úttörő vezető",
    lead: "Az 1-es sorsszám az önállóság, az újrakezdések és a vezetői képességek szimbóluma, amely erőteljes lendülettel visz előre.",
    essence:
      "Ez a szám a kezdeményezőkészséget, az innovációt és a magabiztosságot testesíti meg. Az 1-es arra ösztönöz, hogy bízzunk a saját erőnkben, és alakítsuk a körülményeinket. A teremtés és a kezdetek energiáját hordozza, amely a lehetőségek gyökerét jelenti az életünkben.",
    strengths:
      "Az 1-es sorsszámú személyek rendkívül önállóak, nem várnak a lehetőségekre, hanem megteremtik azokat. Célratörők és pozitív életszemléletűek, folyamatos fejlődésre vágynak. Innovatív gondolkodásmódjuk révén az akadályokat kihívásként kezelik, és kreatív megoldásokkal néznek szembe a nehézségekkel.",
    shadow:
      "Erőteljes előrehaladásuk során hajlamosak lehetnek túl dominánssá válni, ami figyelmetlenséggel párosulva sértést okozhat másoknak.  A túlzott kockázatvállalás és a korlátozott látásmód elkerülhető problémákhoz vezethet. Belső bizonytalanságuk, a hibáktól való félelem mélyen élhet bennük, noha kifelé ezt ritkán mutatják.",
    love: "Párkapcsolataikban az önállóság és a tisztelet kulcsfontosságú. Olyan társat kereshetnek, aki támogatja függetlenségüket, és értékeli vezetői hajlamaikat, miközben teret ad egyéniségüknek.",
    career:
      "Vezetői, önálló és úttörő szerepekben bontakoznak ki igazán, ahol saját elképzeléseiket valósíthatják meg, és irányíthatják a folyamatokat. Vállalkozóként, ügyvezetőként, feltalálóként vagy előadóként találhatják meg a helyüket, ahol nem kötik a merev keretek.",
    advice:
      "Érdemes tudatosítani a benned rejlő vezetői potenciált és az önállóság iránti igényedet. Figyelj arra, hogy az előrehaladásod során ne feledkezz meg mások érzéseiről és igényeiről, és néha lassíts le, hogy láthasd a teljes képet.",
  },
  "2": {
    title: "Sorsszám 2 jelentése — A Béketeremtő",
    lead: "A 2-es Sorsszám a rendkívüli női energiát, a kecsességet és a harmonikus erőteljes jelleget ötvözi. Kiemelkedően együttműködő, mindig a béke és az egyensúly megteremtésére törekszik.",
    essence:
      "A 2-es szám a numerológiában a rendkívüli női energiát képviseli, mely egyszerre hordoz kecsességet és erőt. Az együttműködésre fókuszál, mindig azt célozza, hogy békét és egyensúlyt hozzon egy kapcsolatba vagy helyzetbe. Ez a Sorsszám rendkívül érzékeny, és a legerősebb intuitív képességekkel rendelkezik a számok között. Ösztönösen megérzi az áramlatokat és érzelmeket, melyeket felhasználva empátiával kapcsolódik másokhoz.",
    strengths:
      "Mély és tudattalan szinten képes érzékelni az energiákat, melyek csak érezhetők, de nem láthatók. Ez az intuitív vonása lehetővé teszi számára, hogy ösztönösen tudatában legyen mások érzéseinek, gondolatainak és félelmeinek, még mielőtt azok kifejeződnének, és támogassa a partnerségeket. A 2-es egy igazi béketeremtő, aki élesen tudatában van az együttműködés értékeinek. Diplomatikusan jár el, mert bármi más egyensúlyhiányt teremtene. Hatalmas befolyással bír helyzetekre és kapcsolatokra, de ezt olyan óvatosan teszi, hogy hatása szinte észrevétlen marad.  Úgy dolgozik a háttérben, hogy az eredmények tagadhatatlanok.",
    shadow:
      "Az a vágy, hogy mindig középen maradjon, megnehezíti a részrehajlás felismerését, ami mind nagy, mind kicsi döntések meghozatalát akadályozza. Amikor nem tudja azonosítani a preferenciáját egyik vagy másik irányba, akkor tehetetlenségbe kerül. A harmónia megteremtésének vágya olyan erős, hogy a legkisebb sértés is kibillenti ebből az egyensúlyból. Rendkívül érzékeny energiákról van szó. Az egyensúly és béke fenntartása érdekében a saját szükségleteit hajlamos mások mögé helyezni. Sokkal passzívabb, mint asszertív.",
    love: "A 2-es Sorsszámmal rendelkezők mélyen érzékeny, empatikus és gondoskodó partnerek. Kiválóan alkalmasak arra, hogy megnyílt, támogató párkapcsolatokat építsenek. A békére és harmóniára törekszenek a szerelemben, gyakran ők a diplomáciai kapocs a kapcsolatban.",
    career:
      "Ez a sorsszám olyan szerepekben érzi magát otthonosabban, ahol diplomácia, empátia és együttműködés kell. Jól illhet hozzá a közvetítés, támogatás, emberi kapcsolatok rendezése, csapatmunka vagy olyan háttérszerep, ahol finoman lehet egyensúlyt teremteni. A támogató környezetben könnyebben nyílik ki, mint a kíméletlen versenyben.",
    advice:
      "Érdemes tudatosítani az asszertivitás jelentőségét és azt, hogy a saját szükségleteink kielégítése nem feltétlenül rombolja a harmóniát. Fontos megtanulni határokat húzni és kimondani a véleményünket, még ha az eltér is másoktól. Próbálja meg gyakorolni a döntéshozatalt kisebb dolgokban, hogy fejlessze az önbizalmát ezen a téren.",
  },
  "3": {
    title: "Sorsszám 3 jelentése — Az életöröm és kreativitás útja",
    lead: "A 3-as Sorsszám az önkifejezés, a kommunikáció és az optimista életszemlélet erejét hordozza. Egy örökifjú lélek, aki a kapcsolódásokon és a kreatív megnyilvánulásokon keresztül teljesedik ki.",
    essence:
      "Ezen sorsszám energiája fiatalos, pozitív és tele van életerővel. Az életet egy táncnak tekinti, ahol egyik élvezetes élményből a másikba lendül, miközben folyamatosan kapcsolatba lép másokkal.  Fő mozgatórugója a vidámság, a spontaneitás és a szépség megteremtése a mindennapokban. Az absztrakt gondolatok és művészeti kifejezések mestere, aki szívesen osztja meg belső világát másokkal.",
    strengths:
      "Kiemelkedő kommunikációs képességekkel rendelkezik, ötletei és gondolatai gazdag áramlása inspirálóan hat a környezetére.  Művészi érzéke és kreatív vénája lehetővé teszi számára, hogy mélyebb érzéseket fejezzen ki, túllépve a szavakon.  Természetes bájjal és karizmával vonzza magához az embereket, könnyedén teremt barátságokat és tartja fenn az érdeklődést, bárhová is érkezzen.",
    shadow:
      "Időnként naivitás jellemezheti, nehezen ismeri fel a világ árnyoldalait, ami sebezhetővé teszi. Hajlamos lehet a szétszórtságra, mivel egyszerre sok dolog iránt lelkesedik, és nehezen koncentrál egyetlen célra.  A mélyebb érzelmek és konfliktusok elől való menekülés is előfordulhat, inkább a felületes, ám kellemes interakciókat preferálja, a nehézségeket kerülve.",
    love: "Párkapcsolataiban játékos, kifejező és spontán, örömmel tölti meg a közös pillanatokat.  Számára fontos az intellektuális és érzelmi kapcsolódás, a könnyed és vidám légkör fenntartása.  A beszélgetésekben és a közös alkotásban találja meg a harmóniát, de óvakodnia kell attól, hogy a konfliktusokat elkerülje, ahelyett, hogy szembenézne velük.",
    career:
      "Kreatív területeken bontakozik ki leginkább, ahol önkifejezésének és kommunikációs tehetségének szabad teret engedhet. Íróként, előadóművészként, zenészként vagy marketingesként is sikeres lehet, de vállalkozóként, oktatóként vagy rendezvényszervezőként is kiteljesedhet. Fontos számára a változatosság és a társas érintkezés, egy merev vállalati környezet kiégetné.",
    advice:
      "Törekedjen arra, hogy a felszínesség helyett merjen mélyebbre tekinteni önmagában és a kapcsolataiban.  Fogadja el, hogy a kihívások is részei az életnek, és érdemes időt szánni a fókusz megtartására a célok eléréséhez.  A kibontakozó képességei és örök optimizmusa igazi ajándék, melyekkel gazdagíthatja saját életét és másokét is, ha tudatosan használja őket.",
  },
  "4": {
    title: "Sorsszám 4 jelentése —  Az építő alapokon",
    lead: "A 4-es sorsszám a stabilitás, a rendszerezettség és a megbízhatóság energiáját hordozza. Azoknak szól, akik a gondos építkezést és a tartós értékeket képviselik az életben.",
    essence:
      "Ezen sorsszám rezgése a földelésről, a kitartó munkáról és a gyakorlati megközelítésről szól. A 4-es energiát hordozó személyek általában konkrét, mérhető eredményeket szeretnének látni, és ragaszkodnak a bevált módszerekhez. Számukra a szervezettség és a rendszer a biztonság alapja.",
    strengths:
      "Az életút 4-esek rendkívül gyakorlatiasak, realista a világlátásuk, nem tévesztik meg őket az illúziók. Hűségesek és megbízhatóak, nagy hangsúlyt fektetnek a tartós kapcsolatokra és a stabil alapokra. Szolgálatkészek, tudják, hogy a jó eredményekhez idő és erőfeszítés szükséges, örömmel áldozzák idejüket mások támogatására.",
    shadow:
      "Időnként dogmatikussá válhatnak, mereven ragaszkodnak a saját igazukhoz, és nehezen fogadnak el más nézőpontokat. Előfordulhat, hogy túlságosan is ragaszkodnak a megszokotthoz, és elutasítanak minden újdonságot, ami unalmassá vagy fantáziátlanná teheti őket. Rugalmatlanságuk miatt nehezen illeszkednek be olyan helyzetekbe, ahol kompromisszumra és csapatmunkára van szükség.",
    love: "Párkapcsolataikban a stabilitásra és a hosszú távú elköteleződésre törekednek. Hűségesek, megbízhatóak és odaadóak, akik számára a tartós biztonság fontosabb, mint a spontán kalandok. Hajlamosak lehetnek a megszokott rutinokhoz ragaszkodni, és szükségük van egy olyan partnerre, aki értékelni tudja a biztonságra való törekvésüket és a kitartó gondoskodásukat.",
    career:
      "A 4-es sorsszámúak kiválóak azokban a szakmákban, ahol precizitás, szervezettség és módszeres gondolkodás szükséges. Jól érzik magukat mérnökként, könyvelőként, építészként, projektmenedzserként vagy olyan területeken, ahol stabil alapokat és rendszereket építhetnek. A kitartó munkájuk és a részletekre való odafigyelésük kiemelkedővé teszi őket.",
    advice:
      "Érdemes nyitottságot fejlesztened az új ötletek és perspektívák iránt, még akkor is, ha az elsőre szokatlannak tűnik. Engedd meg magadnak a rugalmasságot, és kísérletezz néha a megszokott mintákon kívül. Emlékezz, a stabilitás érték, de az alkalmazkodás képessége, az építő újdonságok befogadása tovább építheti az életed alapjait.",
  },
  "5": {
    title: "Sorsszám 5 jelentése — A Szabadság keresője",
    lead: "Az 5-ös sorsszám a változékonyság, a szabadság és az élmények iránti vágy megtestesítője. Életében a felfedezés és az új tapasztalatok gyűjtése áll a középpontban.",
    essence:
      "A sorsszám középpontjában a kíváncsiság és a változatosság iránti igény áll. A beteljesedést az izgalmas élmények sokaságában találja meg, és bátran hagyja, hogy a 'szél sodorja'. Ez a szám nem a merev tervek vagy célkitűzések embere; sokkal inkább a kísérletezésről és a tapasztalásról szól az élete.",
    strengths:
      "Kíváncsi természete rendkívül nyitottá teszi az újdonságokra, sokrétű és izgalmas élményekhez juttatva. Képes alkalmazkodni a változásokhoz, könnyedén vált közeget és irányt, és a legkülönfélébb helyzetekben is megtalálja a helyét. Társas lény, aki szívesen lép kapcsolatba másokkal, hiszen az interakciókon keresztül szerzi a legjobb tapasztalatokat és bővíti látókörét.",
    shadow:
      "Az elköteleződés nehézsége jellemző lehet, mivel a szabadság iránti olthatatlan vágy miatt a kötöttségeket gyakran fojtogatóként élheti meg. Emiatt nehezebben mélyedhet el kapcsolatokban vagy szakmai feladatokban. A fegyelem hiánya és a könnyű elvonhatóság megbízhatatlanná teheti, ami kihívást jelenthet a projektek befejezésében és az ígéretek betartásában. Időnként céltalannak érezheti magát, ha nem talál olyan irányt, amely valós célokat szolgálna, és ezáltal értékes időt pazarolhat el.",
    love: "Ez a sorsszám nehezen köteleződik el, mivel a szabadságát félti, de ha megtalálja azt a partnert, aki értékeli a függetlenségét és együtt él át vele izgalmas kalandokat, akkor mély és szenvedélyes kapcsolatot alakíthat ki.",
    career:
      "A leginkább olyan munkakörökben teljesedik ki, amelyek szabadságot, változatosságot és állandó stimulációt biztosítanak. Kiválóan alkalmas az önálló vállalkozásra, értékesítésre, újságírásra, marketingre vagy utazással kapcsolatos foglalkozásokra. Jól érzi magát a gyorsan változó, innovatív és startup környezetekben.",
    advice:
      "Érdemes tudatosan keresni a stabilitást és megtanulni értékelni az elköteleződés mélységét, anélkül, hogy feladná a szabadságérzetét. A változékonyság erejét a hosszú távú célok szolgálatába állíthatja, így elkerülheti a céltalanságot. Fedezze fel, hogyan tudja ötvözni a kalandvágyat a felelősséggel, hogy teljesebb és kiegyensúlyozottabb életet élhessen.",
  },
  "6": {
    title: "Sorsszám 6 jelentése — A gondoskodó szív",
    lead: "A 6-os sorsszám a gondoskodás, a felelősség és a szeretet energiáját hordozza. Szívközpontú lényként fontos dolgod van a világban.",
    essence:
      "A 6-os szám mélyen gyökerező szeretetről, harmóniáról és együttérzésről tanúskodik. Képessé tesz mások támogatására, megnyugtatására és megtartására. Feladatod, hogy szívvel, de egészséges határokkal legyél jelen a környezetedben.",
    strengths:
      "Rendkívül támogató vagy, képes vagy figyelmesen meghallgatni másokat és valódi empátiával fordulni feléjük. Védelmező természettel bírsz, különösen a családod és a szeretteid iránt, és kiállsz azokért, akiknek nincs hangjuk. Romantikus lelkületű vagy, aki keményen dolgozik a békés, kölcsönös kapcsolatokért.",
    shadow:
      "Hajlamos lehetsz túlzottan passzív lenni, és mások kedvéért háttérbe szorítani a saját igényeidet. Az önfeláldozásod néha odáig vezethet, hogy elhanyagolod önmagad. Idealista látásmódod miatt csalódhatsz, amikor a valóság nem felel meg az elképzeléseidnek.",
    love: "Partnereid iránt hűséges, gondoskodó és rendkívül romantikus vagy, meleg és szeretetteljes otthont teremtve. Szeretetedet a gondoskodás, védelem és rendíthetetlen hűség által fejezed ki. Fontos, hogy megtaláld az egyensúlyt a szeretet és az esetleges túlzott ragaszkodás között.",
    career:
      "Kiválóan teljesíthetsz olyan területeken, ahol a szolgálat, a gondoskodás és a harmónia megteremtése a cél. Vonzódhatsz a tanácsadói, segítői, oktatói vagy közösségi szerepekhez. Értékeled a szépséget és az egyensúlyt, ami kreatív, otthonteremtő vagy kapcsolódást építő utak felé is vihet.",
    advice:
      "Próbáld meg tudatosabban figyelni a saját igényeidre, és ne hagyd, hogy az önfeláldozás kimerítsen. Fontos, hogy megtaláld az egyensúlyt a mások támogatása és az önmagad gondozása között. Emellett érdemes elfogadni, hogy nem mindenki osztozik az idealista elképzeléseidben, és ez nem von le az emberi kapcsolatok értékéből.",
  },
  "7": {
    title: "Sorsszám 7 jelentése – A tudáskereső útja",
    lead: "A 7-es sorsszám a mélységek, a bölcsesség és az elmélyült gondolkodás felé tereli egyéniségét. Ez az út a rejtett igazságok és a létezés mélyebb értelmének felfedezéséről szól.",
    essence:
      "Lényét a folytonos kutatás, az elemzés és a belső világ vizsgálata határozza meg. Nem elégszik meg a felszínes magyarázatokkal; a valódi értéket a mélyebb összefüggések megértésében találja. Keresi az okokat és a miérteket, miközben erős intuitív képességei vezetik a tudás felé.",
    strengths:
      "Kiemelkedő spirituális érzékenység jellemzi, mely a láthatatlan világ törvényszerűségei iránti fogékonyságban nyilvánul meg. Intellektuális megközelítésével, elemző képességével képes rendszerezni és értelmezni a megszerzett információkat. Elmélyedő kíváncsisága arra ösztönzi, hogy folyamatosan tanuljon és felfedezze az élet sokrétű aspektusait.",
    shadow:
      "Hajlamos lehet az elvonulásra, ami idővel elszigeteltséget okozhat, gátolva az új kapcsolatok kialakítását. Zárkózottsága és titoktartása megnehezítheti a mélyebb érzelmi kapcsolódást másokkal. Néha túl sokat analizál, és gyanakvóvá válhat, ott is keresve a rejtett motívumokat, ahol nincsenek.",
    love: "Párkapcsolataiban a valódi, mély intellektuális és spirituális kapcsolódásra vágyik. Nehezen nyílik meg, de ha megtalálja azt a partnert, aki megérti és tiszteletben tartja belső világát, akkor rendkívül hűséges és elkötelezett társsá válik. Fontos számára a bizalom és a megértés.",
    career:
      "Kiválóan teljesít olyan területeken, ahol a mély gondolkodást, kutatást és elemzést igénylő feladatok dominálnak. Tudós, kutató, filozófus, író, pszichológus vagy adatelemző munkakörben találhatja meg a hivatását. Fontos, hogy a munkája intellektuálisan kihívást jelentő és elmélyült legyen.",
    advice:
      "Érdemes tudatosan keresnie az egyensúlyt a belső elmélyülés és a külvilággal való kapcsolódás között. Próbáljon meg nyitottabb lenni, és megosztani gondolatait másokkal, anélkül, hogy attól tartana, hogy nem értik meg. Engedje meg magának, hogy időnként csak legyen, és ne mindig a válaszokat keresse.",
  },
  "8": {
    title: "Sorsszám 8 jelentése – A Végrehajtó energiája",
    lead: "A 8-as sorsszám a numerológiában az eredményességet, a hatalmat és az ambíciót testesíti meg. Azok, akik ezzel a sorsszámmal születtek, gyakran válnak kiemelkedő vezetőkké és sikeremberekké.",
    essence:
      "A 8-as sorsszám a kiegyensúlyozott erőfeszítés és következmény körforgását jelképezi. Ez a szám az eredmény, felelősség és hatás kérdését hozza előtérbe: hogyan bánsz az erőddel, a döntéseiddel és azzal, amit felépítesz. A szimmetrikus alakja is a stabilitás és méltányosság fontosságára utal.",
    strengths:
      "Az ezzel a sorsszámmal rendelkezők rendkívül céltudatosak, szinte élnek azért, hogy elérjék céljaikat. Ez a szám a stratégiai gondolkodás és az elhivatottság megtestesítője. Elismeri, hogy a sikereket nem egyedül éri el, és hálával viszonyul a kapott segítséghez, ezzel egyensúlyozva az eredményeket a hálával. Még a nehéz időkben is kitartó, alapvető bizalommal rendelkezik abban, hogy a kitartás és a türelem végül elvezeti a jóléthez.",
    shadow:
      "A 'nyolcasok' hajlamosak túl nagy hangsúlyt fektetni az anyagi javakra, az eredményeiket gyakran tárgyakkal 'jutalmazzák'. Ez a viselkedés mások számára felületesnek vagy hencegőnek tűnhet, és vonzhatja az opportunistákat. Elért eredményeik miatt hatalmi pozícióban érzik magukat, ami autokratikus viselkedéshez vezethet, figyelmen kívül hagyva mások véleményét és erőfeszítéseit. A siker utáni vágyuk gyakran vakká teszi őket a szabályokra és folyamatokra, ami megnehezíti a csapatmunkát és a partnerségeket.",
    love: "Párkapcsolataikban a 8-as sorsszámúak stabilitásra és kölcsönös tiszteletre törekednek. Fontos számukra, hogy partnerük elismerje és támogassa ambícióikat, de ugyanakkor ne érezze magát háttérbe szorítva. Egy egyenrangú és erős partnerre vágynak, akivel együtt építkezhetnek és osztozhatnak a sikereken.",
    career:
      "A 8-as sorsszámhoz jól illhetnek azok a területek, ahol stratégia, felelősség, szervezés és mérhető eredmény is megjelenik. Vezetői, vállalkozói, projektirányítói vagy értékteremtő szerepekben akkor tud jól működni, ha az anyagi világot nem puszta célként, hanem tartós rend és felelősség eszközeként kezeli.",
    advice:
      "Törekedj a belső és külső gazdagság kiegyenlítésére, és ne kizárólag az anyagi sikerekre fókuszálj. Ügyelj arra, hogy a vezetői ambícióid ne váljanak uralkodóvá, és adj teret mások véleményének. Tanuld meg, hogy a valódi hatalom nem az ellenőrzésben, hanem a bölcs együttműködésben és a megosztott sikerekben rejlik.",
  },
  "9": {
    title: "Sorsszám 9 jelentése — Az Önzetlen Segítő",
    lead: "A 9-es sorsszám a személyes fejlődés és a spirituális út egy fontos állomását jelöli. Az életed során szerzett tapasztalatokból merítve bölcsességedet mások megsegítésére fordíthatod.",
    essence:
      "Ez a sorsszám az önzetlen emberségesség, a bölcsesség és az együttérzés rezgését hordozza.  Nem egyszerűen befejezést jelent, hanem egy ciklus lezárását, ami új lehetőségek és kezdetek alapját teremti meg. A 9-es segít a változások és átalakulások folyamatában, spirituális forrásból merítve ad válaszokat a valós világ kihívásaira. Alapvetően jóságos és egyetemes szeretetre törekvő energia, mely a legnagyobb jót keresi.",
    strengths:
      "Az életed során szerzett tapasztalatok révén megtanultad belső bölcsességed értékét és erejét. Képes vagy másokat is felébreszteni saját magasabb énjükre, példát mutatva, hogyan kezelhetők eleganciával és megértéssel a nehézségek.  Rendkívül toleráns vagy, nem ítélkezel faj, vallás vagy életmód alapján, teret és tiszteletet adsz mindenkinek.  Szíved lágysága sokak számára vonzó, akik támogatást keresnek, és tudod, mi kell ahhoz, hogy túljuss a kihívásokon.",
    shadow:
      "A múltbéli nehéz tapasztalatok mély nyomot hagyhattak benned, és ha nem adsz teret a feldolgozásnak, a régi sérelmek árnyékot vethetnek kapcsolataidra. Hajlamos lehetsz túlzásba vinni az önfeláldozást, mások igényeinek előtérbe helyezésével elhanyagolhatod saját szükségleteidet. A sok megtapasztalt nehézség miatt néha többet tulajdoníthatsz a küzdelmes időszakoknak, mint a könnyedebb pillanatoknak.",
    love: "Párkapcsolataidban együttérző, odaadó és érzelmileg gazdag tudsz lenni. Fontos számodra a mély, értelmes kapcsolat, ahol mindketten fejlődhettek, de vigyázz, nehogy túlságosan feloldódj a másikban.",
    career:
      "A 9-es sorsszám olyan munkákban találhat több értelmet, ahol emberi figyelem, tanítás, támogatás, közösségi szemlélet vagy kreatív önkifejezés kap helyet. Nem pusztán a cím vagy fizetés érdekli, hanem az, hogy amit csinál, hordoz-e tágabb emberi értelmet.",
    advice:
      "Próbáld meg egyensúlyba hozni mások segítését a saját szükségleteid kielégítésével. Engedd meg magadnak a pihenést és a feltöltődést, hogy hosszú távon is hatékonyan tudj támogatást nyújtani. Fontos, hogy feldolgozd a múltbéli sérelmeket, hogy azok ne akadályozzák meg jelenlegi kapcsolataidat és a belső békédet.",
  },
  "11": {
    title: "A Sorsszám 11 jelentése — A Mester-Intuitív",
    lead: "A 11-es sorsszám különleges mesterszám a numerológiában, amely mély intuíciót és spirituális érzékenységet hordoz. Ez az út a belső tudás, finom érzékelés és földelt jelenlét összehangolásáról szól.",
    essence:
      "A 11-es sorsszámú embereket kivételes intuíció és rendkívüli érzékenység jellemzi. Képesek észlelni azokat a finom energiákat és összefüggéseket, melyek mások előtt rejtve maradnak. Életük során egyfajta belső tudás vezérli őket, ami a szellemi síkok mély megértéséből fakad. Gyakran érezhetik úgy, mintha mások gondolatait és érzéseit olvasnák, ami áldás és kihívás is egyben.",
    strengths:
      "Rendkívül intuitív lehetsz, gyorsan ráhangolódhatsz egy helyzet érzelmi légkörére. A 11-es erőssége, hogy a nagyobb képet is érzékeli, és finom összefüggéseket vesz észre ott, ahol mások csak részleteket látnak. Empatikus természeted mély kapcsolódást adhat, ha közben megtartod a saját határaidat is.",
    shadow:
      "Fokozott érzékenységed, bár a legnagyobb erőd, túlterhelővé válhat. A negatív érzelmek, a kemény környezet vagy a kritika mélyebben érinthet, ami szorongáshoz, önbizalomhiányhoz vagy elzárkózáshoz vezethet. Hajlamod van az analízisre és az önmagadban való elmélyedésre, ami döntésképtelenséget okozhat. Perfekcionista hajlamod miatt irreálisan magas elvárásokat támaszthatsz magaddal és másokkal szemben, ami frusztrációhoz vezethet, ha a valóság nem felel meg az ideális vízióidnak.",
    love: "Párkapcsolataidban a mély érzelmi és spirituális kapcsolódásra vágysz. Kulcsfontosságú számodra az őszinteség és a megértés, valamint egy olyan partner, aki képes elfogadni és támogatni egyedi érzékenységedet. Fontos, hogy megtaláld az egyensúlyt a szeretet és a függetlenség iránti igényed között.",
    career:
      "Kiválóan teljesítesz olyan területeken, ahol inspirálhatsz és felemelhetsz másokat, például spirituális tanácsadóként, segítőként vagy coachként. Látnoki természeted és kreatív tehetséged révén művészeti, írói vagy humanitárius munkakörökben is megtalálhatod a helyedet. Olyan foglalkozásra van szükséged, amely lélekszintű értelmet ad, hisz a puszta profitközpontú környezet ürességet okozhat.",
    advice:
      "Tanulj meg bízni a belső hangodban és az intuíciódban, ez a legfőbb iránytűd. Engedd meg magadnak, hogy megéld érzékenységedet, de találd meg a módját, hogy megvédd energiáidat a külső hatásoktól. Ne kritizáld magad, ha nem felelsz meg irreális elvárásaidnak; a tökéletesség helyett az önelfogadásra törekedj.",
  },
  "22": {
    title: "Sorsszám 22 jelentése — Az Építőmester útja",
    lead: "A 22-es sorsszám a „Mester Építő” energiáját hordozza, egyesítve a mély intuíciót a gyakorlati megvalósítás képességével. Ez az út a grandiózus elképzelések valósággá formálásáról szól.",
    essence:
      "Ez a szám nagy potenciált jelöl: hidat épít az elképzelés és a konkrét tett között. A 22-es akkor működik erősen, ha a vízió nem marad álom, hanem módszerességgel, felelősséggel és emberi érzékkel kap formát. Nem felsőbbrendűség, hanem nagyobb teherbírás és nagyobb tudatossági feladat.",
    strengths:
      "Erős képességed lehet arra, hogy nagyobb elképzeléseket gyakorlati fegyelemmel építs fel. Átláthatod a nagy képet, miközben a részleteket sem veszted szem elől. A 22-es ereje nem abban áll, hogy minden akadályt legyőz, hanem abban, hogy a nehézségekből is rendszert, tanulságot és következő lépést tud formálni.",
    shadow:
      "Előfordulhat, hogy a túlzott maximalizmusod megbénít, és a tökéletességre való törekvés megakadályoz abban, hogy elfogadd a „jó” megoldásokat. Ez gyakran késedelmekhez, stresszhez és kiégéshez vezethet. A hatalmas felelősségvállalás és a céljaid hajszolása közben könnyen figyelmen kívül hagyhatod a pihenést, a kapcsolataidat és az öngondoskodást, kimerülve a túlhajszoltságban. Nehezen delegálsz, mert úgy érzed, mindent jobban elvégzel magad, ami korlátozhatja a nagyszabású elképzeléseid kibontakozását.",
    love: "Párkapcsolataidban intenzív, céltudatos és ambiciózus vagy, olyan társat keresel, aki támogatja grandiózus vízióidat és megérti elhivatottságodat. Fontos, hogy olyan partnerre találj, aki képes felvenni a ritmust veled, és elfogadja, hogy a munkád gyakran központi szerepet játszik az életedben.",
    career:
      "Kiválóan teljesítesz olyan területeken, ahol rendszereket, struktúrákat és szervezeteket építhetsz, melyek sok ember javát szolgálják. Remek építész, mérnök, városfejlesztő, projektmenedzser vagy vállalkozó lehetsz. Vezetői szerepekben is kiemelkedő vagy, ahol monumentális léptékű és tartós hatású munkával foglalkozhatsz.",
    advice:
      "Érdemes tudatosítanod a benned rejlő építőerőt, de nem kell állandóan bizonyítanod. Fontos, hogy megtaláld az egyensúlyt a nagyszabású tervek és a személyes jóllét, kapcsolatok gondozása között. Az öngondoskodás nem gyengeség, hanem része annak, hogy hosszú távon is stabilan tudj jelen lenni.",
  },
  "33": {
    title: "Sorsszám 33 jelentése — Az Önzetlen Tanító",
    lead: "A 33-as sorsszám a feltétel nélküli szeretet és az önzetlen szolgálat rezgését hordozza. Ez az út mély támogatásra, tanításra és spirituális érlelődésre hív.",
    essence:
      "A 33-as sorsszám a mesterszámok közé tartozik, a szív és a lélek mélységeivel való összekapcsolódásról szól. Az egyetemes szeretet szimbóluma, amely másokat is emlékeztethet a reményre, az együttérzésre és a felelősségteljes jelenlétre. Ez az út a mély empátián és az élettapasztalatokon keresztül mutat irányt.",
    strengths:
      "Mélyen együttérző és empatikus, képes mások szenvedését autentikusan megérteni. Inspiráló jelenléte és tanítása motiválja az embereket a növekedésre és önfelfedezésre. Kreatív megközelítéssel és innovatív módon képes a komplex spirituális igazságokat átadni, láthatóvá téve a láthatatlant.",
    shadow:
      "Időnként túlzottan magas elvárásokat támaszthat önmagával és másokkal szemben, ami csalódottsághoz és kiégéshez vezethet. Mély érzelmi tudatossága sebezhetővé teszi a kritikával és negativitással szemben, határok kijelölésére lehet szüksége.  Az önfeláldozás tendenciája miatt hajlamos lehet elhanyagolni saját igényeit, ami kimerülést okozhat.",
    love: "Párkapcsolataiban mélyen elkötelezett, gondoskodó és spirituálisan érzékeny. Olyan társat keres, aki osztja szenvedélyét a fejlődés és a szolgálat iránt, és képes megérteni belső világának mélységeit.",
    career:
      "A tanítás, támogatás és közösségi emelés iránti elhivatottság jellemzi. Kiváló spirituális vezető, oktató, mentor vagy kreatív közvetítő lehet, akinek munkája a lélek mélységeit szólítja meg. Műtárgyakkal, zenével vagy írásokkal is átadhatja üzenetét, ha azok egy magasabb célt szolgálnak.",
    advice:
      "Mély empátiája erőt ad, de fontos, hogy megtanulja az egészséges érzelmi határokat felállítani. Fordítson figyelmet saját feltöltődésére és szükségleteire, hogy hosszú távon tudja adni a legjobbját. Engedje meg magának, hogy elfogadja a tökéletlenséget, és emlékezzen, hogy a legnagyobb tanítás a szeretetteljes jelenlét.",
  },
};

export const LIFE_PATH_NUMBERS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 22, 33] as const;
